<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/all.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr2d1 = np.arange(1, 13).reshape(3, 4)
arr2d1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
# 7
arr2d1[1, 2]

np.int64(7)

In [4]:
# 10
print(arr2d1[-1, 1])

10


In [5]:
# 1, 2
print(arr2d1[0, 0:2])

[1 2]


In [6]:
# 6, 7
print(arr2d1[1, 1:3])

[6 7]


In [7]:
# 11, 12
print(arr2d1[-1, 2:])

[11 12]


In [8]:
arr3d1 = np.random.randint(1, 100, size=(3, 3, 3))
print(arr3d1)

[[[44 70  1]
  [ 6 93 92]
  [19 13 70]]

 [[ 8 42 66]
  [68 10 33]
  [65 49 88]]

 [[62  7 10]
  [ 8 49 73]
  [82 68 42]]]


In [9]:
# 90, 21
print(arr3d1[0][0, 1:])

[70  1]


In [10]:
# 78
print(arr3d1[0][1, 0])

6


In [11]:
# 30, 5
print(arr3d1[0][-1, 1:])

[13 70]


In [12]:
# 34, 19, 27
print(arr3d1[1][-1, :])

[65 49 88]


In [13]:
# 8, 5
print(arr3d1[2][-1, 1:])

[68 42]


In [14]:
arr2d1[arr2d1 < 6] = 0
print(arr2d1)

[[ 0  0  0  0]
 [ 0  6  7  8]
 [ 9 10 11 12]]


In [15]:
arr2d2 = np.arange(6).reshape(3, 2)
print(arr2d2)

[[0 1]
 [2 3]
 [4 5]]


In [16]:
arr2d2.T

array([[0, 2, 4],
       [1, 3, 5]])

In [17]:
arr3d2 = np.arange(65, 92).reshape(3, 3, 3)
print(arr3d2)

[[[65 66 67]
  [68 69 70]
  [71 72 73]]

 [[74 75 76]
  [77 78 79]
  [80 81 82]]

 [[83 84 85]
  [86 87 88]
  [89 90 91]]]


In [18]:
arr3d2.swapaxes(0, 1)

array([[[65, 66, 67],
        [74, 75, 76],
        [83, 84, 85]],

       [[68, 69, 70],
        [77, 78, 79],
        [86, 87, 88]],

       [[71, 72, 73],
        [80, 81, 82],
        [89, 90, 91]]])

In [19]:
arr3d3 = np.arange(63, 87).reshape(3, 4, 2)
print(arr3d3)

[[[63 64]
  [65 66]
  [67 68]
  [69 70]]

 [[71 72]
  [73 74]
  [75 76]
  [77 78]]

 [[79 80]
  [81 82]
  [83 84]
  [85 86]]]


In [20]:
# 2D massivlar soni va qatorlar sonini almashtirish
arr3d3.swapaxes(0, 1)
# natija : 4 ta 2D massiv va 3 qator 2 ustunli massivlar hosil bo'lishi kerak

array([[[63, 64],
        [71, 72],
        [79, 80]],

       [[65, 66],
        [73, 74],
        [81, 82]],

       [[67, 68],
        [75, 76],
        [83, 84]],

       [[69, 70],
        [77, 78],
        [85, 86]]])

In [21]:
# 2D massivlar soni va ustunlar sonini almashtirish
arr3d3.swapaxes(0, 2)

array([[[63, 71, 79],
        [65, 73, 81],
        [67, 75, 83],
        [69, 77, 85]],

       [[64, 72, 80],
        [66, 74, 82],
        [68, 76, 84],
        [70, 78, 86]]])

In [22]:
arr1 = np.arange(11, 21)
print(arr1)

[11 12 13 14 15 16 17 18 19 20]


In [23]:
# barcha ellarning kvadrat ildizni qaytaradi
np.sqrt(arr1)

array([3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [24]:
# square - barcha ellarni kvadratga oshiradi
np.square(arr1)

array([121, 144, 169, 196, 225, 256, 289, 324, 361, 400])

In [25]:
arr_float = np.random.rand(5)
print(arr_float)

[0.71303435 0.7858013  0.84366827 0.35159768 0.49772616]


In [26]:
# modf - float sonlarni butun va qoldiqlarini ajratadi
qold, but = np.modf(arr_float)
print(f"butun qism: {but}\nqoldiq qism: {qold}")

butun qism: [0. 0. 0. 0. 0.]
qoldiq qism: [0.71303435 0.7858013  0.84366827 0.35159768 0.49772616]


In [27]:
# sign - musbat sonlar