<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/all_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr01 = np.random.randint(-10, 100, 16)
arr01

array([79, 37,  0,  5, 22, 86, -7, 78, 29, 39, 11,  5, 57, 83, 11, 65])

In [3]:
# manfiy sonlarni 0 qilish
arr01[arr01<0] = 0

In [4]:
arr01

array([79, 37,  0,  5, 22, 86,  0, 78, 29, 39, 11,  5, 57, 83, 11, 65])

In [5]:
# 10 dan katta sonlarni esa 10 qilish
arr01[arr01>10] = 10

In [6]:
arr01

array([10, 10,  0,  5, 10, 10,  0, 10, 10, 10, 10,  5, 10, 10, 10, 10])

In [7]:
arr2 = np.arange(10, 30).reshape(5, 4)
arr2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [8]:
# har bir qatordagi eng katta qiymatlarni aniqlash
max_ax = np.max(arr2, axis=1)
max_ax

array([13, 17, 21, 25, 29])

In [9]:
# har bir ustundagi o'rtacha qiymatni hisoblash
mean_col = np.mean(arr2, axis=0)
mean_col

array([18., 19., 20., 21.])

In [10]:
# 20 dan katta va juft sonlarni yangi massivga saqlash
new_arr2 = arr2[(arr2>20) & (arr2%2==0)]
new_arr2

array([22, 24, 26, 28])

#####**dtype**

In [11]:
arr3 = np.array([1, 2.5, 3, 4.0, 7])
arr3

array([1. , 2.5, 3. , 4. , 7. ])

In [12]:
# arr3 ning ma'lumot turini aniqlash
arr3.dtype

dtype('float64')

In [13]:
# arr3 ni int ma'lumotiga o'zgartirish
arr3_int = arr3.astype(np.int8)
arr3_int

array([1, 2, 3, 4, 7], dtype=int8)

In [14]:
arr3_int.dtype

dtype('int8')

In [15]:
# tasodifiy 1000 ta sonlardan iborat massiv yaratish
arr4 = np.random.random(1000)
arr4

array([7.12506898e-01, 5.46055580e-01, 6.71044343e-01, 1.50885275e-01,
       2.42501680e-01, 7.96731344e-01, 5.36576078e-02, 9.59254449e-01,
       8.97441032e-01, 8.47643687e-01, 5.89219075e-01, 3.09970466e-01,
       5.16023438e-02, 9.69171641e-01, 3.48388174e-01, 4.70054791e-01,
       1.67944440e-01, 2.70335904e-01, 9.06241731e-01, 1.36680519e-01,
       3.34095599e-01, 9.80350868e-01, 2.55045410e-01, 8.19865419e-01,
       2.00676858e-01, 9.35174027e-01, 4.07238168e-01, 1.43481303e-01,
       2.63956523e-01, 9.09184384e-01, 4.49375142e-01, 7.95549603e-01,
       3.84441747e-01, 2.05208970e-01, 1.45351722e-01, 8.03432695e-01,
       4.63792072e-01, 6.99924816e-01, 2.83314318e-02, 4.06082738e-02,
       8.92468465e-01, 6.65565775e-01, 1.72034526e-01, 3.47558394e-01,
       3.08441880e-01, 3.69395463e-01, 6.81653189e-01, 5.02321507e-01,
       3.76270213e-01, 2.71901351e-01, 9.58390867e-01, 7.40194778e-01,
       5.02523511e-01, 3.08941118e-02, 9.86268419e-01, 8.32522353e-01,
      

In [16]:
# arr4ni xotiradan egallagan joyini aniqlash
arr4.nbytes

8000

In [17]:
arr4.dtype

dtype('float64')

- `arr4` ni ma'lumot turini o'zgartirish orqali uning xotiradan oladigan joyini qisqartirish

In [18]:
arr4_new = arr4.astype(np.float16)
arr4_new

array([7.1240e-01, 5.4590e-01, 6.7090e-01, 1.5088e-01, 2.4255e-01,
       7.9688e-01, 5.3650e-02, 9.5947e-01, 8.9746e-01, 8.4766e-01,
       5.8936e-01, 3.1006e-01, 5.1605e-02, 9.6924e-01, 3.4839e-01,
       4.6997e-01, 1.6797e-01, 2.7026e-01, 9.0625e-01, 1.3672e-01,
       3.3398e-01, 9.8047e-01, 2.5513e-01, 8.1982e-01, 2.0068e-01,
       9.3506e-01, 4.0723e-01, 1.4343e-01, 2.6392e-01, 9.0918e-01,
       4.4946e-01, 7.9541e-01, 3.8452e-01, 2.0520e-01, 1.4539e-01,
       8.0322e-01, 4.6387e-01, 6.9971e-01, 2.8336e-02, 4.0619e-02,
       8.9258e-01, 6.6553e-01, 1.7200e-01, 3.4766e-01, 3.0835e-01,
       3.6938e-01, 6.8164e-01, 5.0244e-01, 3.7622e-01, 2.7197e-01,
       9.5850e-01, 7.4023e-01, 5.0244e-01, 3.0899e-02, 9.8633e-01,
       8.3252e-01, 7.1582e-01, 9.7314e-01, 6.5430e-01, 4.6582e-01,
       9.1064e-02, 3.4277e-01, 8.3105e-01, 1.4209e-01, 5.5518e-01,
       4.2041e-01, 8.6914e-01, 6.7969e-01, 3.3765e-01, 5.4834e-01,
       5.6801e-03, 2.6245e-01, 7.5977e-01, 8.8574e-01, 4.7192e

In [19]:
arr4_new.nbytes

2000

#####**indexing and slicing**

In [20]:
arr5 = np.arange(0, 30)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
# 5-elementdan 20-elementgacha bo'lgan sonlarni olish
arr5[5:20]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
# har 2-elementlarni olish
arr5[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [23]:
# massiv ohiridan 8 ta elementni teskari tartibda olish
arr5[-1:-9:-1]

array([29, 28, 27, 26, 25, 24, 23, 22])

In [24]:
arr6 = np.arange(55, 91).reshape(6, 6)
arr6

array([[55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66],
       [67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89, 90]])

In [25]:
# massivdan markazdagi 4x4 qiymatlarni olish
arr6[1:-1, 1:-1]

array([[62, 63, 64, 65],
       [68, 69, 70, 71],
       [74, 75, 76, 77],
       [80, 81, 82, 83]])

#####**bolean indexing**

In [26]:
arr7 = np.random.randint(-20, 20, 21)
arr7

array([-12,   9,  -2,  18,   4,   8,  -5, -12,  11,  -8,  -1, -14,  -1,
       -20,   7,  -4,  14,  -8,  10,  14, -10])

In [27]:
# manfiy qiymatlarni ajratish
arr7_neg = arr7[arr7<0]
arr7_neg

array([-12,  -2,  -5, -12,  -8,  -1, -14,  -1, -20,  -4,  -8, -10])

In [28]:
# elementlar sonini aniqlash
arr7_neg.size

12

In [29]:
# 5 dan katta va 15 dan kichik qiymatlar
arr7[(arr7>5) & (arr7<15)]

array([ 9,  8, 11,  7, 14, 10, 14])

In [30]:
# 3 ga karrali bo'lmagan sonlar
arr7[arr7%3!=0]

array([ -2,   4,   8,  -5,  11,  -8,  -1, -14,  -1, -20,   7,  -4,  14,
        -8,  10,  14, -10])

In [31]:
arr8 = np.random.randint(-100, 100, 25).reshape(5,5)
arr8

array([[ 62,  -4,  -2,  44, -79],
       [  9, -74, -89,  12, -91],
       [ 59,  76, -48, -11,  89],
       [ 62, -67,  73,  51, -75],
       [-27,   3,  51, -33,  -6]])

In [32]:
# faqatgina musbat elementlarni olish
arr8[arr8>0]

array([62, 44,  9, 12, 59, 76, 89, 62, 73, 51,  3, 51])

In [33]:
# dioganaldagi qiymatlarni 0 dan kattasini olish
arr8_diag = np.diag(arr8)
arr8_diag[arr8_diag>0]

array([62, 51])

In [34]:
arr8

array([[ 62,  -4,  -2,  44, -79],
       [  9, -74, -89,  12, -91],
       [ 59,  76, -48, -11,  89],
       [ 62, -67,  73,  51, -75],
       [-27,   3,  51, -33,  -6]])

In [35]:
# 10 dan katta barcha qiymatlarni -1 ga almashtirish
arr8[arr8>10] = -1

In [36]:
arr8

array([[ -1,  -4,  -2,  -1, -79],
       [  9, -74, -89,  -1, -91],
       [ -1,  -1, -48, -11,  -1],
       [ -1, -67,  -1,  -1, -75],
       [-27,   3,  -1, -33,  -6]])

In [37]:
arr9 = np.arange(1, 16).reshape(3, 5)
arr9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [38]:
# massiv qatorlarini ustunlarga aylantirish
arr9_t = arr9.T
arr9_t

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [39]:
arr9_t.shape

(5, 3)

In [40]:
arr10 = np.random.rand(2, 3, 4)
arr10

array([[[2.87182248e-01, 8.96988557e-01, 4.79800463e-01, 3.89065555e-01],
        [3.38625010e-01, 4.53419183e-04, 6.88283852e-01, 7.92892324e-01],
        [4.70706973e-01, 4.49281496e-01, 9.98083802e-01, 1.62697034e-01]],

       [[5.80876983e-01, 5.31077222e-01, 9.72536561e-01, 7.26278937e-01],
        [1.65879338e-01, 9.79319849e-01, 9.52895712e-01, 8.57487088e-01],
        [9.78356644e-01, 5.06315192e-01, 6.23599646e-01, 9.20950338e-01]]])

In [41]:
# arr10 3D massivni : 2D dan 4 ta, 3 qator va 2 ustunli qilish
arr10_swap = np.swapaxes(arr10, 0, 2)
arr10_swap

array([[[2.87182248e-01, 5.80876983e-01],
        [3.38625010e-01, 1.65879338e-01],
        [4.70706973e-01, 9.78356644e-01]],

       [[8.96988557e-01, 5.31077222e-01],
        [4.53419183e-04, 9.79319849e-01],
        [4.49281496e-01, 5.06315192e-01]],

       [[4.79800463e-01, 9.72536561e-01],
        [6.88283852e-01, 9.52895712e-01],
        [9.98083802e-01, 6.23599646e-01]],

       [[3.89065555e-01, 7.26278937e-01],
        [7.92892324e-01, 8.57487088e-01],
        [1.62697034e-01, 9.20950338e-01]]])

In [42]:
print("massiv:", arr10.shape)
print("swap_massiv:", arr10_swap.shape)

massiv: (2, 3, 4)
swap_massiv: (4, 3, 2)


In [43]:
arr11 = np.random.uniform(-100, 100, 11)
arr11

array([ 93.26512426,  25.69411684,  70.54826759,  30.28528049,
       -28.00444238,  24.92799169,  78.84421635, -78.94340014,
        98.69215705,   1.42050928, -85.635787  ])

In [44]:
# har bir elementni musbat yoki manfiyligini aniqlash
np.sign(arr11)

array([ 1.,  1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1., -1.])

In [45]:
# massivning manfiy qiymatlarini musbat qilish
arr11_new = np.abs(arr11)
arr11_new

array([93.26512426, 25.69411684, 70.54826759, 30.28528049, 28.00444238,
       24.92799169, 78.84421635, 78.94340014, 98.69215705,  1.42050928,
       85.635787  ])

In [46]:
print("minimum qiymat:", np.min(arr11_new))
print("maksimum qiymat:", np.max(arr11_new))

minimum qiymat: 1.4205092827692027
maksimum qiymat: 98.69215705032397


In [47]:
# max va min qiymatlari farqi
np.max(arr11_new) - np.min(arr11_new)

np.float64(97.27164776755477)

In [48]:
arr12_1 = np.random.randint(40, 120, 16).reshape(4, 4)
arr12_1

array([[ 48,  69,  63,  50],
       [ 93,  71, 110,  84],
       [ 52,  96,  76,  55],
       [114, 107,  82, 117]])

In [49]:
arr12_2 = np.random.randint(6, 50, 16).reshape(4, 4)
arr12_2

array([[25,  6, 49, 12],
       [44, 12, 16, 32],
       [28, 27,  7,  9],
       [43, 38, 47, 45]])

In [50]:
# ikkala massivning mos elementlarini solishtirib , ulardan kattasini olish
np.maximum(arr12_1, arr12_2)

array([[ 48,  69,  63,  50],
       [ 93,  71, 110,  84],
       [ 52,  96,  76,  55],
       [114, 107,  82, 117]])

#####**where**

In [51]:
arr13 = np.random.randint(-100, 100, 21)
arr13

array([ 80,  -9,  74, -74, -56,  83,  81,  37,  71, -79,  34,  17,  77,
        79, -30, -40, -97, -53, -64,  39,   7])

In [52]:
# agarda qiymat 0 dan kichik bo'lsa 0 ga o'zgartirish
np.where(arr13<0, 0, arr13)

array([80,  0, 74,  0,  0, 83, 81, 37, 71,  0, 34, 17, 77, 79,  0,  0,  0,
        0,  0, 39,  7])

In [53]:
# 10 dan katta qiymatlarni -1 ga o'zgartirish
np.where(arr13>10, -1, arr13)

array([ -1,  -9,  -1, -74, -56,  -1,  -1,  -1,  -1, -79,  -1,  -1,  -1,
        -1, -30, -40, -97, -53, -64,  -1,   7])

In [54]:
arr14 = np.random.uniform(-40, 40, 30).reshape(6, 5)
arr14

array([[ 29.62528249, -28.75183255, -13.34157364, -13.54967012,
         19.50581755],
       [ 32.14053701,  -1.91520523, -19.16877209, -31.69694282,
        -12.19995037],
       [ 12.25486043, -18.38501542,  -1.85638769,   1.29921897,
        -23.39281284],
       [ 36.09892549, -12.12844247,   7.85779149,   7.88234779,
         22.34314153],
       [  7.49782424, -29.2186002 ,  15.79374782,  26.27632018,
        -22.71978378],
       [ 26.98265639, -21.67465034,  39.24939483,   1.11930161,
         37.41893198]])

In [55]:
# faqatgina musbat elementlardan tashkil topgan yangi massiv hosil qilish
arr14_new = arr14[np.where(arr14>0)]
arr14_new

array([29.62528249, 19.50581755, 32.14053701, 12.25486043,  1.29921897,
       36.09892549,  7.85779149,  7.88234779, 22.34314153,  7.49782424,
       15.79374782, 26.27632018, 26.98265639, 39.24939483,  1.11930161,
       37.41893198])

In [56]:
# manfiy elementlar indekslarini aniqlash
np.where(arr14<0)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 4, 4, 5]),
 array([1, 2, 3, 1, 2, 3, 4, 1, 2, 4, 1, 1, 4, 1]))

In [57]:
# musbat qiymatlarni kvadratini , manfiy qiymatlarni o'zini hisoblash
np.where(arr14>0, arr14**2, arr14)

array([[ 8.77657363e+02, -2.87518326e+01, -1.33415736e+01,
        -1.35496701e+01,  3.80476918e+02],
       [ 1.03301412e+03, -1.91520523e+00, -1.91687721e+01,
        -3.16969428e+01, -1.21999504e+01],
       [ 1.50181604e+02, -1.83850154e+01, -1.85638769e+00,
         1.68796994e+00, -2.33928128e+01],
       [ 1.30313242e+03, -1.21284425e+01,  6.17448871e+01,
         6.21314066e+01,  4.99215973e+02],
       [ 5.62173684e+01, -2.92186002e+01,  2.49442470e+02,
         6.90445002e+02, -2.27197838e+01],
       [ 7.28063746e+02, -2.16746503e+01,  1.54051499e+03,
         1.25283609e+00,  1.40017647e+03]])

#####**arithmetic operations**

In [58]:
arr15_1 = np.random.randint(-100, 100, 11)
arr15_2 = np.random.randint(-50, 50, 11)
arr15_1

array([-53,  57,  81, -50, -61,  42,  43,  34,  10,  -7,  50])

In [59]:
arr15_2

array([-16, -18,  36, -44,  11,   4,   4, -21,  31,  28,  45])

In [60]:
# mos elementlarini qo'shish
arr15_1+arr15_2

array([-69,  39, 117, -94, -50,  46,  47,  13,  41,  21,  95])

In [61]:
# mos elementlarni ayirish
arr15_1-arr15_2

array([-37,  75,  45,  -6, -72,  38,  39,  55, -21, -35,   5])

In [62]:
# mos elementlarni ko'paytirish
arr15_1*arr15_2

array([  848, -1026,  2916,  2200,  -671,   168,   172,  -714,   310,
        -196,  2250])

In [63]:
# mos elementlarini bo'lish
arr15_1/arr15_2

array([ 3.3125    , -3.16666667,  2.25      ,  1.13636364, -5.54545455,
       10.5       , 10.75      , -1.61904762,  0.32258065, -0.25      ,
        1.11111111])

In [64]:
arr16 = np.random.randint(-100, 100, 24).reshape(4, 6)
arr16

array([[ 68,  58,  79, -83,  12,  -9],
       [ 40, -50,  88, -98, -90,  51],
       [-34, -88,  51, -61, -70,  78],
       [ 66,   3,  51,  39,  76,  46]])

In [65]:
# har bir qatorni yig'indisini aniqlash
np.sum(arr16, axis=1)

array([ 125,  -59, -124,  281])

In [66]:
# har bir ustundagi elementlar ko'paytmasini aniqlash
np.prod(arr16, axis=0)

array([ -6103680,    765600,  18082152, -19350786,   5745600,  -1646892])

In [67]:
# massivning o'rtacha qiymatini aniqlash
np.mean(arr16)

np.float64(9.291666666666666)

- *har bir qatordan , shu qatorni o'rtacha qiymatini ayirish*

In [68]:
arr16_mean = np.mean(arr16, axis=1, keepdims=True)
arr16_mean

array([[ 20.83333333],
       [ -9.83333333],
       [-20.66666667],
       [ 46.83333333]])

In [69]:
arr16-arr16_mean

array([[  47.16666667,   37.16666667,   58.16666667, -103.83333333,
          -8.83333333,  -29.83333333],
       [  49.83333333,  -40.16666667,   97.83333333,  -88.16666667,
         -80.16666667,   60.83333333],
       [ -13.33333333,  -67.33333333,   71.66666667,  -40.33333333,
         -49.33333333,   98.66666667],
       [  19.16666667,  -43.83333333,    4.16666667,   -7.83333333,
          29.16666667,   -0.83333333]])

#####**sorting**

- massivlar AI yordamida yaratiladi

In [70]:
arr17 = np.array([12, -3, 45, 7, 0, 19, -8, 23, 5, 42, 16, -1, 9, 30, 4])
arr17

array([12, -3, 45,  7,  0, 19, -8, 23,  5, 42, 16, -1,  9, 30,  4])

In [71]:
# massivni o'sish tartibida saralash
np.sort(arr17)

array([-8, -3, -1,  0,  4,  5,  7,  9, 12, 16, 19, 23, 30, 42, 45])

In [72]:
# kamayish tartibida saralash
-np.sort(-arr17)

array([45, 42, 30, 23, 19, 16, 12,  9,  7,  5,  4,  0, -1, -3, -8])

In [73]:
# eng kichik 5 ta elementni olish
-np.sort(-arr17)[-5:]

array([ 4,  0, -1, -3, -8])

- *eng katta 3 ta elementni indeksini olish*

In [74]:
arr17_idx = np.argsort(arr17)
arr17_idx[-3:]

array([13,  9,  2])

In [75]:
arr18 = np.array([[12,  5,  9,  1],[20, -3,  7, 14],[ 6, 18,  2, 11],[25,  4, -6, 10],[ 8, 16,  3, 19]])
arr18

array([[12,  5,  9,  1],
       [20, -3,  7, 14],
       [ 6, 18,  2, 11],
       [25,  4, -6, 10],
       [ 8, 16,  3, 19]])

In [76]:
# har bir qatordagi elementlarni tartiblash
np.sort(arr18, axis=1)

array([[ 1,  5,  9, 12],
       [-3,  7, 14, 20],
       [ 2,  6, 11, 18],
       [-6,  4, 10, 25],
       [ 3,  8, 16, 19]])

In [77]:
# ustunlar bo'yicha tartiblash
np.sort(arr18, axis=0)

array([[ 6, -3, -6,  1],
       [ 8,  4,  2, 10],
       [12,  5,  3, 11],
       [20, 16,  7, 14],
       [25, 18,  9, 19]])

In [78]:
arr_18_rows = np.sum(arr18, axis=1)
arr_18_rows

array([27, 38, 37, 33, 46])

In [79]:
# qatorlar yig'indilarini tartiblash
arr_18_rows.sort()

In [80]:
arr_18_rows

array([27, 33, 37, 38, 46])

#####**non-repeatable and other actions**

In [81]:
arr19 = np.array([4, 7, 2, 7, 4, 9, 2, 5, 7, 9, 1, 4])
arr19

array([4, 7, 2, 7, 4, 9, 2, 5, 7, 9, 1, 4])

In [84]:
# tarorlanmas qiymatlarni olish
np.unique(arr19)

array([1, 2, 4, 5, 7, 9])

In [86]:
val, couns = np.unique(arr19, return_counts=True)
val

array([1, 2, 4, 5, 7, 9])

In [88]:
# qiymatlar necha marta takrorlanganini aniqledi
couns

array([1, 2, 3, 1, 3, 2])

In [89]:
arr_main = np.array([10, 15, 20, 25, 30, 35, 40])
arr_check = np.array([15, 22, 30, 41])

In [92]:
# arr_maindagi elementni qaysi birir arr_checkda mavjudligini aniqlash
np.isin(arr_main, arr_check)

array([False,  True, False, False,  True, False, False])

In [93]:
arr_A = np.array([1, 2, 3, 4, 5, 6, 7])
arr_B = np.array([2, 4, 6, 8])

In [95]:
# ikkinchi massivda bo'lmagan arr_A ning qiymatlarini olish
np.setdiff1d(arr_A, arr_B)

array([1, 3, 5, 7])

In [96]:
np.isin(arr_A, arr_B)

array([False,  True, False,  True, False,  True, False])

In [97]:
arr_count = np.array([0, 1, 1, 2, 3, 2, 1, 0, 4, 2, 3, 3, 1])
arr_count

array([0, 1, 1, 2, 3, 2, 1, 0, 4, 2, 3, 3, 1])

In [98]:
# har bir element necha marta takrorlangan
val2, couns2 = np.unique(arr_count, return_counts=True)
couns2

array([2, 4, 3, 3, 1])

In [99]:
for val, count in zip(val2, couns2):
    print(f"{val} -> {count} marta")

0 -> 2 marta
1 -> 4 marta
2 -> 3 marta
3 -> 3 marta
4 -> 1 marta


#####**save and read to file**

- faylga saqlash

In [100]:
np.save('arr01', arr01)

In [101]:
# arr01ni o'qish
np.load('arr01.npy')

array([10, 10,  0,  5, 10, 10,  0, 10, 10, 10, 10,  5, 10, 10, 10, 10])

In [102]:
# bir nechta massivlarni saqlash
np.savez('arrs_02_03', a=arr2, b=arr3)

In [104]:
arrs_02_03 = np.load('arrs_02_03.npz')

In [105]:
arrs_02_03['a']

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [106]:
arrs_02_03['b']

array([1. , 2.5, 3. , 4. , 7. ])

#####**shuffling array elements**

In [107]:
arr20 = np.array([5, 10, 15, 20, 25, 30, 35])
arr20

array([ 5, 10, 15, 20, 25, 30, 35])

- `arr20` ning qiymatlarini tasodifiy aralashtirish , bunda asl massiv saqlanib qolishi kerak

In [108]:
arr20_per = np.random.permutation(arr20)
arr20_per

array([35, 15, 30, 10,  5, 25, 20])

In [109]:
X = np.array([100, 200, 300, 400, 500])
y = np.array([1, 0, 1, 0, 1])
X

array([100, 200, 300, 400, 500])

In [110]:
y

array([1, 0, 1, 0, 1])

- `X` va `y` ning elementlarini aralashtirish

In [111]:
x_per = np.random.permutation(len(X))

In [112]:
X[x_per]

array([200, 500, 300, 400, 100])

In [113]:
y[x_per]

array([0, 1, 1, 0, 1])