<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/all_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr01 = np.random.randint(-10, 100, 16)
arr01

array([58, 93,  2, 64,  8, 87, 37, 31, 93, -6, -3, 72, 53, 23, 56, 86])

In [ ]:
# manfiy sonlarni 0 qilish
arr01[arr01<0] = 0

In [ ]:
arr01

array([58, 93,  2, 64,  8, 87, 37, 31, 93,  0,  0, 72, 53, 23, 56, 86])

In [ ]:
# 10 dan katta sonlarni esa 10 qilish
arr01[arr01>10] = 10

In [ ]:
arr01

array([10, 10,  2, 10,  8, 10, 10, 10, 10,  0,  0, 10, 10, 10, 10, 10])

In [ ]:
arr2 = np.arange(10, 30).reshape(5, 4)
arr2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [ ]:
# har bir qatordagi eng katta qiymatlarni aniqlash
max_ax = np.max(arr2, axis=1)
max_ax

array([13, 17, 21, 25, 29])

In [ ]:
# har bir ustundagi o'rtacha qiymatni hisoblash
mean_col = np.mean(arr2, axis=0)
mean_col

array([18., 19., 20., 21.])

In [ ]:
# 20 dan katta va juft sonlarni yangi massivga saqlash
new_arr2 = arr2[(arr2>20) & (arr2%2==0)]
new_arr2

array([22, 24, 26, 28])

#####**dtype**

In [ ]:
arr3 = np.array([1, 2.5, 3, 4.0, 7])
arr3

array([1. , 2.5, 3. , 4. , 7. ])

In [ ]:
# arr3 ning ma'lumot turini aniqlash
arr3.dtype

dtype('float64')

In [ ]:
# arr3 ni int ma'lumotiga o'zgartirish
arr3_int = arr3.astype(np.int8)
arr3_int

array([1, 2, 3, 4, 7], dtype=int8)

In [ ]:
arr3_int.dtype

dtype('int8')

In [ ]:
# tasodifiy 1000 ta sonlardan iborat massiv yaratish
arr4 = np.random.random(1000)
arr4

array([0.16939306, 0.5088394 , 0.63538768, 0.12668351, 0.05266953,
       0.68901001, 0.83708926, 0.12493596, 0.96715546, 0.62163438,
       0.62639106, 0.76379142, 0.18764529, 0.14722296, 0.13478555,
       0.70203359, 0.87236457, 0.23968313, 0.74297321, 0.44518057,
       0.19879996, 0.42687953, 0.217912  , 0.3722339 , 0.93524486,
       0.95036711, 0.00331863, 0.02043547, 0.81204488, 0.33215046,
       0.97894051, 0.59482956, 0.34218269, 0.18752685, 0.64559155,
       0.38263428, 0.5229327 , 0.98625182, 0.39034603, 0.385777  ,
       0.55881533, 0.74890475, 0.71083531, 0.29230587, 0.6000146 ,
       0.63343284, 0.48838192, 0.58629541, 0.34459338, 0.29760494,
       0.51758871, 0.79518527, 0.56773319, 0.19538904, 0.40039098,
       0.96058243, 0.55822657, 0.76201747, 0.72735654, 0.65867011,
       0.22075728, 0.02494573, 0.68994209, 0.26734546, 0.33473051,
       0.23774036, 0.03748926, 0.10575244, 0.88832011, 0.88000891,
       0.53858478, 0.02468643, 0.91990651, 0.9075244 , 0.42017

In [ ]:
# arr4ni xotiradan egallagan joyini aniqlash
arr4.nbytes

8000

In [ ]:
arr4.dtype

dtype('float64')

- `arr4` ni ma'lumot turini o'zgartirish orqali uning xotiradan oladigan joyini qisqartirish

In [ ]:
arr4_new = arr4.astype(np.float16)
arr4_new

array([0.1694  , 0.509   , 0.6353  , 0.1267  , 0.05267 , 0.689   ,
       0.837   , 0.12494 , 0.9673  , 0.6216  , 0.6265  , 0.7637  ,
       0.1876  , 0.1472  , 0.1348  , 0.702   , 0.8726  , 0.2396  ,
       0.743   , 0.445   , 0.1989  , 0.4268  , 0.2179  , 0.3723  ,
       0.935   , 0.95    , 0.003319, 0.02043 , 0.812   , 0.332   ,
       0.979   , 0.5947  , 0.3423  , 0.1875  , 0.6455  , 0.3826  ,
       0.523   , 0.9863  , 0.3904  , 0.3857  , 0.5586  , 0.749   ,
       0.711   , 0.2922  , 0.6     , 0.6333  , 0.4883  , 0.5864  ,
       0.3445  , 0.2976  , 0.5176  , 0.7954  , 0.568   , 0.1954  ,
       0.4004  , 0.9604  , 0.558   , 0.762   , 0.7275  , 0.6587  ,
       0.2207  , 0.02495 , 0.69    , 0.2673  , 0.3347  , 0.2378  ,
       0.03748 , 0.1058  , 0.888   , 0.88    , 0.5386  , 0.02469 ,
       0.92    , 0.9077  , 0.4202  , 0.86    , 0.452   , 0.627   ,
       0.637   , 0.659   , 0.6606  , 0.1554  , 0.3425  , 0.7915  ,
       0.608   , 0.1847  , 0.81    , 0.8506  , 0.708   , 0.433

In [ ]:
arr4_new.nbytes

2000

#####**indexing and slicing**

In [ ]:
arr5 = np.arange(0, 30)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
# 5-elementdan 20-elementgacha bo'lgan sonlarni olish
arr5[5:20]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# har 2-elementlarni olish
arr5[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
# massiv ohiridan 8 ta elementni teskari tartibda olish
arr5[-1:-9:-1]

array([29, 28, 27, 26, 25, 24, 23, 22])

In [ ]:
arr6 = np.arange(55, 91).reshape(6, 6)
arr6

array([[55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66],
       [67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89, 90]])

In [ ]:
# massivdan markazdagi 4x4 qiymatlarni olish
arr6[1:-1, 1:-1]

array([[62, 63, 64, 65],
       [68, 69, 70, 71],
       [74, 75, 76, 77],
       [80, 81, 82, 83]])

#####**bolean indexing**

In [ ]:
arr7 = np.random.randint(-20, 20, 21)
arr7

array([ 17,   4,   1, -18,  -1,  16,  17,  18, -17,   1, -11, -12,  -9,
       -19,  19,  17,  14,  -4,  -2,  -8,  -3])

In [ ]:
# manfiy qiymatlarni ajratish
arr7_neg = arr7[arr7<0]
arr7_neg

array([-18,  -1, -17, -11, -12,  -9, -19,  -4,  -2,  -8,  -3])

In [ ]:
# elementlar sonini aniqlash
arr7_neg.size

11

In [ ]:
# 5 dan katta va 15 dan kichik qiymatlar
arr7[(arr7>5) & (arr7<15)]

array([14])

In [ ]:
# 3 ga karrali bo'lmagan sonlar
arr7[arr7%3!=0]

array([ 17,   4,   1,  -1,  16,  17, -17,   1, -11, -19,  19,  17,  14,
        -4,  -2,  -8])

In [ ]:
arr8 = np.random.randint(-100, 100, 25).reshape(5,5)
arr8

array([[  53,   83,  -93,  -34,  -51],
       [  81,    9,   60,   20,   58],
       [   5,   73,   39,    1,   97],
       [ -80, -100,  -53,   90,  -73],
       [   9,    0,   90,  -41,    1]])

In [ ]:
# faqatgina musbat elementlarni olish
arr8[arr8>0]

array([53, 83, 81,  9, 60, 20, 58,  5, 73, 39,  1, 97, 90,  9, 90,  1])

In [ ]:
# dioganaldagi qiymatlarni 0 dan kattasini olish
arr8_diag = np.diag(arr8)
arr8_diag[arr8_diag>0]

array([53,  9, 39, 90,  1])

In [ ]:
arr8

array([[  53,   83,  -93,  -34,  -51],
       [  81,    9,   60,   20,   58],
       [   5,   73,   39,    1,   97],
       [ -80, -100,  -53,   90,  -73],
       [   9,    0,   90,  -41,    1]])

In [ ]:
# 10 dan katta barcha qiymatlarni -1 ga almashtirish
arr8[arr8>10] = -1

In [ ]:
arr8

array([[  -1,   -1,  -93,  -34,  -51],
       [  -1,    9,   -1,   -1,   -1],
       [   5,   -1,   -1,    1,   -1],
       [ -80, -100,  -53,   -1,  -73],
       [   9,    0,   -1,  -41,    1]])

In [ ]:
arr9 = np.arange(1, 16).reshape(3, 5)
arr9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# massiv qatorlarini ustunlarga aylantirish
arr9_t = arr9.T
arr9_t

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [ ]:
arr9_t.shape

(5, 3)

In [ ]:
arr10 = np.random.rand(2, 3, 4)
arr10

array([[[0.18587216, 0.49334551, 0.647132  , 0.53310052],
        [0.01107016, 0.7212588 , 0.96058968, 0.48897895],
        [0.50208043, 0.32207972, 0.48131899, 0.96588191]],

       [[0.67880364, 0.97443908, 0.50993568, 0.95823437],
        [0.7249637 , 0.62359748, 0.30659777, 0.99061273],
        [0.11243663, 0.23479415, 0.1108844 , 0.28480223]]])

In [ ]:
# arr10 3D massivni : 2D dan 4 ta, 3 qator va 2 ustunli qilish
arr10_swap = np.swapaxes(arr10, 0, 2)
arr10_swap

array([[[0.18587216, 0.67880364],
        [0.01107016, 0.7249637 ],
        [0.50208043, 0.11243663]],

       [[0.49334551, 0.97443908],
        [0.7212588 , 0.62359748],
        [0.32207972, 0.23479415]],

       [[0.647132  , 0.50993568],
        [0.96058968, 0.30659777],
        [0.48131899, 0.1108844 ]],

       [[0.53310052, 0.95823437],
        [0.48897895, 0.99061273],
        [0.96588191, 0.28480223]]])

In [ ]:
print("massiv:", arr10.shape)
print("swap_massiv:", arr10_swap.shape)

massiv: (2, 3, 4)
swap_massiv: (4, 3, 2)


In [ ]:
arr11 = np.random.uniform(-100, 100, 11)
arr11

array([-26.28498803, -41.9037338 , -34.38555282,  85.50553956,
       -35.52935559, -62.84563452, -53.59328697,  37.03060513,
        66.82872913,   7.14573794,  19.09198212])

In [ ]:
# har bir elementni musbat yoki manfiyligini aniqlash
np.sign(arr11)

array([-1., -1., -1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.])

In [ ]:
# massivning manfiy qiymatlarini musbat qilish
arr11_new = np.abs(arr11)
arr11_new

array([26.28498803, 41.9037338 , 34.38555282, 85.50553956, 35.52935559,
       62.84563452, 53.59328697, 37.03060513, 66.82872913,  7.14573794,
       19.09198212])

In [ ]:
print("minimum qiymat:", np.min(arr11_new))
print("maksimum qiymat:", np.max(arr11_new))

minimum qiymat: 7.145737936214914
maksimum qiymat: 85.50553956066332


In [ ]:
# max va min qiymatlari farqi
np.max(arr11_new) - np.min(arr11_new)

np.float64(78.35980162444841)

In [77]:
arr12_1 = np.random.randint(40, 120, 16).reshape(4, 4)
arr12_1

array([[103,  84,  73, 109],
       [118,  77,  77,  91],
       [ 65,  47,  47,  81],
       [ 70, 106,  47,  43]])

In [ ]:
arr12_2 = np.random.randint(6, 50, 16).reshape(4, 4)
arr12_2

array([[16, 23, 13, 31],
       [22, 19, 31,  7],
       [20, 40, 25, 43],
       [40, 37, 45, 37]])

In [79]:
# ikkala massivning mos elementlarini solishtirib , ulardan kattasini olish
np.maximum(arr12_1, arr12_2)

array([[103,  84,  73, 109],
       [118,  77,  77,  91],
       [ 65,  47,  47,  81],
       [ 70, 106,  47,  43]])

#####**where**

In [80]:
arr13 = np.random.randint(-100, 100, 21)
arr13

array([ 61,  98,  62, -86,  83,  79, -13,  30,  13, -29,  36,  -7, -59,
       -19, -80,  93,  21, -73, -60, -90,  78])

In [81]:
# agarda qiymat 0 dan kichik bo'lsa 0 ga o'zgartirish
np.where(arr13<0, 0, arr13)

array([61, 98, 62,  0, 83, 79,  0, 30, 13,  0, 36,  0,  0,  0,  0, 93, 21,
        0,  0,  0, 78])

In [82]:
# 10 dan katta qiymatlarni -1 ga o'zgartirish
np.where(arr13>10, -1, arr13)

array([ -1,  -1,  -1, -86,  -1,  -1, -13,  -1,  -1, -29,  -1,  -7, -59,
       -19, -80,  -1,  -1, -73, -60, -90,  -1])

In [83]:
arr14 = np.random.uniform(-40, 40, 30).reshape(6, 5)
arr14

array([[-35.63457737,   2.47681623,  27.53863417, -10.36436027,
         -2.40784628],
       [ 19.28986922,  25.44387663,  23.93024315,  25.64578689,
        -39.03473155],
       [ 21.36159061,  19.19417404,  26.99592693,  24.48729537,
        -20.90996251],
       [ 31.96617446,  -5.36703296, -32.11799243, -37.2344318 ,
        -19.00126462],
       [ 38.47963108,  -2.76977364,  27.49240706,  13.47510159,
        -22.94863273],
       [ 26.76816245,  35.34630523, -33.74760683, -13.88174663,
         38.27606634]])

In [88]:
np.where(arr14>0)

(array([0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 4, 4, 4, 5, 5, 5]),
 array([1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 0, 0, 2, 3, 0, 1, 4]))