<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/all_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np

In [43]:
arr01 = np.random.randint(-10, 100, 16)
arr01

array([ 70,  42, -10, -10,  83,  13,  12,  44,  23,  46,  -1,  60,  -7,
        74,  79,  28])

In [44]:
# manfiy sonlarni 0 qilish
arr01[arr01<0] = 0

In [45]:
arr01

array([70, 42,  0,  0, 83, 13, 12, 44, 23, 46,  0, 60,  0, 74, 79, 28])

In [46]:
# 10 dan katta sonlarni esa 10 qilish
arr01[arr01>10] = 10

In [47]:
arr01

array([10, 10,  0,  0, 10, 10, 10, 10, 10, 10,  0, 10,  0, 10, 10, 10])

In [48]:
arr2 = np.arange(10, 30).reshape(5, 4)
arr2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [49]:
# har bir qatordagi eng katta qiymatlarni aniqlash
max_ax = np.max(arr2, axis=1)
max_ax

array([13, 17, 21, 25, 29])

In [50]:
# har bir ustundagi o'rtacha qiymatni hisoblash
mean_col = np.mean(arr2, axis=0)
mean_col

array([18., 19., 20., 21.])

In [51]:
# 20 dan katta va juft sonlarni yangi massivga saqlash
new_arr2 = arr2[(arr2>20) & (arr2%2==0)]
new_arr2

array([22, 24, 26, 28])

#####**dtype**

In [52]:
arr3 = np.array([1, 2.5, 3, 4.0, 7])
arr3

array([1. , 2.5, 3. , 4. , 7. ])

In [53]:
# arr3 ning ma'lumot turini aniqlash
arr3.dtype

dtype('float64')

In [54]:
# arr3 ni int ma'lumotiga o'zgartirish
arr3_int = arr3.astype(np.int8)
arr3_int

array([1, 2, 3, 4, 7], dtype=int8)

In [55]:
arr3_int.dtype

dtype('int8')

In [56]:
# tasodifiy 1000 ta sonlardan iborat massiv yaratish
arr4 = np.random.random(1000)
arr4

array([7.94964932e-01, 4.51213168e-01, 3.87876532e-06, 8.08587374e-01,
       3.80236666e-01, 8.90596008e-01, 8.91395212e-01, 4.14744263e-01,
       8.64147345e-01, 2.71890369e-01, 1.22071060e-01, 3.03470700e-01,
       6.55992139e-01, 5.13989967e-01, 1.53936692e-01, 3.36877719e-01,
       5.70304840e-01, 6.69023430e-01, 2.22710489e-01, 5.41909436e-01,
       2.39040213e-01, 7.37113004e-01, 6.27131280e-01, 1.76110000e-01,
       8.54306808e-01, 8.27958823e-01, 5.36967712e-01, 7.02200849e-01,
       8.55734381e-01, 5.14766285e-01, 1.52355338e-01, 9.59362411e-01,
       4.76484981e-01, 8.04386464e-01, 7.06071828e-01, 8.93650002e-01,
       5.34251909e-01, 9.22876940e-01, 7.67030080e-01, 2.93281103e-01,
       7.24909603e-01, 3.66209485e-01, 5.12929015e-01, 9.06291858e-01,
       3.42808685e-01, 2.48771423e-01, 5.38933768e-01, 8.64789878e-01,
       9.92301375e-01, 7.07730711e-01, 6.68242048e-01, 4.72692084e-01,
       9.84879164e-01, 7.42809261e-01, 5.42476972e-01, 8.31016355e-01,
      

In [57]:
# arr4ni xotiradan egallagan joyini aniqlash
arr4.nbytes

8000

In [58]:
arr4.dtype

dtype('float64')

- `arr4` ni ma'lumot turini o'zgartirish orqali uning xotiradan oladigan joyini qisqartirish

In [60]:
arr4_new = arr4.astype(np.float16)
arr4_new

array([7.9492e-01, 4.5117e-01, 3.8743e-06, 8.0859e-01, 3.8013e-01,
       8.9062e-01, 8.9160e-01, 4.1479e-01, 8.6426e-01, 2.7197e-01,
       1.2207e-01, 3.0347e-01, 6.5576e-01, 5.1416e-01, 1.5393e-01,
       3.3691e-01, 5.7031e-01, 6.6895e-01, 2.2266e-01, 5.4199e-01,
       2.3901e-01, 7.3730e-01, 6.2695e-01, 1.7615e-01, 8.5449e-01,
       8.2812e-01, 5.3711e-01, 7.0215e-01, 8.5596e-01, 5.1465e-01,
       1.5234e-01, 9.5947e-01, 4.7656e-01, 8.0420e-01, 7.0605e-01,
       8.9355e-01, 5.3418e-01, 9.2285e-01, 7.6709e-01, 2.9321e-01,
       7.2510e-01, 3.6621e-01, 5.1270e-01, 9.0625e-01, 3.4277e-01,
       2.4878e-01, 5.3906e-01, 8.6475e-01, 9.9219e-01, 7.0752e-01,
       6.6846e-01, 4.7266e-01, 9.8486e-01, 7.4268e-01, 5.4248e-01,
       8.3105e-01, 6.7285e-01, 3.6694e-01, 3.9111e-01, 6.6260e-01,
       4.5020e-01, 8.4619e-01, 8.2275e-02, 9.5398e-02, 5.0244e-01,
       2.3499e-02, 8.6719e-01, 9.5557e-01, 4.1992e-01, 4.1187e-01,
       4.2908e-02, 1.7114e-01, 6.3623e-01, 1.6394e-01, 3.7479e

In [61]:
arr4_new.nbytes

2000

#####**indexing and slicing**

In [62]:
arr5 = np.arange(0, 30)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [64]:
# 5-elementdan 20-elementgacha bo'lgan sonlarni olish
arr5[5:20]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [66]:
# har 2-elementlarni olish
arr5[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [69]:
arr5[-9:-1]

array([21, 22, 23, 24, 25, 26, 27, 28])