<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/all_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr01 = np.random.randint(-10, 100, 16)
arr01

array([42,  9,  2, 75, 69, 19, 40, 72,  3, 26, -4, 10, 25, 16, 28, 62])

In [3]:
# manfiy sonlarni 0 qilish
arr01[arr01<0] = 0

In [4]:
arr01

array([42,  9,  2, 75, 69, 19, 40, 72,  3, 26,  0, 10, 25, 16, 28, 62])

In [5]:
# 10 dan katta sonlarni esa 10 qilish
arr01[arr01>10] = 10

In [6]:
arr01

array([10,  9,  2, 10, 10, 10, 10, 10,  3, 10,  0, 10, 10, 10, 10, 10])

In [7]:
arr2 = np.arange(10, 30).reshape(5, 4)
arr2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [8]:
# har bir qatordagi eng katta qiymatlarni aniqlash
max_ax = np.max(arr2, axis=1)
max_ax

array([13, 17, 21, 25, 29])

In [9]:
# har bir ustundagi o'rtacha qiymatni hisoblash
mean_col = np.mean(arr2, axis=0)
mean_col

array([18., 19., 20., 21.])

In [10]:
# 20 dan katta va juft sonlarni yangi massivga saqlash
new_arr2 = arr2[(arr2>20) & (arr2%2==0)]
new_arr2

array([22, 24, 26, 28])

#####**dtype**

In [11]:
arr3 = np.array([1, 2.5, 3, 4.0, 7])
arr3

array([1. , 2.5, 3. , 4. , 7. ])

In [12]:
# arr3 ning ma'lumot turini aniqlash
arr3.dtype

dtype('float64')

In [13]:
# arr3 ni int ma'lumotiga o'zgartirish
arr3_int = arr3.astype(np.int8)
arr3_int

array([1, 2, 3, 4, 7], dtype=int8)

In [14]:
arr3_int.dtype

dtype('int8')

In [15]:
# tasodifiy 1000 ta sonlardan iborat massiv yaratish
arr4 = np.random.random(1000)
arr4

array([1.30108757e-01, 9.19109183e-01, 4.32464981e-01, 7.32507782e-01,
       8.81775079e-01, 9.62319386e-01, 3.33406529e-01, 4.60913524e-01,
       2.69831582e-01, 1.62851590e-01, 7.22334137e-02, 1.46414256e-01,
       1.04156532e-01, 1.04626810e-01, 4.64175684e-02, 5.18438238e-01,
       5.32341070e-01, 2.91247524e-02, 5.55392774e-01, 5.40091394e-01,
       9.28557525e-01, 4.71094350e-01, 1.72326247e-01, 3.95620167e-01,
       5.49511702e-01, 5.26821139e-01, 1.41741229e-01, 4.16700552e-01,
       1.00581143e-01, 2.91341673e-01, 2.78976765e-02, 7.41644200e-01,
       1.47061323e-01, 9.70803629e-01, 7.82737267e-02, 7.87988421e-01,
       2.53549315e-01, 1.89354609e-01, 5.49846510e-01, 1.19522807e-01,
       7.43565747e-01, 2.74365611e-02, 9.28586860e-01, 9.23017710e-01,
       2.85253192e-01, 8.19379238e-01, 4.91359657e-01, 1.49615838e-01,
       4.11177790e-02, 2.00827749e-01, 3.95640384e-01, 2.04973549e-01,
       4.04680127e-01, 3.63112938e-01, 7.07995071e-01, 8.46368375e-01,
      

In [16]:
# arr4ni xotiradan egallagan joyini aniqlash
arr4.nbytes

8000

In [17]:
arr4.dtype

dtype('float64')

- `arr4` ni ma'lumot turini o'zgartirish orqali uning xotiradan oladigan joyini qisqartirish

In [18]:
arr4_new = arr4.astype(np.float16)
arr4_new

array([1.3013e-01, 9.1895e-01, 4.3237e-01, 7.3242e-01, 8.8184e-01,
       9.6240e-01, 3.3350e-01, 4.6094e-01, 2.6978e-01, 1.6284e-01,
       7.2205e-02, 1.4636e-01, 1.0419e-01, 1.0461e-01, 4.6417e-02,
       5.1855e-01, 5.3223e-01, 2.9129e-02, 5.5518e-01, 5.4004e-01,
       9.2871e-01, 4.7119e-01, 1.7236e-01, 3.9551e-01, 5.4932e-01,
       5.2686e-01, 1.4172e-01, 4.1675e-01, 1.0059e-01, 2.9126e-01,
       2.7893e-02, 7.4170e-01, 1.4709e-01, 9.7070e-01, 7.8247e-02,
       7.8809e-01, 2.5366e-01, 1.8933e-01, 5.4980e-01, 1.1951e-01,
       7.4365e-01, 2.7435e-02, 9.2871e-01, 9.2285e-01, 2.8516e-01,
       8.1934e-01, 4.9146e-01, 1.4966e-01, 4.1107e-02, 2.0081e-01,
       3.9575e-01, 2.0496e-01, 4.0479e-01, 3.6304e-01, 7.0801e-01,
       8.4619e-01, 4.5746e-02, 5.9961e-01, 3.3813e-01, 3.8672e-01,
       3.6621e-01, 2.5952e-01, 6.2646e-01, 7.8857e-01, 6.6872e-03,
       6.2842e-01, 5.6055e-01, 1.6492e-01, 1.1749e-01, 8.5303e-01,
       1.0358e-01, 1.3916e-01, 9.3750e-01, 2.8784e-01, 7.7881e

In [19]:
arr4_new.nbytes

2000

#####**indexing and slicing**

In [20]:
arr5 = np.arange(0, 30)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
# 5-elementdan 20-elementgacha bo'lgan sonlarni olish
arr5[5:20]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
# har 2-elementlarni olish
arr5[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [23]:
# massiv ohiridan 8 ta elementni teskari tartibda olish
arr5[-1:-9:-1]

array([29, 28, 27, 26, 25, 24, 23, 22])

In [24]:
arr6 = np.arange(55, 91).reshape(6, 6)
arr6

array([[55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66],
       [67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89, 90]])

In [25]:
# massivdan markazdagi 4x4 qiymatlarni olish
arr6[1:-1, 1:-1]

array([[62, 63, 64, 65],
       [68, 69, 70, 71],
       [74, 75, 76, 77],
       [80, 81, 82, 83]])

#####**bolean indexing**

In [26]:
arr7 = np.random.randint(-20, 20, 21)
arr7

array([-15,   4,  16, -17, -17,  13,  -4,  -1, -13,  10,  -8,   7,   1,
        16, -11,   6,  15, -18,   3,  15,   8])

In [27]:
# manfiy qiymatlarni ajratish
arr7_neg = arr7[arr7<0]
arr7_neg

array([-15, -17, -17,  -4,  -1, -13,  -8, -11, -18])

In [28]:
# elementlar sonini aniqlash
arr7_neg.size

9

In [29]:
# 5 dan katta va 15 dan kichik qiymatlar
arr7[(arr7>5) & (arr7<15)]

array([13, 10,  7,  6,  8])

In [30]:
# 3 ga karrali bo'lmagan sonlar
arr7[arr7%3!=0]

array([  4,  16, -17, -17,  13,  -4,  -1, -13,  10,  -8,   7,   1,  16,
       -11,   8])

In [31]:
arr8 = np.random.randint(-100, 100, 25).reshape(5,5)
arr8

array([[ 85,  74,  57, -85,  46],
       [-42, -24,  68, -97,  51],
       [-68, -76, -44,  38, -12],
       [-69,  99,  18, -93, -78],
       [ -4,  90, -83,  -5,  -9]])

In [32]:
# faqatgina musbat elementlarni olish
arr8[arr8>0]

array([85, 74, 57, 46, 68, 51, 38, 99, 18, 90])

In [33]:
# dioganaldagi qiymatlarni 0 dan kattasini olish
arr8_diag = np.diag(arr8)
arr8_diag[arr8_diag>0]

array([85])

In [34]:
arr8

array([[ 85,  74,  57, -85,  46],
       [-42, -24,  68, -97,  51],
       [-68, -76, -44,  38, -12],
       [-69,  99,  18, -93, -78],
       [ -4,  90, -83,  -5,  -9]])

In [35]:
# 10 dan katta barcha qiymatlarni -1 ga almashtirish
arr8[arr8>10] = -1

In [36]:
arr8

array([[ -1,  -1,  -1, -85,  -1],
       [-42, -24,  -1, -97,  -1],
       [-68, -76, -44,  -1, -12],
       [-69,  -1,  -1, -93, -78],
       [ -4,  -1, -83,  -5,  -9]])

In [37]:
arr9 = np.arange(1, 16).reshape(3, 5)
arr9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [38]:
# massiv qatorlarini ustunlarga aylantirish
arr9_t = arr9.T
arr9_t

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [39]:
arr9_t.shape

(5, 3)

In [40]:
arr10 = np.random.rand(2, 3, 4)
arr10

array([[[0.93390454, 0.32428   , 0.39917715, 0.64472491],
        [0.72312715, 0.65928469, 0.91929891, 0.78726082],
        [0.24000056, 0.04804161, 0.93785151, 0.54617216]],

       [[0.34239696, 0.26435391, 0.08204504, 0.25732152],
        [0.70106158, 0.62174152, 0.95564714, 0.0933144 ],
        [0.27494635, 0.57223756, 0.14018801, 0.23481885]]])

In [41]:
# arr10 3D massivni : 2D dan 4 ta, 3 qator va 2 ustunli qilish
arr10_swap = np.swapaxes(arr10, 0, 2)
arr10_swap

array([[[0.93390454, 0.34239696],
        [0.72312715, 0.70106158],
        [0.24000056, 0.27494635]],

       [[0.32428   , 0.26435391],
        [0.65928469, 0.62174152],
        [0.04804161, 0.57223756]],

       [[0.39917715, 0.08204504],
        [0.91929891, 0.95564714],
        [0.93785151, 0.14018801]],

       [[0.64472491, 0.25732152],
        [0.78726082, 0.0933144 ],
        [0.54617216, 0.23481885]]])

In [42]:
print("massiv:", arr10.shape)
print("swap_massiv:", arr10_swap.shape)

massiv: (2, 3, 4)
swap_massiv: (4, 3, 2)


In [43]:
arr11 = np.random.uniform(-100, 100, 11)
arr11

array([ 93.82435315, -80.14274668, -80.03017678,  44.53362118,
        82.1235929 ,  17.9744145 ,  39.36954498,  -1.54565431,
        -4.59944563,  -8.29634166,  51.6295314 ])

In [44]:
# har bir elementni musbat yoki manfiyligini aniqlash
np.sign(arr11)

array([ 1., -1., -1.,  1.,  1.,  1.,  1., -1., -1., -1.,  1.])

In [45]:
# massivning manfiy qiymatlarini musbat qilish
arr11_new = np.abs(arr11)
arr11_new

array([93.82435315, 80.14274668, 80.03017678, 44.53362118, 82.1235929 ,
       17.9744145 , 39.36954498,  1.54565431,  4.59944563,  8.29634166,
       51.6295314 ])

In [46]:
print("minimum qiymat:", np.min(arr11_new))
print("maksimum qiymat:", np.max(arr11_new))

minimum qiymat: 1.5456543090549957
maksimum qiymat: 93.82435315497702


In [47]:
# max va min qiymatlari farqi
np.max(arr11_new) - np.min(arr11_new)

np.float64(92.27869884592202)

In [48]:
arr12_1 = np.random.randint(40, 120, 16).reshape(4, 4)
arr12_1

array([[ 71, 108, 104,  71],
       [ 98,  48, 107,  62],
       [105,  65,  50,  92],
       [ 74,  44,  46,  62]])

In [49]:
arr12_2 = np.random.randint(6, 50, 16).reshape(4, 4)
arr12_2

array([[39, 12, 18, 36],
       [ 6, 12,  7, 19],
       [ 9, 46, 23, 45],
       [11, 47, 30,  9]])

In [50]:
# ikkala massivning mos elementlarini solishtirib , ulardan kattasini olish
np.maximum(arr12_1, arr12_2)

array([[ 71, 108, 104,  71],
       [ 98,  48, 107,  62],
       [105,  65,  50,  92],
       [ 74,  47,  46,  62]])

#####**where**

In [51]:
arr13 = np.random.randint(-100, 100, 21)
arr13

array([-14,  86, -74,  95,  10, -29,  93,  37, -43,  60, -56, -61, -76,
       -43,  94, -14,  82,  43, -67,  46, -61])

In [52]:
# agarda qiymat 0 dan kichik bo'lsa 0 ga o'zgartirish
np.where(arr13<0, 0, arr13)

array([ 0, 86,  0, 95, 10,  0, 93, 37,  0, 60,  0,  0,  0,  0, 94,  0, 82,
       43,  0, 46,  0])

In [53]:
# 10 dan katta qiymatlarni -1 ga o'zgartirish
np.where(arr13>10, -1, arr13)

array([-14,  -1, -74,  -1,  10, -29,  -1,  -1, -43,  -1, -56, -61, -76,
       -43,  -1, -14,  -1,  -1, -67,  -1, -61])

In [54]:
arr14 = np.random.uniform(-40, 40, 30).reshape(6, 5)
arr14

array([[ 39.69373162,  18.68750654,   8.38278409,  30.85968915,
        -37.14315085],
       [ -9.69755048, -16.74521702,   1.11169119, -31.15065685,
          7.92402117],
       [ -0.83670503, -27.82650579,   3.888504  , -39.57799776,
         19.46933676],
       [-32.20055965,  26.55828324,  26.71300704,   2.45133619,
         17.56431817],
       [ 22.94879081,  27.65027365,   7.70309906,   0.22673903,
          1.00193874],
       [  1.39245828,  16.50052211, -35.55870021,  15.54322053,
         18.36883311]])

In [57]:
# faqatgina musbat elementlardan tashkil topgan yangi massiv hosil qilish
arr14_new = arr14[np.where(arr14>0)]
arr14_new

array([39.69373162, 18.68750654,  8.38278409, 30.85968915,  1.11169119,
        7.92402117,  3.888504  , 19.46933676, 26.55828324, 26.71300704,
        2.45133619, 17.56431817, 22.94879081, 27.65027365,  7.70309906,
        0.22673903,  1.00193874,  1.39245828, 16.50052211, 15.54322053,
       18.36883311])

In [58]:
# manfiy elementlar indekslarini aniqlash
np.where(arr14<0)

(array([0, 1, 1, 1, 2, 2, 2, 3, 5]), array([4, 0, 1, 3, 0, 1, 3, 0, 2]))

In [60]:
# musbat qiymatlarni kvadratini , manfiy qiymatlarni o'zini hisoblash
np.where(arr14>0, arr14**2, arr14)

array([[ 1.57559233e+03,  3.49222901e+02,  7.02710692e+01,
         9.52320414e+02, -3.71431509e+01],
       [-9.69755048e+00, -1.67452170e+01,  1.23585729e+00,
        -3.11506569e+01,  6.27901114e+01],
       [-8.36705030e-01, -2.78265058e+01,  1.51204633e+01,
        -3.95779978e+01,  3.79055074e+02],
       [-3.22005596e+01,  7.05342409e+02,  7.13584745e+02,
         6.00904911e+00,  3.08505273e+02],
       [ 5.26647000e+02,  7.64537633e+02,  5.93377351e+01,
         5.14105857e-02,  1.00388125e+00],
       [ 1.93894007e+00,  2.72267230e+02, -3.55587002e+01,
         2.41591704e+02,  3.37414030e+02]])

#####**arithmetic operations**

In [61]:
arr15_1 = np.random.randint(-100, 100, 11)
arr15_2 = np.random.randint(-50, 50, 11)
arr15_1

array([ 98, -31,  33, -79,   4,  -6,   7, -21,  48,  38,   9])

In [62]:
arr15_2

array([-26,  42, -33, -25,   3, -40, -18,   9, -31, -24, -33])

In [63]:
# mos elementlarini qo'shish
arr15_1+arr15_2

array([  72,   11,    0, -104,    7,  -46,  -11,  -12,   17,   14,  -24])

In [64]:
# mos elementlarni ayirish
arr15_1-arr15_2

array([124, -73,  66, -54,   1,  34,  25, -30,  79,  62,  42])

In [65]:
# mos elementlarni ko'paytirish
arr15_1*arr15_2

array([-2548, -1302, -1089,  1975,    12,   240,  -126,  -189, -1488,
        -912,  -297])

In [67]:
# mos elementlarini bo'lish
arr15_1/arr15_2

array([-3.76923077, -0.73809524, -1.        ,  3.16      ,  1.33333333,
        0.15      , -0.38888889, -2.33333333, -1.5483871 , -1.58333333,
       -0.27272727])

In [68]:
arr16 = np.random.randint(-100, 100, 24).reshape(4, 6)
arr16

array([[ 44,  12, -93, -83,  97,  59],
       [-92,  36, -73,  92,   7,  74],
       [-57,  57, -43,  87, -49,  58],
       [ 46,  65,  93,  35, -52,  39]])

In [70]:
# har bir qatorni yig'indisini aniqlash
np.sum(arr16, axis=1)

array([ 36,  44,  53, 226])

In [72]:
# har bir ustundagi elementlar ko'paytmasini aniqlash
np.prod(arr16, axis=0)

array([ 10613856,   1600560, -27149211, -23251620,   1730092,   9875892])

In [74]:
# massivning o'rtacha qiymatini aniqlash
np.mean(arr16)

np.float64(14.958333333333334)

- *har bir qatordan , shu qatorni o'rtacha qiymatini ayirish*

In [78]:
arr16_mean = np.mean(arr16, axis=1, keepdims=True)
arr16_mean

array([[ 6.        ],
       [ 7.33333333],
       [ 8.83333333],
       [37.66666667]])

In [79]:
arr16-arr16_mean

array([[ 38.        ,   6.        , -99.        , -89.        ,
         91.        ,  53.        ],
       [-99.33333333,  28.66666667, -80.33333333,  84.66666667,
         -0.33333333,  66.66666667],
       [-65.83333333,  48.16666667, -51.83333333,  78.16666667,
        -57.83333333,  49.16666667],
       [  8.33333333,  27.33333333,  55.33333333,  -2.66666667,
        -89.66666667,   1.33333333]])

#####**sorting**

- massivlar AI yordamida yaratiladi

In [80]:
arr17 = np.array([12, -3, 45, 7, 0, 19, -8, 23, 5, 42, 16, -1, 9, 30, 4])
arr17

array([12, -3, 45,  7,  0, 19, -8, 23,  5, 42, 16, -1,  9, 30,  4])

In [81]:
# massivni o'sish tartibida saralash
np.sort(arr17)

array([-8, -3, -1,  0,  4,  5,  7,  9, 12, 16, 19, 23, 30, 42, 45])

In [82]:
# kamayish tartibida saralash
-np.sort(-arr17)

array([45, 42, 30, 23, 19, 16, 12,  9,  7,  5,  4,  0, -1, -3, -8])

In [85]:
# eng kichik 5 ta elementni olish
-np.sort(-arr17)[-5:]

array([ 4,  0, -1, -3, -8])

- *eng katta 3 ta elementni indeksini olish*

In [96]:
arr17_idx = np.argsort(arr17)
arr17_idx[-3:]

array([13,  9,  2])

In [97]:
arr18 = np.array([[12,  5,  9,  1],[20, -3,  7, 14],[ 6, 18,  2, 11],[25,  4, -6, 10],[ 8, 16,  3, 19]])
arr18

array([[12,  5,  9,  1],
       [20, -3,  7, 14],
       [ 6, 18,  2, 11],
       [25,  4, -6, 10],
       [ 8, 16,  3, 19]])

In [98]:
# har bir qatordagi elementlarni tartiblash
np.sort(arr18, axis=1)

array([[ 1,  5,  9, 12],
       [-3,  7, 14, 20],
       [ 2,  6, 11, 18],
       [-6,  4, 10, 25],
       [ 3,  8, 16, 19]])