<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/arr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Creating an array using the array function
lst = [1, 2.2, -3, 4, -5.5]
arr = np.array(lst)
print(arr)

[ 1.   2.2 -3.   4.  -5.5]


In [3]:
tpl = (1.1, -2.2, 3, -4, 5)
arr2 = np.array(tpl)
print(arr2)

[ 1.1 -2.2  3.  -4.   5. ]


In [4]:
# create using array creation functions | zeros
zer = np.zeros(5)
print(zer)

[0. 0. 0. 0. 0.]


In [5]:
# create by shaping
zer2 = np.zeros((3, 4))
print(zer2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# create with ones function
ons = np.ones(5)
print(ons)

[1. 1. 1. 1. 1.]


In [7]:
# shape
ons2 = np.ones((3, 4))
print(ons2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
# create using the arange function
arng = np.arange(5)
print(arng)

[0 1 2 3 4]


In [9]:
# start, stop, step
arng2 = np.arange(1, 11, 2)
print(arng2)

[1 3 5 7 9]


In [10]:
# create using the random function
rand = np.random.rand(5)
print(rand)

[0.2512648  0.27443142 0.98115848 0.98110047 0.31317964]


In [11]:
rand2 = np.random.rand(3, 4)
rand2

array([[0.76794463, 0.33055865, 0.82594592, 0.34100968],
       [0.39539904, 0.38152229, 0.72218244, 0.50693452],
       [0.62792244, 0.20122735, 0.93513711, 0.77289373]])

In [12]:
# random.randn
rand3 = np.random.randn(5)
rand3

array([ 0.49929788, -0.11696983, -0.07823918,  0.16837787, -0.28977409])

In [13]:
rand4 = np.random.randn(3, 4)
print(rand4)

[[-1.19747551  0.75779286 -1.159123   -0.5144872 ]
 [-0.07071313 -0.84872955  0.97534295 -1.56901838]
 [ 0.64389421  0.83195043  0.59788696 -0.49476138]]


In [15]:
rand5 = np.random.randint(10, 100, 5)
rand5

array([41, 69, 11, 37, 64])

In [16]:
rand6 = np.random.randint(10, 110, (2, 3))
rand6

array([[22, 22, 55],
       [98, 17, 19]])

In [17]:
rand7 = np.random.random_sample(5)
rand7

array([0.65922733, 0.76893538, 0.46525817, 0.5396953 , 0.34676992])

In [20]:
rand8 = np.random.random_sample((3, 4))
rand8

array([[0.24779123, 0.6540256 , 0.07772819, 0.8572894 ],
       [0.70022065, 0.62837278, 0.03824234, 0.22192309],
       [0.65148171, 0.99337522, 0.43924326, 0.60897413]])

In [21]:
rand9 = np.random.random(5)
rand9

array([0.58688392, 0.08110796, 0.15481117, 0.49879823, 0.78042607])

In [22]:
rand10 = np.random.random((3, 4))
rand10

array([[0.22089554, 0.91901181, 0.9922807 , 0.85384888],
       [0.47270562, 0.5168624 , 0.27763147, 0.23709891],
       [0.53926562, 0.85454626, 0.82644318, 0.25453371]])

In [24]:
# determining array size
arr.ndim

1

In [25]:
rand2.ndim

2

In [26]:
# determine the number of rows and columns
arr2.shape

(5,)

In [27]:
rand5.shape

(5,)

In [28]:
rand10.shape

(3, 4)

In [30]:
# determine the number of elements
rand10.size

12

In [31]:
arr2.size

5