<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/arr_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# create an array with array function
lst = [1, 2.2, 3, -4.4, -5, 6]
arr1 = np.array(lst)

In [3]:
print(list)

<class 'list'>


In [4]:
print(arr1)

[ 1.   2.2  3.  -4.4 -5.   6. ]


In [5]:
type(arr1)

numpy.ndarray

In [6]:
lst2 = ['a', 'b', 'c', 'd']
arr2 = np.array(lst2)
print(lst2)
print(arr2)
print(type(arr2))

['a', 'b', 'c', 'd']
['a' 'b' 'c' 'd']
<class 'numpy.ndarray'>


In [7]:
# create an array with zeros function
z_arr = np.zeros(5)
print(z_arr)

[0. 0. 0. 0. 0.]


In [8]:
type(z_arr)

numpy.ndarray

In [9]:
z_arr2 = np.zeros((3, 4))
print(z_arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# create an array with ones function
o_arr = np.ones(5)
print(o_arr)

[1. 1. 1. 1. 1.]


In [11]:
type(o_arr)

numpy.ndarray

In [12]:
o_arr2 = np.ones((3, 4))
print(o_arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# create an array with arange function
a_arr = np.arange(5)
print(a_arr)

[0 1 2 3 4]


In [14]:
a_arr2 = np.arange(1, 11)
print(a_arr2)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
a_arr3 = np.arange(10, 100, 10)
print(a_arr3)

[10 20 30 40 50 60 70 80 90]


In [16]:
# create an array with random function
r_arr = np.random.rand(5)
print(r_arr)

[0.83413943 0.55581016 0.42449416 0.63829174 0.74972208]


In [17]:
r_arr2 = np.random.rand(3, 4)
print(r_arr2)

[[0.94346356 0.15156882 0.74242277 0.12540296]
 [0.23918963 0.85792571 0.9555784  0.89010847]
 [0.45242421 0.57851337 0.61693675 0.00542051]]


In [18]:
# with randn
r_arr3 = np.random.randn(5)
print(r_arr3)

[-0.31570315 -0.09005388  0.17538983 -1.27337834 -0.85596161]


In [19]:
r_arr4 = np.random.randn(3, 4)
print(r_arr4)

[[ 2.24143568e+00  4.10791472e-02 -2.87312170e-01  1.68977041e-01]
 [ 9.03891917e-01 -8.16515797e-01 -9.93756674e-02  6.52505835e-01]
 [ 6.56354218e-01  1.15231886e+00 -8.28564611e-04  1.35306577e+00]]


In [34]:
# with randint
r_arr5 = np.random.randint(4)
print(r_arr5)

3


In [35]:
r_arr6 = np.random.randint(1, 11, 4)
print(r_arr6)

[8 8 6 9]


In [36]:
r_arr7 = np.random.randint(1, 111, (3, 4))
print(r_arr7)

[[ 54 106  50  63]
 [  7  40  78   4]
 [ 93  48  38  15]]


In [37]:
# with random_sample
r_arr8 = np.random.random_sample(5)
print(r_arr8)

[0.83055323 0.36564386 0.15638025 0.3759261  0.59637538]


In [39]:
# with random.random
r_arr9 = np.random.random((3, 4))
print(r_arr9)

[[0.88906927 0.62806193 0.98495661 0.7340969 ]
 [0.13207635 0.80489341 0.09366124 0.05552808]
 [0.56146277 0.91898648 0.50727138 0.13955118]]


In [40]:
# determining array size
z_arr2.ndim

2

In [41]:
r_arr2.ndim

2

In [42]:
# determine the number of rows and columns of an array
z_arr.shape

(5,)

In [43]:
z_arr2.shape

(3, 4)

In [44]:
# determine the number of all elements of an array
r_arr2.size

12

In [45]:
z_arr.size

5