<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/bool.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
names = np.array(['Hasan', 'Husan', 'Elyor', 'Mirasil', 'Hasan', 'Abdurashid', 'Elyor', 'Abror', 'Javohir'])
names

array(['Hasan', 'Husan', 'Elyor', 'Mirasil', 'Hasan', 'Abdurashid',
       'Elyor', 'Abror', 'Javohir'], dtype='<U10')

In [4]:
data = np.random.rand(9, 4)
data

array([[0.77027187, 0.57285044, 0.11768574, 0.50467435],
       [0.39977593, 0.46409184, 0.63676399, 0.05169233],
       [0.38733323, 0.19718726, 0.38807466, 0.70885309],
       [0.79453258, 0.29464133, 0.61899376, 0.64039975],
       [0.8904553 , 0.69478069, 0.72018387, 0.38915406],
       [0.37191931, 0.2716145 , 0.95053089, 0.09398536],
       [0.48213768, 0.99898781, 0.21529348, 0.74246691],
       [0.14755477, 0.55186031, 0.62320631, 0.42870728],
       [0.38297398, 0.70436564, 0.08555166, 0.62350197]])

- each row is the data of one person

In [5]:
# boolean index
names == 'Abdurashid'

array([False, False, False, False, False,  True, False, False, False])

In [6]:
names == 'Elyor'

array([False, False,  True, False, False, False,  True, False, False])

In [7]:
# Slicing Abdurashid's data using boolean indexing
data[names == 'Abdurashid']

array([[0.37191931, 0.2716145 , 0.95053089, 0.09398536]])

In [8]:
# Elyor's data
data[names == 'Elyor']

array([[0.38733323, 0.19718726, 0.38807466, 0.70885309],
       [0.48213768, 0.99898781, 0.21529348, 0.74246691]])

In [9]:
# Hasan's data
data[names == 'Hasan']

array([[0.77027187, 0.57285044, 0.11768574, 0.50467435],
       [0.8904553 , 0.69478069, 0.72018387, 0.38915406]])

In [10]:
# get all the data except for hasan's data
data[names != 'Hasan']

array([[0.39977593, 0.46409184, 0.63676399, 0.05169233],
       [0.38733323, 0.19718726, 0.38807466, 0.70885309],
       [0.79453258, 0.29464133, 0.61899376, 0.64039975],
       [0.37191931, 0.2716145 , 0.95053089, 0.09398536],
       [0.48213768, 0.99898781, 0.21529348, 0.74246691],
       [0.14755477, 0.55186031, 0.62320631, 0.42870728],
       [0.38297398, 0.70436564, 0.08555166, 0.62350197]])

In [11]:
# get all the data except for elyor's data
data[names != 'Elyor']

array([[0.77027187, 0.57285044, 0.11768574, 0.50467435],
       [0.39977593, 0.46409184, 0.63676399, 0.05169233],
       [0.79453258, 0.29464133, 0.61899376, 0.64039975],
       [0.8904553 , 0.69478069, 0.72018387, 0.38915406],
       [0.37191931, 0.2716145 , 0.95053089, 0.09398536],
       [0.14755477, 0.55186031, 0.62320631, 0.42870728],
       [0.38297398, 0.70436564, 0.08555166, 0.62350197]])