<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/bool.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
names = np.array(['Hasan', 'Husan', 'Elyor', 'Mirasil', 'Hasan', 'Abdurashid', 'Elyor', 'Abror', 'Javohir'])
names

array(['Hasan', 'Husan', 'Elyor', 'Mirasil', 'Hasan', 'Abdurashid',
       'Elyor', 'Abror', 'Javohir'], dtype='<U10')

In [3]:
data = np.random.rand(9, 4)
data

array([[0.60772105, 0.51690904, 0.47587714, 0.49959237],
       [0.34561948, 0.32190688, 0.81247601, 0.46543106],
       [0.65961477, 0.23203385, 0.33289681, 0.33259878],
       [0.73812994, 0.64211784, 0.09533755, 0.68210558],
       [0.34641604, 0.55476335, 0.98544032, 0.04098587],
       [0.21562993, 0.70389242, 0.49270305, 0.92959049],
       [0.284825  , 0.74977021, 0.46652483, 0.68043066],
       [0.96003979, 0.8345763 , 0.44913055, 0.55325273],
       [0.89515238, 0.19074516, 0.0310086 , 0.22454645]])

- each row is the data of one person

In [4]:
# boolean index
names == 'Abdurashid'

array([False, False, False, False, False,  True, False, False, False])

In [5]:
names == 'Elyor'

array([False, False,  True, False, False, False,  True, False, False])

In [6]:
# Slicing Abdurashid's data using boolean indexing
data[names == 'Abdurashid']

array([[0.21562993, 0.70389242, 0.49270305, 0.92959049]])

In [7]:
# Elyor's data
data[names == 'Elyor']

array([[0.65961477, 0.23203385, 0.33289681, 0.33259878],
       [0.284825  , 0.74977021, 0.46652483, 0.68043066]])

In [8]:
# Hasan's data
data[names == 'Hasan']

array([[0.60772105, 0.51690904, 0.47587714, 0.49959237],
       [0.34641604, 0.55476335, 0.98544032, 0.04098587]])

In [9]:
# get all the data except for hasan's data
data[names != 'Hasan']

array([[0.34561948, 0.32190688, 0.81247601, 0.46543106],
       [0.65961477, 0.23203385, 0.33289681, 0.33259878],
       [0.73812994, 0.64211784, 0.09533755, 0.68210558],
       [0.21562993, 0.70389242, 0.49270305, 0.92959049],
       [0.284825  , 0.74977021, 0.46652483, 0.68043066],
       [0.96003979, 0.8345763 , 0.44913055, 0.55325273],
       [0.89515238, 0.19074516, 0.0310086 , 0.22454645]])

In [10]:
# get all the data except for elyor's data
data[names != 'Elyor']

array([[0.60772105, 0.51690904, 0.47587714, 0.49959237],
       [0.34561948, 0.32190688, 0.81247601, 0.46543106],
       [0.73812994, 0.64211784, 0.09533755, 0.68210558],
       [0.34641604, 0.55476335, 0.98544032, 0.04098587],
       [0.21562993, 0.70389242, 0.49270305, 0.92959049],
       [0.96003979, 0.8345763 , 0.44913055, 0.55325273],
       [0.89515238, 0.19074516, 0.0310086 , 0.22454645]])

In [11]:
# Get Mirasil and Abror's data in one place
two = (names == 'Mirasil') | (names == 'Abror')
data[two]

array([[0.73812994, 0.64211784, 0.09533755, 0.68210558],
       [0.96003979, 0.8345763 , 0.44913055, 0.55325273]])

In [16]:
# get information from 3 people in one
three = (names =='Javohir') | (names == 'Mirasil') | (names == 'Abdurashid')
three

array([False, False, False,  True, False,  True, False, False,  True])

In [17]:
data[three]

array([[0.73812994, 0.64211784, 0.09533755, 0.68210558],
       [0.21562993, 0.70389242, 0.49270305, 0.92959049],
       [0.89515238, 0.19074516, 0.0310086 , 0.22454645]])

In [20]:
# get the last 2 details of abdurashid
data[names == 'Abdurashid', 2:]

array([[0.49270305, 0.92959049]])

In [23]:
data[names == 'Elyor']

array([[0.65961477, 0.23203385, 0.33289681, 0.33259878],
       [0.284825  , 0.74977021, 0.46652483, 0.68043066]])

In [25]:
data[names == 'Elyor', 1:3]

array([[0.23203385, 0.33289681],
       [0.74977021, 0.46652483]])

- *boolean indexing with numeric data*

In [30]:
arr = np.array([1, -2, 3, -4, 5, -6, 7, 8, -9, 10])
arr

array([ 1, -2,  3, -4,  5, -6,  7,  8, -9, 10])

In [33]:
# set elements less than 0 to 0
arr[arr < 0] = 0

In [34]:
print(arr)

[ 1  0  3  0  5  0  7  8  0 10]


In [35]:
# making numbers less than 7 into 1
arr[arr < 7] = 1
print(arr)

[ 1  1  1  1  1  1  7  8  1 10]


In [36]:
# displaying numbers 7 and greater
print(arr[arr>=7])

[ 7  8 10]
