<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/dtype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(1.1, 9.9, 2)
arr

array([1.1, 3.1, 5.1, 7.1, 9.1])

In [4]:
# specifying the data type of an array when creating it
arr2 = np.array([1.1, -2.2, 3.3, -4.4, 5.5], dtype=np.float16)
arr2

array([ 1.1, -2.2,  3.3, -4.4,  5.5], dtype=float16)

In [7]:
arr3 = np.arange(1, 10, dtype=np.int8)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [8]:
# determining the data type of an array
arr.dtype

dtype('float64')

In [9]:
arr2.dtype

dtype('float16')

In [10]:
arr3.dtype

dtype('int8')

In [11]:
# convert an array to another data type
# casting arr2 to integer type
arr2_int = arr2.astype(np.int8)
print(arr2_int)

[ 1 -2  3 -4  5]


In [12]:
print("arr2 dtype =", arr2.dtype)
print("arr2_int dtype =", arr2_int.dtype)

arr2 dtype = float16
arr2_int dtype = int8
