<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/indexing_slic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(10, 110, 10)
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [3]:
# 20
arr[1]

np.int64(20)

In [4]:
# 40
arr[3]

np.int64(40)

In [5]:
# 60, 70
arr[5:7]

array([60, 70])

In [6]:
# 90, 100
arr[-2:]

array([ 90, 100])

In [7]:
# 100
arr[-1]

np.int64(100)

- *cutting elements from an array and modifying them*

In [8]:
# 60, 70, 80
arr_slic = arr[5:8]
arr_slic

array([60, 70, 80])

In [9]:
arr_slic[0] = -11
arr_slic[1] = -22
arr_slic[0] = -33
print(arr_slic)

[-33 -22  80]


In [10]:
print(arr)
print(arr_slic)

[ 10  20  30  40  50 -33 -22  80  90 100]
[-33 -22  80]


- *affected the elements of the main array*

In [12]:
# slicing without affecting the elements of the main array : 10, 20, 30
arr2_slic = arr[0:3].copy()
arr2_slic

array([10, 20, 30])

In [13]:
arr2_slic[0] = -1
arr2_slic[1] = -2
arr2_slic[2] = -3

In [14]:
print(arr)
print(arr2_slic)

[ 10  20  30  40  50 -33 -22  80  90 100]
[-1 -2 -3]


In [19]:
arr_str = np.array(['Bobur', 'Aziz', 'Dilshod'])
arr_str

array(['Bobur', 'Aziz', 'Dilshod'], dtype='<U7')

In [20]:
arr_str2 = arr_str[:].copy()
arr_str2

array(['Bobur', 'Aziz', 'Dilshod'], dtype='<U7')

In [21]:
arr_str2[1] = 'Sherzod'

In [22]:
print(arr_str)
print(arr_str2)

['Bobur' 'Aziz' 'Dilshod']
['Bobur' 'Sherzod' 'Dilshod']
