<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/indexing_slic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(10, 110, 10)
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [3]:
# 20
arr[1]

np.int64(20)

In [4]:
# 40
arr[3]

np.int64(40)

In [5]:
# 60, 70
arr[5:7]

array([60, 70])

In [6]:
# 90, 100
arr[-2:]

array([ 90, 100])

In [7]:
# 100
arr[-1]

np.int64(100)

- *cutting elements from an array and modifying them*

In [8]:
# 60, 70, 80
arr_slic = arr[5:8]
arr_slic

array([60, 70, 80])

In [9]:
arr_slic[0] = -11
arr_slic[1] = -22
arr_slic[0] = -33
print(arr_slic)

[-33 -22  80]


In [10]:
print(arr)
print(arr_slic)

[ 10  20  30  40  50 -33 -22  80  90 100]
[-33 -22  80]


- *affected the elements of the main array*

In [11]:
# slicing without affecting the elements of the main array : 10, 20, 30
arr2_slic = arr[0:3].copy()
arr2_slic

array([10, 20, 30])

In [12]:
arr2_slic[0] = -1
arr2_slic[1] = -2
arr2_slic[2] = -3

In [13]:
print(arr)
print(arr2_slic)

[ 10  20  30  40  50 -33 -22  80  90 100]
[-1 -2 -3]


In [14]:
arr_str = np.array(['Bobur', 'Aziz', 'Dilshod'])
arr_str

array(['Bobur', 'Aziz', 'Dilshod'], dtype='<U7')

In [15]:
arr_str2 = arr_str[:].copy()
arr_str2

array(['Bobur', 'Aziz', 'Dilshod'], dtype='<U7')

In [16]:
arr_str2[1] = 'Sherzod'

In [17]:
print(arr_str)
print(arr_str2)

['Bobur' 'Aziz' 'Dilshod']
['Bobur' 'Sherzod' 'Dilshod']


In [18]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
# 2
print(arr2d[0, 1])

2


In [21]:
# 4
print(arr2d[0, -1])

4


In [22]:
# 5, 6
print(arr2d[1, 0:2])

[5 6]


In [23]:
# 10, 11, 12
print(arr2d[2, 1:])

[10 11 12]


In [24]:
# 11, 12, 15, 16
print(arr2d[2:, 2:])

[[11 12]
 [15 16]]


In [26]:
# indexing and slicing in 3D array
arr3d = np.arange(41, 59).reshape(3, 2, 3)
arr3d

array([[[41, 42, 43],
        [44, 45, 46]],

       [[47, 48, 49],
        [50, 51, 52]],

       [[53, 54, 55],
        [56, 57, 58]]])

In [28]:
# 42
print(arr3d[0][0, 1])

42


In [30]:
# 45, 46
print(arr3d[0][1, 1:])

[45 46]


In [32]:
# 47, 50
print(arr3d[1][:, 0])

[47 50]


In [34]:
# 55, 58
print(arr3d[-1][:, -1])

[55 58]
