<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/indx_slic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10, 110, 10)
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
arr[0:4]

array([10, 20, 30, 40])

In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
slic_arr = arr2[1, 1:]
slic_arr

array([5, 6])

In [ ]:
slic_arr[:] = -11
slic_arr

array([-11, -11])

In [ ]:
print(arr2)

[[  1   2   3]
 [  4 -11 -11]
 [  7   8   9]]


In [ ]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
slic_arr3 = arr3[1][1, :]
print(slic_arr3)

[10 11 12]


In [ ]:
slic_arr3[0] = -22
slic_arr3[1] = -33
slic_arr3[2] = -44
slic_arr3

array([-22, -33, -44])

In [ ]:
arr3

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [-22, -33, -44]]])