<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [9]:
arr = np.arange(6).reshape(3, 2)
print(arr)

[[0 1]
 [2 3]
 [4 5]]


In [10]:
arr.T

array([[0, 2, 4],
       [1, 3, 5]])

In [11]:
arr.swapaxes(1, 0)

array([[0, 2, 4],
       [1, 3, 5]])

In [12]:
arr2 = np.random.randint(1, 100, (3, 4))
print(arr2)

[[14 69  2 40]
 [52 18 59 28]
 [48 66 41 58]]


In [13]:
arr2.ndim

2

In [16]:
arr2.T

array([[14, 52, 48],
       [69, 18, 66],
       [ 2, 59, 41],
       [40, 28, 58]])

In [18]:
arr2.swapaxes(0, 1)

array([[14, 52, 48],
       [69, 18, 66],
       [ 2, 59, 41],
       [40, 28, 58]])

In [19]:
arr2

array([[14, 69,  2, 40],
       [52, 18, 59, 28],
       [48, 66, 41, 58]])

In [21]:
arr2.swapaxes(0, 1) # 0-rows , 1-columns

array([[14, 52, 48],
       [69, 18, 66],
       [ 2, 59, 41],
       [40, 28, 58]])

In [24]:
arr3 = np.arange(24).reshape((2, 3, 4))
print(f"Asl massiv (shakli: {arr3.shape}):\n{arr3}")
# Shakli: (2, 3, 4) - 2 ta namuna, har birida 3 qator va 4 ustun

# 0-chi (namunalar) va 1-chi (qatorlar) o'lchamlarni almashtirish
swapped_arr3_01 = np.swapaxes(arr3, 0, 1)
print(f"\n0 va 1 almashtirilgan (shakli: {swapped_arr3_01.shape}):\n{swapped_arr3_01}")
# Shakli: (3, 2, 4) - endi 3 ta 'namuna' (oldingi qatorlar), har birida 2 ta 'qator' (oldingi namunalar) va 4 ta ustun

# 1-chi (oldingi qatorlar) va 2-chi (ustunlar) o'lchamlarni almashtirish
swapped_arr3_12 = np.swapaxes(arr3, 1, 2)
print(f"\n1 va 2 almashtirilgan (shakli: {swapped_arr3_12.shape}):\n{swapped_arr3_12}")
# Shakli: (2, 4, 3) - 2 ta namuna, har birida 4 ta 'qator' (oldingi ustunlar) va 3 ta 'ustun' (oldingi qatorlar)

Asl massiv (shakli: (2, 3, 4)):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

0 va 1 almashtirilgan (shakli: (3, 2, 4)):
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

1 va 2 almashtirilgan (shakli: (2, 4, 3)):
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]
