<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/reinforcement/univer_funcs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
# sqrt - returns the square root of each element
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [9]:
# abs, fabs - gives the absolute value of each element
print(np.abs(arr))
print(np.fabs(arr))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [10]:
arr_m = np.random.randn(5)
print(arr_m)

[-0.9488566  -0.22025252  1.45754676  0.22825425  0.95709882]


In [11]:
print(np.abs(arr_m))

[0.9488566  0.22025252 1.45754676 0.22825425 0.95709882]


In [12]:
print(np.fabs(arr_m))

[0.9488566  0.22025252 1.45754676 0.22825425 0.95709882]


In [13]:
# square - gives the square of each element
print(np.square(arr))

[  1   4   9  16  25  36  49  64  81 100]


In [14]:
np.square(arr_m)

array([0.90032886, 0.04851117, 2.12444256, 0.0521    , 0.91603815])

In [15]:
# exp - returns the exponent of each element
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [16]:
np.exp(arr_m)

array([0.38718347, 0.80231617, 4.29540893, 1.25640472, 2.60413045])