<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/scikit-learn/onehotencoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ushbu sahifada OneHotEncoder - matnli ustunlarni songa o'tkizish amaliyot qilinadi**

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
df = pd.DataFrame({
    "city": [
        "Tashkent",
        "Samarkand",
        "Bukhara",
        "Tashkent",
        "Samarkand",
        "Bukhara"
    ],
    "gender": [
        "Male",
        "Female",
        "Female",
        "Male",
        "Male",
        "Female"
    ]
})
df.shape

(6, 2)

In [3]:
df

,city,gender
0,Tashkent,Male
1,Samarkand,Female
2,Bukhara,Female
3,Tashkent,Male
4,Samarkand,Male
5,Bukhara,Female


In [4]:
# X va y larni ajratish (datasetimiz kichikligi uchun y olinmiydi)
X = df[['city', 'gender']]

from sklearn.model_selection import train_test_split

# train va testlarga bo'lish
X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)

print("shape X_train:", X_train.shape)
print("shape X_test:", X_test.shape)

shape X_train: (4, 2)
shape X_test: (2, 2)


In [7]:
from sklearn.preprocessing import OneHotEncoder

# obyekt yaratish
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

train_encoded = encoder.fit_transform(X_train)
test_encoded = encoder.transform(X_test)

print("X_train:\n", X_train)
print("\ntrain_encoded:\n", train_encoded)

X_train:
         city  gender
5    Bukhara  Female
2    Bukhara  Female
4  Samarkand    Male
3   Tashkent    Male

train_encoded:
 [[1. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]]


In [8]:
# qaysi kategoriyalarni o'rganganini ko'rish
encoder.categories_

[array(['Bukhara', 'Samarkand', 'Tashkent'], dtype=object),
 array(['Female', 'Male'], dtype=object)]

In [9]:
# yangi ustun nomlarini ko'rish
encoder.get_feature_names_out()

array(['city_Bukhara', 'city_Samarkand', 'city_Tashkent', 'gender_Female',
       'gender_Male'], dtype=object)