<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/scikit-learn/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ushbu sahifada ma'lumotlarni oldindan qayta ishlashni amaliyot qilamiz**

###**Feature Scaling**

In [1]:
import numpy as np
import pandas as pd
import sklearn

**Standard Scaler bilan ishlash**

In [2]:
df = pd.DataFrame({
    "age": [20, 25, 30, 35, 40],
    "salary": [2000, 3000, 5000, 7000, 10000]
})
df

,age,salary
0,20,2000
1,25,3000
2,30,5000
3,35,7000
4,40,10000


In [3]:
df.describe()

,age,salary
count,5.000000,5.000000
mean,30.000000,5400.000000
std,7.905694,3209.361307
min,20.000000,2000.000000
25%,25.000000,3000.000000
50%,30.000000,5000.000000
75%,35.000000,7000.000000
max,40.000000,10000.000000


- shunchaki amaliyot uchun faqatgina X ni ajratib olamiz , y shart emas

In [4]:
X = df[['age', 'salary']]
type(X)

pandas.core.frame.DataFrame

In [5]:
# ma'lumotlarni bo'lish
from sklearn.model_selection import train_test_split

X_train, X_test = train_test_split(X, random_state=42, test_size=0.2)

print("shape train:", X_train.shape)
print("shape test:", X_test.shape)

shape train: (4, 2)
shape test: (1, 2)


In [6]:
# featuresni bir xil masshtabga tushirish
from sklearn.preprocessing import StandardScaler

# obyekt yaratish
scaler = StandardScaler()

# scaling qilish
X_train_scaling = scaler.fit_transform(X_train)
X_test_scaling = scaler.transform(X_test)

In [7]:
X_train_scaling

array([[ 1.18321596,  1.37198868],
       [-0.16903085, -0.34299717],
       [-1.52127766, -1.37198868],
       [ 0.50709255,  0.34299717]])

In [8]:
X_test_scaling

array([[-0.84515425, -1.02899151]])

###**MinMaxScaler**

In [9]:
# yuqoridagi data bilan MinMaxScaler qilish
X_train

,age,salary
4,40,10000
2,30,5000
0,20,2000
3,35,7000


In [10]:
X_test

,age,salary
1,25,3000


In [11]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

X_minmax_scaled = min_max_scaler.fit_transform(X_train)
X_minmax_test_scaled = min_max_scaler.transform(X_test)
X_minmax_scaled

array([[1.   , 1.   ],
       [0.5  , 0.375],
       [0.   , 0.   ],
       [0.75 , 0.625]])

In [12]:
X_minmax_test_scaled

array([[0.25 , 0.125]])