<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/04_05_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#####**broadcasting**

In [1]:
import numpy as np

In [2]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([2, 4, 6, 8, 10])
print("Array 1:", arr1)
print("Array 2:", arr2)

Array 1: [10 20 30 40 50]
Array 2: [ 2  4  6  8 10]


In [3]:
# Add two arrays element by element
arr1+arr2

array([12, 24, 36, 48, 60])

In [4]:
# Multiply two arrays element by element
arr1*arr2

array([ 20,  80, 180, 320, 500])

In [5]:
# Subtract arr2 from arr1 element by element
arr1-arr2

array([ 8, 16, 24, 32, 40])

In [6]:
# Divide arr1 into arr2 element by element
arr1/arr2

array([5., 5., 5., 5., 5.])

In [7]:
arr3 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr4 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

In [8]:
print("Array 1:")
print(arr3)
print("\nArray 2:")
print(arr4)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [9]:
# Add two matrices element by element
arr3+arr4

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [10]:
# Multiply two matrices element by element
arr3*arr4

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [11]:
# Divide each element of arr3 by the corresponding element of arr4
arr3/arr4

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [12]:
arr5 = np.array([5, 10, 15, 20])
arr6 = np.array([1, 2, 3, 4])

print("Array 1:", arr5)
print("Array 2:", arr6)

Array 1: [ 5 10 15 20]
Array 2: [1 2 3 4]


In [13]:
# Multiply two arrays element by element
arr7 = arr5*arr6
arr7

array([ 5, 20, 45, 80])

In [14]:
# Raise each element in the result by 2 (square it)
arr7**2

array([  25,  400, 2025, 6400])

In [15]:
# Add each element of arr5 with the corresponding element of arr6 and divide the result by 3
(arr5+arr6)/3

array([2., 4., 6., 8.])

In [16]:
arr8 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr9 = np.array([10, 20, 30])

print("Array 1 (2x3):")
print(arr8)
print("\nArray 2 (3,):")
print(arr9)

Array 1 (2x3):
[[1 2 3]
 [4 5 6]]

Array 2 (3,):
[10 20 30]


In [17]:
# Add arr9 to each row of arr8
arr10 = arr8+arr9
arr10

array([[11, 22, 33],
       [14, 25, 36]])

In [18]:
arr10.shape

(2, 3)

In [19]:
arr11 = np.array([[1],
                 [2],
                 [3]])

arr12 = np.array([10, 20, 30, 40])

print("Array 11 (3x1):")
print(arr11)
print("\nArray 12 (4,):")
print(arr12)

Array 11 (3x1):
[[1]
 [2]
 [3]]

Array 12 (4,):
[10 20 30 40]


In [20]:
# Add these two arrays
arr13 = arr11+arr12
arr13

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43]])

In [21]:
arr13.shape

(3, 4)

In [22]:
arr14 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

arr15 = np.array([[10, 20]])

print("Array 1 (3x2):")
print(arr14)
print("\nArray 2 (1x2):")
print(arr15)

Array 1 (3x2):
[[1 2]
 [3 4]
 [5 6]]

Array 2 (1x2):
[[10 20]]


In [23]:
# Subtract arr15 from arr14
arr16 = arr14-arr15
arr16

array([[ -9, -18],
       [ -7, -16],
       [ -5, -14]])

In [24]:
arr16.shape

(3, 2)

In [25]:
# multiply arr14 by arr15
arr17 = arr14*arr15
arr17

array([[ 10,  40],
       [ 30,  80],
       [ 50, 120]])

In [26]:
arr17.shape

(3, 2)

In [27]:
arr18 = np.array([10, 20, 30, 40, 50])
arr18

array([10, 20, 30, 40, 50])

In [28]:
# Multiply all elements by 5
arr19 = arr18*5
print("multiply 5:", arr19)

# Add 100 to the result
arr20 = arr19+100
print("add 100:", arr20)

# Divide the result by 2
arr21 = arr20/2
print('divide 2:', arr21)

multiply 5: [ 50 100 150 200 250]
add 100: [150 200 250 300 350]
divide 2: [ 75. 100. 125. 150. 175.]


In [29]:
arr22 = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])

print("Original array:")
print(arr22)

Original array:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [30]:
# Subtract 10 from all elements
arr23 = arr22-10
print('subtract 10:', arr23)

# Multiply the result by 3
arr24 = arr23*3
print('multiply 3:', arr24)

# Raise each element to level 2
arr25 = arr24**2
print("raise level2:", arr25)

subtract 10: [[-5  0  5]
 [10 15 20]
 [25 30 35]]
multiply 3: [[-15   0  15]
 [ 30  45  60]
 [ 75  90 105]]
raise level2: [[  225     0   225]
 [  900  2025  3600]
 [ 5625  8100 11025]]


In [32]:
prices = np.array([100, 200, 150, 300, 250])

print("Original prices:", prices)
discount_percent = 15

per_prices = prices - (discount_percent/100)
print('percent prices :', per_prices)

Original prices: [100 200 150 300 250]
percent prices : [ 99.85 199.85 149.85 299.85 249.85]


In [33]:
arr26 = np.array([[10, 20, 30]])
arr27 = np.array([[1],
                 [2],
                 [3]])

print("Array 26 (1x3):")
print(arr26)
print("\nArray 27 (3x1):")
print(arr27)

Array 26 (1x3):
[[10 20 30]]

Array 27 (3x1):
[[1]
 [2]
 [3]]


In [34]:
# Multiply these two arrays
arr28 = arr26*arr27
print(arr28)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [35]:
print(arr28.shape)

(3, 3)


In [36]:
# Find the largest and smallest values ​​in the result
print('min :', np.min(arr28))
print("max :", np.max(arr28))

min : 10
max : 90


In [37]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

row_multiplier = np.array([[2],
                           [3],
                           [4]])

print("Matrix (3x4):")
print(matrix)
print("\nRow multiplier (3x1):")
print(row_multiplier)

Matrix (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Row multiplier (3x1):
[[2]
 [3]
 [4]]


In [39]:
# Multiply each row of the matrix by the appropriate multiplier
np.multiply(matrix, row_multiplier)

array([[ 2,  4,  6,  8],
       [15, 18, 21, 24],
       [36, 40, 44, 48]])

In [40]:
arr29 = np.array([[10, 20, 30],
                [40, 50, 60]])

col_adder = np.array([5, 10, 15])

print("Array (2x3):")
print(arr29)
print("\nColumn adder (3,):")
print(col_adder)

Array (2x3):
[[10 20 30]
 [40 50 60]]

Column adder (3,):
[ 5 10 15]


In [42]:
# Add the appropriate value to each column of the array
arr29_add = arr29+col_adder
arr29_add

array([[15, 30, 45],
       [45, 60, 75]])

In [43]:
# Calculate the sum of each row of the resulting array
np.sum(arr29_add, axis=1)

array([ 90, 180])

In [44]:
temperatures_celsius = np.array([0, 10, 20, 30, 40, 100])

print("Temperatures (Celsius):", temperatures_celsius)

Temperatures (Celsius): [  0  10  20  30  40 100]


In [45]:
# Convert Celsius to Fahrenheit
fahren = temperatures_celsius*9/5 + 32
print(fahren)

[ 32.  50.  68.  86. 104. 212.]
