<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/04_05_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#####**broadcasting**

In [1]:
import numpy as np

In [2]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([2, 4, 6, 8, 10])
print("Array 1:", arr1)
print("Array 2:", arr2)

Array 1: [10 20 30 40 50]
Array 2: [ 2  4  6  8 10]


In [3]:
# Add two arrays element by element
arr1+arr2

array([12, 24, 36, 48, 60])

In [4]:
# Multiply two arrays element by element
arr1*arr2

array([ 20,  80, 180, 320, 500])

In [5]:
# Subtract arr2 from arr1 element by element
arr1-arr2

array([ 8, 16, 24, 32, 40])

In [6]:
# Divide arr1 into arr2 element by element
arr1/arr2

array([5., 5., 5., 5., 5.])

In [7]:
arr3 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr4 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

In [9]:
print("Array 1:")
print(arr3)
print("\nArray 2:")
print(arr4)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [10]:
# Add two matrices element by element
arr3+arr4

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [11]:
# Multiply two matrices element by element
arr3*arr4

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [13]:
# Divide each element of arr3 by the corresponding element of arr4
arr3/arr4

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [14]:
arr5 = np.array([5, 10, 15, 20])
arr6 = np.array([1, 2, 3, 4])

print("Array 1:", arr5)
print("Array 2:", arr6)

Array 1: [ 5 10 15 20]
Array 2: [1 2 3 4]


In [16]:
# Multiply two arrays element by element
arr7 = arr5*arr6
arr7

array([ 5, 20, 45, 80])

In [17]:
# Raise each element in the result by 2 (square it)
arr7**2

array([  25,  400, 2025, 6400])

In [18]:
# Add each element of arr5 with the corresponding element of arr6 and divide the result by 3
(arr5+arr6)/3

array([2., 4., 6., 8.])

In [19]:
arr8 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr9 = np.array([10, 20, 30])

print("Array 1 (2x3):")
print(arr8)
print("\nArray 2 (3,):")
print(arr9)

Array 1 (2x3):
[[1 2 3]
 [4 5 6]]

Array 2 (3,):
[10 20 30]


In [21]:
# Add arr9 to each row of arr8
arr10 = arr8+arr9
arr10

array([[11, 22, 33],
       [14, 25, 36]])

In [22]:
arr10.shape

(2, 3)

In [23]:
arr11 = np.array([[1],
                 [2],
                 [3]])

arr12 = np.array([10, 20, 30, 40])

print("Array 11 (3x1):")
print(arr11)
print("\nArray 12 (4,):")
print(arr12)

Array 11 (3x1):
[[1]
 [2]
 [3]]

Array 12 (4,):
[10 20 30 40]
