<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/06_05_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print("Original array:", arr)

Original array: [1 2 3 4 5]


In [3]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [4]:
arr2 = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

print("Original array:")
print(arr2)

Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# Raise each element to a level based on e
arr2_log = np.log(arr2)
arr2_log

/tmp/ipykernel_5363/1694645289.py:2: RuntimeWarning: divide by zero encountered in log
  arr2_log = np.log(arr2)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154]])

In [8]:
# Find the largest and smallest values ​​in the result
print('max :', np.max(arr2_log))
print("min :", np.min(arr2_log))

max : 2.0794415416798357
min : -inf


In [9]:
# Calculate the sum of all elements
print("sum :", np.sum(arr2_log))

sum : -inf


In [10]:
arr3 = np.array([1, 10, 100, 1000, 10000])

print("Original array:", arr3)

Original array: [    1    10   100  1000 10000]
