<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/2026_04_22_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create an array of size 4x6, all elements of which are 7.5
arr1 = np.full((4, 6), 7.5)
arr1

array([[7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5]])

In [3]:
# Extract the shape and data type of the array
print("shape :", arr1.shape)
print("dtype :", arr1.dtype)

shape : (4, 6)
dtype : float64


In [4]:
# Create an array of size 5x5, all elements of which are 3.14, and of data type int32
arr2 = np.full((5, 5), 3.14, dtype=np.int32)
arr2

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=int32)

In [5]:
# Output the total number of elements and size (in bytes) of an array
print("elements :", arr2.size)
print("bytes :", arr2.nbytes)

elements : 25
bytes : 100


In [6]:
# Create a 6x6 unit matrix
arr3 = np.eye(6, 6)
arr3

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [7]:
# Calculate the sum of diagonal elements
arr3.diagonal().sum()

np.float64(6.0)

In [8]:
# Calculate the sum of all non-diagonal elements
np.sum(arr3) - np.trace(arr3)

np.float64(0.0)

In [9]:
# Create an 8x8 unit matrix
arr4 = np.eye(8, 8)
arr4

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
# Multiply the matrix by 5
arr4 = arr4*5
arr4

array([[5., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0.],
       [0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 0., 0., 5.]])

In [11]:
# Change diagonal elements to 0

# copy from original array
arr4_diag = arr4.copy()

# get indices of diagonal values
diag_idx = np.diag_indices(arr4_diag.shape[0])
diag_idx

(array([0, 1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 5, 6, 7]))

In [12]:
arr4_diag[diag_idx] = 0

In [13]:
arr4_diag

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
# Generate 21 evenly distributed numbers in the range 0 to 10
arr5 = np.linspace(0, 10, 21)
arr5

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [18]:
# Check the difference between every two adjacent elements in an array
np.diff(arr5)

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [19]:
# Generate 11 evenly distributed numbers in the range 0 to 100
arr6 = np.linspace(0, 100, 11)
arr6

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [23]:
print("first el :", arr6[0])
print("median :", np.median(arr6))
print("last el :", arr6[-1])

first el : 0.0
median : 50.0
last el : 100.0


In [24]:
arr7 = np.array([1, 2, 3, 4, 5])
arr8 = np.array([1.5, 2.5, 3.5, 4.5, 5.5])
arr9 = np.array([True, False, True, False, True])

print("Array 1:", arr7)
print("Array 2:", arr8)
print("Array 3:", arr9)

Array 1: [1 2 3 4 5]
Array 2: [1.5 2.5 3.5 4.5 5.5]
Array 3: [ True False  True False  True]


In [25]:
# Extract the data type of each array
print("first arr :", arr7.dtype)
print("second arr :", arr8.dtype)
print("third arr :", arr9.dtype)

first arr : int64
second arr : float64
third arr : bool


In [26]:
new_arr8 = arr8.copy()
new_arr8

array([1.5, 2.5, 3.5, 4.5, 5.5])

In [27]:
# Convert arr2 to int64 type and show the result
new_arr8 = new_arr8.astype(np.int64)
new_arr8

array([1, 2, 3, 4, 5])

In [28]:
# convert arr3 to type int32
new_arr9 = arr9.copy()

new_arr9 = new_arr9.astype(np.int32)
new_arr9

array([1, 0, 1, 0, 1], dtype=int32)

In [29]:
# Create arrays from this list in the following data types :int8, 32/ float16,64
data = [10, 20, 30, 40, 50]

arr10 = np.array(data, dtype=np.int8)
arr11 = np.array(data, dtype=np.int32)
arr12 = np.array(data, dtype=np.float16)
arr13 = np.array(data, dtype=np.float64)
print(arr10)

[10 20 30 40 50]


In [30]:
arr11

array([10, 20, 30, 40, 50], dtype=int32)

In [31]:
arr12

array([10., 20., 30., 40., 50.], dtype=float16)

In [32]:
arr13

array([10., 20., 30., 40., 50.])