<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/2026_04_22_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
# Create an array of size 4x6, all elements of which are 7.5
arr1 = np.full((4, 6), 7.5)
arr1

array([[7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5]])

In [5]:
# Extract the shape and data type of the array
print("shape :", arr1.shape)
print("dtype :", arr1.dtype)

shape : (4, 6)
dtype : float64


In [6]:
# Create an array of size 5x5, all elements of which are 3.14, and of data type int32
arr2 = np.full((5, 5), 3.14, dtype=np.int32)
arr2

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=int32)

In [7]:
# Output the total number of elements and size (in bytes) of an array
print("elements :", arr2.size)
print("bytes :", arr2.nbytes)

elements : 25
bytes : 100


In [10]:
# Create a 6x6 unit matrix
arr3 = np.eye(6, 6)
arr3

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [14]:
# Calculate the sum of diagonal elements
arr3.diagonal().sum()

np.float64(6.0)

In [18]:
# Calculate the sum of all non-diagonal elements
np.sum(arr3) - np.trace(arr3)

np.float64(0.0)

In [20]:
# Create an 8x8 unit matrix
arr4 = np.eye(8, 8)
arr4

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
# Multiply the matrix by 5
arr4 = arr4*5
arr4

array([[5., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0.],
       [0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 0., 0., 5.]])

In [42]:
# Change diagonal elements to 0

# copy from original array
arr4_diag = arr4.copy()

# get indices of diagonal values
diag_idx = np.diag_indices(arr4_diag.shape[0])
diag_idx

(array([0, 1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 5, 6, 7]))

In [43]:
arr4_diag[diag_idx] = 0

In [45]:
arr4_diag

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])