<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/2026_04_22_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create an array of size 4x6, all elements of which are 7.5
arr1 = np.full((4, 6), 7.5)
arr1

array([[7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5]])

In [3]:
# Extract the shape and data type of the array
print("shape :", arr1.shape)
print("dtype :", arr1.dtype)

shape : (4, 6)
dtype : float64


In [4]:
# Create an array of size 5x5, all elements of which are 3.14, and of data type int32
arr2 = np.full((5, 5), 3.14, dtype=np.int32)
arr2

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=int32)

In [5]:
# Output the total number of elements and size (in bytes) of an array
print("elements :", arr2.size)
print("bytes :", arr2.nbytes)

elements : 25
bytes : 100


In [6]:
# Create a 6x6 unit matrix
arr3 = np.eye(6, 6)
arr3

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [7]:
# Calculate the sum of diagonal elements
arr3.diagonal().sum()

np.float64(6.0)

In [8]:
# Calculate the sum of all non-diagonal elements
np.sum(arr3) - np.trace(arr3)

np.float64(0.0)

In [9]:
# Create an 8x8 unit matrix
arr4 = np.eye(8, 8)
arr4

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
# Multiply the matrix by 5
arr4 = arr4*5
arr4

array([[5., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0.],
       [0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 0., 0., 5.]])

In [11]:
# Change diagonal elements to 0

# copy from original array
arr4_diag = arr4.copy()

# get indices of diagonal values
diag_idx = np.diag_indices(arr4_diag.shape[0])
diag_idx

(array([0, 1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 5, 6, 7]))

In [12]:
arr4_diag[diag_idx] = 0

In [13]:
arr4_diag

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
# Generate 21 evenly distributed numbers in the range 0 to 10
arr5 = np.linspace(0, 10, 21)
arr5

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [15]:
# Check the difference between every two adjacent elements in an array
np.diff(arr5)

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [16]:
# Generate 11 evenly distributed numbers in the range 0 to 100
arr6 = np.linspace(0, 100, 11)
arr6

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [17]:
print("first el :", arr6[0])
print("median :", np.median(arr6))
print("last el :", arr6[-1])

first el : 0.0
median : 50.0
last el : 100.0


In [18]:
arr7 = np.array([1, 2, 3, 4, 5])
arr8 = np.array([1.5, 2.5, 3.5, 4.5, 5.5])
arr9 = np.array([True, False, True, False, True])

print("Array 1:", arr7)
print("Array 2:", arr8)
print("Array 3:", arr9)

Array 1: [1 2 3 4 5]
Array 2: [1.5 2.5 3.5 4.5 5.5]
Array 3: [ True False  True False  True]


In [19]:
# Extract the data type of each array
print("first arr :", arr7.dtype)
print("second arr :", arr8.dtype)
print("third arr :", arr9.dtype)

first arr : int64
second arr : float64
third arr : bool


In [20]:
new_arr8 = arr8.copy()
new_arr8

array([1.5, 2.5, 3.5, 4.5, 5.5])

In [21]:
# Convert arr2 to int64 type and show the result
new_arr8 = new_arr8.astype(np.int64)
new_arr8

array([1, 2, 3, 4, 5])

In [22]:
# convert arr3 to type int32
new_arr9 = arr9.copy()

new_arr9 = new_arr9.astype(np.int32)
new_arr9

array([1, 0, 1, 0, 1], dtype=int32)

In [23]:
# Create arrays from this list in the following data types :int8, 32/ float16,64
data = [10, 20, 30, 40, 50]

arr10 = np.array(data, dtype=np.int8)
arr11 = np.array(data, dtype=np.int32)
arr12 = np.array(data, dtype=np.float16)
arr13 = np.array(data, dtype=np.float64)
print(arr10)

[10 20 30 40 50]


In [30]:
arr10.nbytes

5

In [27]:
arr11.nbytes

20

In [28]:
arr12.nbytes

10

In [29]:
arr13.nbytes

40

In [31]:
arr14 = np.array([1.1, 2.7, 3.9, 4.2, 5.8])

print("Original array:", arr14)
print("Original dtype:", arr14.dtype)

Original array: [1.1 2.7 3.9 4.2 5.8]
Original dtype: float64


In [32]:
# Convert the array to int32 type
arr14 = arr14.astype(np.int32)
print(arr14)
print("dtype :", arr14.dtype)

[1 2 3 4 5]
dtype : int32


In [33]:
# Convert the array to uint8 type
arr14 = arr14.astype(np.uint8)
print(arr14)
print("dtype :", arr14.dtype)

[1 2 3 4 5]
dtype : uint8


####**array size management**

In [34]:
arr = np.arange(1, 21)

print("Original array:", arr)
print("Shape:", arr.shape)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape: (20,)


In [36]:
# Make this array 4x5
arr.reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [37]:
# Make it 5x4
arr.reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [39]:
# Make it into a 2x2x5 shape
arr.reshape(2, 2, 5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [40]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

print("Original array:", arr2)
print("Shape:", arr2.shape)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
Shape: (18,)


In [43]:
# Make this array 3x6
arr2 = arr2.reshape(3, 6)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [45]:
# output the element in row 2, column 4
arr2[1, 3]

np.int64(10)

In [47]:
# Convert the array to a 2x3x3 shape
arr2 = arr2.reshape(2, 3, 3)
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
# Extract the element at position [1, 2, 1] in the new form
arr2[1][2, 1]

np.int64(17)

In [49]:
arr3 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Original array:")
print(arr3)
print("Shape:", arr3.shape)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [52]:
# Convert this array to a one-dimensional array
arr3 = arr3.flatten()
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
arr3.shape

(12,)

In [55]:
# Find the 5th element (index 4)
arr3[4]

np.int64(5)

In [56]:
arr4 = np.array([[[1, 2], [3, 4], [5, 6]],
                [[7, 8], [9, 10], [11, 12]]])

print("Original array:")
print(arr4)
print("Shape:", arr4.shape)

Original array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Shape: (2, 3, 2)


In [59]:
# Convert this 3D array to a one-dimensional array
arr4 = arr4.flatten()
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
# How many elements are there in the result?
arr4.size

12

In [62]:
# Change the array back to 4x3 shape
arr4 = arr4.reshape(4, 3)
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
arr5 = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Original array:")
print(arr5)
print("Shape:", arr5.shape)

Original array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape: (3, 3)


In [65]:
# Convert this array to a one-dimensional array (without making a copy)
arr5 = arr5.ravel()
arr5

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
# Change the 3rd element in the resulting array to 999
arr5[2] = 999
arr5

array([ 10,  20, 999,  40,  50,  60,  70,  80,  90])

In [70]:
arr6 = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print("Original array:")
print(arr6)
print("Shape:", arr6.shape)

Original array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)


In [71]:
# Convert this array to a one-dimensional array (without making a copy)
new_arr6 = arr6.ravel()
new_arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
# Replace the element at position [0, 2] of the original array
arr6[0, 2] = -11
arr6

array([[  1,   2, -11,   4,   5],
       [  6,   7,   8,   9,  10]])

In [74]:
new_arr6

array([  1,   2, -11,   4,   5,   6,   7,   8,   9,  10])

In [75]:
arr7 = np.array([1, 2, 3, 4, 5])

print("Original array:", arr7)
print("Shape:", arr7.shape)

Original array: [1 2 3 4 5]
Shape: (5,)


In [81]:
# Add one new dimension to this array, making it (1, 5)
new_arr7 = np.expand_dims(arr7, axis=0)
new_arr7.shape

(1, 5)

In [84]:
# Add a new dimension to the end so that it becomes (1, 5, 1)
new_arr7 = arr7.reshape(1, 5, 1)
new_arr7.shape

(1, 5, 1)