<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/2026_04_22_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create an array of size 4x6, all elements of which are 7.5
arr1 = np.full((4, 6), 7.5)
arr1

array([[7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5]])

In [3]:
# Extract the shape and data type of the array
print("shape :", arr1.shape)
print("dtype :", arr1.dtype)

shape : (4, 6)
dtype : float64


In [4]:
# Create an array of size 5x5, all elements of which are 3.14, and of data type int32
arr2 = np.full((5, 5), 3.14, dtype=np.int32)
arr2

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=int32)

In [5]:
# Output the total number of elements and size (in bytes) of an array
print("elements :", arr2.size)
print("bytes :", arr2.nbytes)

elements : 25
bytes : 100


In [6]:
# Create a 6x6 unit matrix
arr3 = np.eye(6, 6)
arr3

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [7]:
# Calculate the sum of diagonal elements
arr3.diagonal().sum()

np.float64(6.0)

In [8]:
# Calculate the sum of all non-diagonal elements
np.sum(arr3) - np.trace(arr3)

np.float64(0.0)

In [9]:
# Create an 8x8 unit matrix
arr4 = np.eye(8, 8)
arr4

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
# Multiply the matrix by 5
arr4 = arr4*5
arr4

array([[5., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0.],
       [0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 0., 0., 5.]])

In [11]:
# Change diagonal elements to 0

# copy from original array
arr4_diag = arr4.copy()

# get indices of diagonal values
diag_idx = np.diag_indices(arr4_diag.shape[0])
diag_idx

(array([0, 1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 5, 6, 7]))

In [12]:
arr4_diag[diag_idx] = 0

In [13]:
arr4_diag

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
# Generate 21 evenly distributed numbers in the range 0 to 10
arr5 = np.linspace(0, 10, 21)
arr5

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [15]:
# Check the difference between every two adjacent elements in an array
np.diff(arr5)

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [16]:
# Generate 11 evenly distributed numbers in the range 0 to 100
arr6 = np.linspace(0, 100, 11)
arr6

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [17]:
print("first el :", arr6[0])
print("median :", np.median(arr6))
print("last el :", arr6[-1])

first el : 0.0
median : 50.0
last el : 100.0


In [18]:
arr7 = np.array([1, 2, 3, 4, 5])
arr8 = np.array([1.5, 2.5, 3.5, 4.5, 5.5])
arr9 = np.array([True, False, True, False, True])

print("Array 1:", arr7)
print("Array 2:", arr8)
print("Array 3:", arr9)

Array 1: [1 2 3 4 5]
Array 2: [1.5 2.5 3.5 4.5 5.5]
Array 3: [ True False  True False  True]


In [19]:
# Extract the data type of each array
print("first arr :", arr7.dtype)
print("second arr :", arr8.dtype)
print("third arr :", arr9.dtype)

first arr : int64
second arr : float64
third arr : bool


In [20]:
new_arr8 = arr8.copy()
new_arr8

array([1.5, 2.5, 3.5, 4.5, 5.5])

In [21]:
# Convert arr2 to int64 type and show the result
new_arr8 = new_arr8.astype(np.int64)
new_arr8

array([1, 2, 3, 4, 5])

In [22]:
# convert arr3 to type int32
new_arr9 = arr9.copy()

new_arr9 = new_arr9.astype(np.int32)
new_arr9

array([1, 0, 1, 0, 1], dtype=int32)

In [23]:
# Create arrays from this list in the following data types :int8, 32/ float16,64
data = [10, 20, 30, 40, 50]

arr10 = np.array(data, dtype=np.int8)
arr11 = np.array(data, dtype=np.int32)
arr12 = np.array(data, dtype=np.float16)
arr13 = np.array(data, dtype=np.float64)
print(arr10)

[10 20 30 40 50]


In [24]:
arr10.nbytes

5

In [25]:
arr11.nbytes

20

In [26]:
arr12.nbytes

10

In [27]:
arr13.nbytes

40

In [28]:
arr14 = np.array([1.1, 2.7, 3.9, 4.2, 5.8])

print("Original array:", arr14)
print("Original dtype:", arr14.dtype)

Original array: [1.1 2.7 3.9 4.2 5.8]
Original dtype: float64


In [29]:
# Convert the array to int32 type
arr14 = arr14.astype(np.int32)
print(arr14)
print("dtype :", arr14.dtype)

[1 2 3 4 5]
dtype : int32


In [30]:
# Convert the array to uint8 type
arr14 = arr14.astype(np.uint8)
print(arr14)
print("dtype :", arr14.dtype)

[1 2 3 4 5]
dtype : uint8


####**array size management**

In [31]:
arr = np.arange(1, 21)

print("Original array:", arr)
print("Shape:", arr.shape)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape: (20,)


In [32]:
# Make this array 4x5
arr.reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [33]:
# Make it 5x4
arr.reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [34]:
# Make it into a 2x2x5 shape
arr.reshape(2, 2, 5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [35]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

print("Original array:", arr2)
print("Shape:", arr2.shape)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
Shape: (18,)


In [36]:
# Make this array 3x6
arr2 = arr2.reshape(3, 6)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [37]:
# output the element in row 2, column 4
arr2[1, 3]

np.int64(10)

In [38]:
# Convert the array to a 2x3x3 shape
arr2 = arr2.reshape(2, 3, 3)
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [39]:
# Extract the element at position [1, 2, 1] in the new form
arr2[1][2, 1]

np.int64(17)

In [40]:
arr3 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Original array:")
print(arr3)
print("Shape:", arr3.shape)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [41]:
# Convert this array to a one-dimensional array
arr3 = arr3.flatten()
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr3.shape

(12,)

In [43]:
# Find the 5th element (index 4)
arr3[4]

np.int64(5)

In [44]:
arr4 = np.array([[[1, 2], [3, 4], [5, 6]],
                [[7, 8], [9, 10], [11, 12]]])

print("Original array:")
print(arr4)
print("Shape:", arr4.shape)

Original array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Shape: (2, 3, 2)


In [45]:
# Convert this 3D array to a one-dimensional array
arr4 = arr4.flatten()
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
# How many elements are there in the result?
arr4.size

12

In [47]:
# Change the array back to 4x3 shape
arr4 = arr4.reshape(4, 3)
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
arr5 = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Original array:")
print(arr5)
print("Shape:", arr5.shape)

Original array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape: (3, 3)


In [49]:
# Convert this array to a one-dimensional array (without making a copy)
arr5 = arr5.ravel()
arr5

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
# Change the 3rd element in the resulting array to 999
arr5[2] = 999
arr5

array([ 10,  20, 999,  40,  50,  60,  70,  80,  90])

In [51]:
arr6 = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print("Original array:")
print(arr6)
print("Shape:", arr6.shape)

Original array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)


In [52]:
# Convert this array to a one-dimensional array (without making a copy)
new_arr6 = arr6.ravel()
new_arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
# Replace the element at position [0, 2] of the original array
arr6[0, 2] = -11
arr6

array([[  1,   2, -11,   4,   5],
       [  6,   7,   8,   9,  10]])

In [54]:
new_arr6

array([  1,   2, -11,   4,   5,   6,   7,   8,   9,  10])

In [55]:
arr7 = np.array([1, 2, 3, 4, 5])

print("Original array:", arr7)
print("Shape:", arr7.shape)

Original array: [1 2 3 4 5]
Shape: (5,)


In [56]:
# Add one new dimension to this array, making it (1, 5)
new_arr7 = np.expand_dims(arr7, axis=0)
new_arr7.shape

(1, 5)

In [57]:
# Add a new dimension to the end so that it becomes (1, 5, 1)
new_arr7 = np.expand_dims(new_arr7, axis=-1)
new_arr7.shape

(1, 5, 1)

In [58]:
arr8 = np.array([[10, 20, 30]])

print("Original array:")
print(arr8)
print("Shape:", arr8.shape)

Original array:
[[10 20 30]]
Shape: (1, 3)


In [59]:
# Add a new dimension before dimension 0 of this array
new_arr8 = np.expand_dims(arr8, axis=0)
new_arr8.shape

(1, 1, 3)

In [60]:
# Add a new dimension to the 2nd position (end)
new_arr8_2 = np.expand_dims(new_arr8, axis=-1)
new_arr8_2.shape

(1, 1, 3, 1)

In [61]:
arr9 = np.array([[[[[10]]]]])

print("Original array:")
print(arr9)
print("Shape:", arr9.shape)

Original array:
[[[[[10]]]]]
Shape: (1, 1, 1, 1, 1)


In [62]:
# Remove all unnecessary dimensions (those with size 1) from this array
new_arr9 = np.squeeze(arr9)
new_arr9

array(10)

In [63]:
arr10 = np.array([[[[1, 2, 3]]]])

print("Original array:")
print(arr10)
print("Shape:", arr10.shape)

Original array:
[[[[1 2 3]]]]
Shape: (1, 1, 1, 3)


In [64]:
# Remove all unnecessary dimensions from this array
new_arr10 = np.squeeze(arr10)
new_arr10.shape

(3,)

In [65]:
new_arr10

array([1, 2, 3])

In [66]:
arr11 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Original array:")
print(arr11)
print("Shape:", arr11.shape)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [67]:
# Convert the rows of this matrix into columns and the columns into rows
new_arr11 = arr11.transpose()
new_arr11

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [68]:
new_arr11.shape

(4, 3)

In [69]:
# Find the element at position [2, 1] in the new matrix
new_arr11[2, 1]

np.int64(7)

In [70]:
arr12 = np.array([[[1, 2, 3],
                 [4, 5, 6]],

                [[7, 8, 9],
                 [10, 11, 12]]])

print("Original array:")
print(arr12)
print("Shape:", arr12.shape)

Original array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)


In [71]:
# Swap the 0th and 2nd dimensions of this array
new_arr12 = arr12.swapaxes(0, 2)
new_arr12

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [72]:
new_arr12.shape

(3, 2, 2)

In [73]:
arr13 = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("Original array:")
print(arr13)
print("Shape:", arr13.shape)

Original array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Shape: (3, 4)


In [74]:
# Find the transpose of this matrix
new_arr13 = arr13.T
new_arr13

array([[ 10,  50,  90],
       [ 20,  60, 100],
       [ 30,  70, 110],
       [ 40,  80, 120]])

In [75]:
# Find the element at position [1, 2] in the transpose
new_arr13[1, 2]

np.int64(100)

In [76]:
# Compare the forms of the original and transpose matrices
print("real arr shape :", arr13.shape)
print("transpose arr shape :", new_arr13.shape)

real arr shape : (3, 4)
transpose arr shape : (4, 3)


In [77]:
arr14 = np.array([[1, 2],
                [3, 4],
                [5, 6],
                [7, 8]])

print("Original array:")
print(arr14)
print("Shape:", arr14.shape)

Original array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape: (4, 2)


In [78]:
# Find the transpose of this matrix
new_arr14 = arr14.T
new_arr14

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [79]:
new_arr14.shape

(2, 4)

In [80]:
# Find the diagonal elements in the transpose
np.diag(new_arr14)

array([1, 4])

In [81]:
new_arr14.T

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#####**indexing and slicing**

In [82]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Original array:", arr)

Original array: [ 10  20  30  40  50  60  70  80  90 100]


In [83]:
# Extract elements from index 2 to index 8
arr[2:8]

array([30, 40, 50, 60, 70, 80])

In [84]:
# Extract every 3rd element (0, 3, 6, 9)
arr[::3]

array([ 10,  40,  70, 100])

In [85]:
# Extract the last 5 elements
arr[-6:-1]

array([50, 60, 70, 80, 90])

In [86]:
# Output the array in reverse order
arr[::-1]

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [87]:
arr2 = np.arange(0, 51, 5)

print("Original array:", arr2)

Original array: [ 0  5 10 15 20 25 30 35 40 45 50]


In [88]:
# Extract elements from index 3 to the end
arr2[3:]

array([15, 20, 25, 30, 35, 40, 45, 50])

In [89]:
# Extract elements at even index
arr2[::2]

array([ 0, 10, 20, 30, 40, 50])

In [90]:
# Extract every 2nd element starting from index 1
arr2[1::2]

array([ 5, 15, 25, 35, 45])

In [91]:
# Extract every 3rd element from the end in reverse order
arr2[::-3]

array([50, 35, 20,  5])

In [92]:
arr3 = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100],
                [110, 120, 130, 140, 150],
                [160, 170, 180, 190, 200]])

print("Original array:")
print(arr3)

Original array:
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [93]:
# Separate rows 1 and 2
arr3[0:2, :]

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [94]:
# Separate rows 2 and 3
arr3[1:3, :]

array([[ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [95]:
# Separate rows 3 and 4
arr3[2:, :]

array([[110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [96]:
# Extract only the first and last columns from all rows
arr3[:, [0, -1]]

array([[ 10,  50],
       [ 60, 100],
       [110, 150],
       [160, 200]])

In [97]:
arr3

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [98]:
# Output the last two lines in reverse order
arr3[2:][::-1]

array([[160, 170, 180, 190, 200],
       [110, 120, 130, 140, 150]])

In [99]:
arr4 = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12],
                [13, 14, 15, 16, 17, 18],
                [19, 20, 21, 22, 23, 24]])

print("Original array:")
print(arr4)

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [100]:
# Separate the 2x3 subarray (from the middle)
new_arr4 = arr4[1:3, 1:4]
new_arr4

array([[ 8,  9, 10],
       [14, 15, 16]])

In [101]:
# Separate even rows and odd columns
arr4[::2, 1::3]

array([[ 2,  5],
       [14, 17]])

In [102]:
# Extract every second row and every third column
arr4[::2, ::3]

array([[ 1,  4],
       [13, 16]])

In [103]:
arr5 = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]],
                [[13, 14, 15], [16, 17, 18]]])

print("Original array:")
print(arr5)
print("Shape:", arr5.shape)

Original array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Shape: (3, 2, 3)


In [104]:
# Separate the first and last blocks
arr5[[0, -1], :, :]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [105]:
# Extract only the first line from each block
arr5[:, 1, :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [106]:
# Extract only the last element from each block, from each row
arr5[:, :, -1]

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [107]:
scores = np.array([45, 67, 89, 34, 78, 92, 56, 23, 88, 71])

print("Scores:", scores)

Scores: [45 67 89 34 78 92 56 23 88 71]


In [108]:
scores.size

10

In [109]:
# output all scores above 60
scores[scores>60]

array([67, 89, 78, 92, 88, 71])

In [110]:
# Find the scores between 50 and 80 (50 and 80 are inclusive)
scores[(scores>=50) & (scores<=80)]

array([67, 78, 56, 71])

In [111]:
# Change scores below 70 to 0
scores[scores<70] = 0

In [112]:
prices = np.array([1200, 450, 800, 350, 1500, 600, 2000, 300])

print("Prices:", prices)

Prices: [1200  450  800  350 1500  600 2000  300]


In [113]:
prices.size

8

In [114]:
# Find prices under 500
prices[prices<500]

array([450, 350, 300])

In [115]:
# Mark prices above 1000 as "Expensive" and the rest as "Affordable"
cond = prices>1_000
np.where(cond, 'expensive', 'affordable')

array(['expensive', 'affordable', 'affordable', 'affordable', 'expensive',
       'affordable', 'expensive', 'affordable'], dtype='<U10')

In [116]:
# Separate prices above 800 AND below 1500
prices[(prices>800) & (prices<1500)]

array([1200])

In [117]:
matrix = np.array([[12, 35, 8, 42],
                   [55, 18, 70, 23],
                   [9, 48, 15, 61],
                   [38, 22, 51, 17]])

print("Original matrix:")
print(matrix)

Original matrix:
[[12 35  8 42]
 [55 18 70 23]
 [ 9 48 15 61]
 [38 22 51 17]]


In [118]:
matrix.shape

(4, 4)

In [119]:
# Find all values ​​greater than 30
matrix[matrix>30]

array([35, 42, 55, 70, 48, 61, 38, 51])

In [120]:
# Find values ​​that are less than 20 AND even
matrix[(matrix<20) & (matrix%2==0)]

array([12,  8, 18])

In [121]:
# Change elements larger than diagonal elements to 100
matrix_diag = np.diag(matrix)
np.where(matrix>matrix_diag, 100, matrix)

array([[ 12, 100,   8, 100],
       [100,  18, 100, 100],
       [  9, 100,  15, 100],
       [100, 100, 100,  17]])

In [122]:
arr6 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

indices = [0, 2, 5, 8]

print("Original array:", arr6)
print("Indices:", indices)

Original array: [ 10  20  30  40  50  60  70  80  90 100]
Indices: [0, 2, 5, 8]


In [123]:
arr6.size

10

In [124]:
# Extract elements at given indices
new_arr6 = arr6[indices]
new_arr6

array([10, 30, 60, 90])

In [125]:
# Multiply these elements by 2
new_arr6*2

array([ 20,  60, 120, 180])

In [126]:
arr7 = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

row_indices = [0, 1, 3]
col_indices = [1, 3, 4]

print("Original array:")
print(arr7)

Original array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [127]:
arr7.shape

(4, 5)

In [128]:
# Extract the elements at the following positions: (0,1), (1,3), (3,4)
new_arr7 = arr7[row_indices, col_indices]
new_arr7

array([ 2,  9, 20])

In [129]:
# Calculate the sum of these elements
np.sum(new_arr7)

np.int64(31)

In [130]:
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

row_indices = [0, 0, 2, 2]
col_indices = [0, 2, 0, 2]

print("Original matrix:")
print(matrix)

Original matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [131]:
matrix.shape

(3, 3)

In [132]:
# Extract the corner elements with given indices
new_matrix = matrix[row_indices, col_indices]
new_matrix

array([10, 30, 70, 90])

In [133]:
# Convert the result to a 2x2 shape
new_matrix.reshape(2, 2)

array([[10, 30],
       [70, 90]])

In [134]:
numbers = np.array([15, 28, 42, 7, 35, 19, 50, 11, 33, 8])

print("Numbers:", numbers)

Numbers: [15 28 42  7 35 19 50 11 33  8]


In [135]:
numbers.size

10

In [136]:
# Change numbers greater than 20 to 100 and the rest to 0
new_numbers = np.where(numbers>20, 100, 0)
new_numbers

array([  0, 100, 100,   0, 100,   0, 100,   0, 100,   0])

In [137]:
temperatures = np.array([5, 15, 25, 35, 10, 30, 40, 8, 22, 38])

print("Temperatures:", temperatures)

Temperatures: [ 5 15 25 35 10 30 40  8 22 38]


In [138]:
temperatures.size

10

In [139]:
# Return 'Cold' if below 15, 'Moderate' if between 15-30, 'Hot' if above 30
cond2 = [
    temperatures < 15, # cold
    (temperatures >= 15) | (temperatures <= 30), # moderate
    temperatures > 30 # hot
]
choices = ['cold', 'moderate', 'hot']
result = np.select(cond2, choices, default='Unknown')
result

array(['cold', 'moderate', 'moderate', 'moderate', 'cold', 'moderate',
       'moderate', 'cold', 'moderate', 'moderate'], dtype='<U8')

In [140]:
ages = np.array([15, 22, 35, 8, 45, 17, 60, 12, 28, 50])

print("Ages:", ages)

Ages: [15 22 35  8 45 17 60 12 28 50]


In [141]:
ages.size

10

- Create a category based on age:
  - Under 18: 'Minor'
  - 18-30: 'Young Adult'
  - 31-50: 'Adult'
  - Over 50: 'Senior'

In [142]:
cond3 = [
    ages < 18, # minor
    (ages >= 18) & (ages <= 65), # young adult
    (ages >= 31) & (ages <= 50), # adult
    ages > 50 # senior
]
choices2 = ['minor', 'young adult', 'adult', 'senior']
result2 = np.select(cond3, choices2, default='Unknown')
result2

array(['minor', 'young adult', 'young adult', 'minor', 'young adult',
       'minor', 'young adult', 'minor', 'young adult', 'young adult'],
      dtype='<U11')

- Rate according to the scores:
  - 90 and above: 'A'
  - 80-89: 'B'
  - 70-79: 'C'
  - 60-69: 'D'
  - Below 60: 'F

In [143]:
scores = np.array([45, 67, 89, 34, 78, 92, 56, 23, 88, 71])

print("Scores:", scores)

Scores: [45 67 89 34 78 92 56 23 88 71]


In [144]:
scores.size

10

In [145]:
cond4 = [
    scores >= 90, # A
    (scores>=80) & (scores<=89), # B
    (scores>=70) & (scores<=79), # C
    (scores>=60) & (scores<=69), # D
    scores<60 # F
]
choices3 = ['A', 'B', 'C', 'D', 'F']
result3 = np.select(cond4, choices3, default='Unknown')
result3

array(['F', 'D', 'B', 'F', 'C', 'A', 'F', 'F', 'B', 'C'], dtype='<U7')

- Determine the level based on salary:
  - Below 5000: 'Junior'
  - 5000-10000: 'Middle'  
  - 10000-15000: 'Senior'
  - Above 15000: 'Lead'
  

In [146]:
salaries = np.array([3000, 5000, 7000, 10000, 15000, 2500, 8000, 12000])

print("Salaries:", salaries)

Salaries: [ 3000  5000  7000 10000 15000  2500  8000 12000]


In [147]:
cond5 = [
    salaries < 5000, # junior
    (salaries >= 5000) & (salaries <=10_000), # middle
    (salaries >= 10_000) & (salaries <= 15_000), # senior
    salaries > 15_000 # lead
]
choices4 = ['junior', 'middle', 'senior', 'lead']
result4 = np.select(cond5, choices4, default='Unknown')
result4

array(['junior', 'middle', 'middle', 'middle', 'senior', 'junior',
       'middle', 'senior'], dtype='<U7')

In [150]:
uniq_els, counts_el = np.unique(result4, return_counts=True)
print(uniq_els)
print(counts_el)

['junior' 'middle' 'senior']
[2 4 2]
