<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/agricultural_monitoring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
satellite_data = np.array([
    [120, 150, 110, 450], # Hudud 1: Zich o'rmon
    [180, 130, 120, 210], # Hudud 2: Qurigan yer/Bino
    [100, 200, 90,  500], # Hudud 3: Ekin maydoni
    [255, 255, 255, 10],  # Hudud 4: Bulut (Xato ma'lumot)
    [140, 160, 130, 400]  # Hudud 5: Bog'
], dtype=float)

# Hududlarning maydoni (kvadrat metrda)
area_sq_m = np.array([5000, 2000, 7500, 1000, 3000])

satellite_data

array([[120., 150., 110., 450.],
       [180., 130., 120., 210.],
       [100., 200.,  90., 500.],
       [255., 255., 255.,  10.],
       [140., 160., 130., 400.]])

`qizil` , `yashil` , `ko'k` , `yaqin infraqizil`

In [8]:
satellite_data.shape

(5, 4)

In [15]:
np.argmax(satellite_data[:, -1] < satellite_data[:, 0])

np.int64(3)

In [18]:
np.argmax(satellite_data[:, -1] < satellite_data[:, 0])

np.int64(3)

In [22]:
# # The NIR channel (column 4) should always be greater than the Red channel (column 1).
# Therefore, we delete the Red data that is greater than the NIR channel.
np.delete(satellite_data, 3, axis=0)
np.delete(area_sq_m, 3)

array([5000, 2000, 7500, 3000])

In [23]:
satellite_data

array([[120., 150., 110., 450.],
       [180., 130., 120., 210.],
       [100., 200.,  90., 500.],
       [255., 255., 255.,  10.],
       [140., 160., 130., 400.]])