<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/arithmetic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

This lesson teaches you how to add, subtract, multiply, and divide array elements in a simple way

**multiplication**

- multiplies by corresponding elements of two arrays

In [2]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 3, 2, 1])
print(arr1*arr2)

[4 6 6 4]


- the same rule for multiplication works for addition, subtraction, and division

In [5]:
arr3 = np.arange(10, 100, 10)
arr4 = np.arange(2, 20, 2)

# division
print(arr3/arr4)

# division 2
print(arr3//arr4)

[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5 5 5 5 5 5 5 5 5]


In [7]:
# addition
arr1+arr2

array([5, 5, 5, 5])

In [8]:
# substraction
arr3-arr4

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72])