<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/arithmetic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

This lesson teaches you how to add, subtract, multiply, and divide array elements in a simple way

**multiplication**

- multiplies by corresponding elements of two arrays

In [10]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 3, 2, 1])
print(arr1*arr2)

[4 6 6 4]


- the same rule for multiplication works for addition, subtraction, and division

In [11]:
arr3 = np.arange(10, 100, 10)
arr4 = np.arange(2, 20, 2)

# division
print(arr3/arr4)

# division 2
print(arr3//arr4)

[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5 5 5 5 5 5 5 5 5]


In [12]:
# addition
arr1+arr2

array([5, 5, 5, 5])

In [13]:
# substraction
arr3-arr4

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72])

**square or other powers of the array elements**

In [14]:
# squaring
arr2**2

array([16,  9,  4,  1])

In [15]:
# cube
arr2**3

array([64, 27,  8,  1])

In [16]:
# it is increased to other levels in the same way
arr2**5

array([1024,  243,   32,    1])