<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/arr_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### N1
**How create a simple array using the NumPy library? Give an example**


In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2.2, -3, 4, -5.5])
arr

array([ 1. ,  2.2, -3. ,  4. , -5.5])

#### N2
**What kind of array does the code np.zeros((2,3)) create?**

- creates an array of size 2x3 with all elements set to 0

###N3
**What does the following code return?**

`import numpy as np`

`arr = np.array([10, 20, 30, 40])`

`print(arr.shape)`

- specifies the number of rows and columns of the array in the variable arr

###N4
**What kind of array does the code np.arange(5, 20, 3) create ?**

- Creates a one-dimensional array with numbers from 5 to 20 in 3 steps

###N5
**What would be the possible result of the code**

`np.random.randint(1, 50, (3, 3))?`

- Creates a 3x3 array whose elements are random numbers between 1 and 50

###N6
**What is the response from the code below ?**

`arr = np.linspace(0, 10, 5)`

`print(arr)`

- Creates an array of 5 evenly distributed numbers from 0 to 10

###N7
**Reshape the given array into a 3x4 matrix using reshape**

`arr = np.arange(12)`

In [4]:
arr2 = np.arange(12).reshape(3, 4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

###N8
**Create a 4x4 array of randomly distributed numbers and round each element to 2 decimal places**

In [5]:
arr3 = np.random.rand(4, 4) # generates random numbers between 0 and 1
# integration
arr3 = np.round(arr3, 2)
arr3

array([[0.07, 0.55, 0.62, 0.53],
       [0.34, 0.32, 0.88, 0.81],
       [0.93, 0.84, 0.02, 0.55],
       [0.84, 0.94, 0.49, 0.43]])

###N9
**What will be the output of the following code and why ?**

`arr1 = np.array([1, 2, 3])`

`arr2 = np.array([4, 5])`

`result = np.concatenate((arr1, arr2))`

`print(result)`

- Two one-dimensional arrays are created (arr1 and arr2). concatenate combines them, because both arrays have the same size

###N10
**How do you create a NumPy array filled with ones? Provide an example**

In [6]:
arr4 = np.ones(5)
arr4

array([1., 1., 1., 1., 1.])

###N11
**What does the following code output?**

```
arr = np.full((2, 3), 7)
print(arr)
```

- creates an array of size 2x3 with all elements consisting of 7

###N12
**How can you create a NumPy array from a Python list [10, 20, 30, 40, 50]?**

In [13]:
lst = [10, 20, 30, 40, 50]
arr5 = np.array(lst)
arr5

array([10, 20, 30, 40, 50])

###N13
**What does the function np.identity(4) generate?**

- creates a 4x4 array with diagonal elements 1 and remaining elements 0

###N14
**How do you generate a 5x5 matrix of random integers between 10 and 100?**

In [14]:
arr6 = np.random.randint(10, 100, (5, 5))
arr6

array([[60, 13, 60, 71, 66],
       [86, 75, 24, 44, 39],
       [60, 27, 88, 65, 47],
       [86, 12, 40, 40, 34],
       [55, 69, 61, 84, 63]])

###N15
**What is the difference between np.zeros((3,3)) and np.empty((3,3))?**

- `zeros function` - creates a 3x3 array with all elements 0

  `empty function` - allocates empty space with random values

###N16
**Create a 3x3 matrix where all diagonal elements are 5, and the rest are zeros**

In [15]:
arr7 = np.eye(3)*5
arr7

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

###N17
**Generate a 4x4 NumPy array with random numbers between 0 and 1, then replace all values greater than 0.5 with 1 and others with 0**

In [17]:
arr8 = np.random.rand(4, 4)
arr8

array([[0.41345631, 0.02605144, 0.33984527, 0.89625913],
       [0.68740249, 0.86419914, 0.46908543, 0.11877545],
       [0.12343627, 0.60064166, 0.98405915, 0.73008133],
       [0.04941514, 0.24609203, 0.70213607, 0.32022285]])

In [18]:
arr8[arr8 > 0.5] = 1
arr8[arr8 < 0.5] = 0
arr8

array([[0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 1., 1.],
       [0., 0., 1., 0.]])

###N18
**Given the following array, reshape it into a 3D array with shape (2, 3, 2):**

`arr = np.arange(12)`

In [19]:
arr9 = np.arange(12).reshape(2, 3, 2)
arr9

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])