<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/bool_indx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**get required elements from an array by giving a condition**

In [2]:
arr = np.arange(10, 110, 10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [3]:
# getting elements greater than 40
large_num = arr > 40
large_num

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [4]:
arr[large_num]

array([ 50,  60,  70,  80,  90, 100])

In [5]:
# get all elements less than 50
small_num = arr < 50
small_num

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [6]:
arr[small_num]

array([10, 20, 30, 40])

**get the desired elements by giving two or more conditions**

In [13]:
# get elements less than 30 and greater than 70
bool1 = (arr < 30) | (arr > 70)
bool1

array([ True,  True, False, False, False, False, False,  True,  True,
        True])

In [14]:
arr[bool1]

array([ 10,  20,  80,  90, 100])

In [18]:
# get elements less than 50 and greater than 70
bool2 = (arr > 70) | (arr < 50)
arr[bool2]

array([ 10,  20,  30,  40,  80,  90, 100])

**changing unnecessary elements to other values ​​by giving a condition**

In [30]:
# copy from array arr
arr2 = arr.copy()
print(arr)
print(arr2)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]


In [31]:
arr2[arr % 3 ==0] = -1
arr2

array([ 10,  20,  -1,  40,  50,  -1,  70,  80,  -1, 100])

In [32]:
arr2[arr % 4 == 0] = -4
arr2

array([10, -4, -1, -4, 50, -4, 70, -4, -1, -4])