<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/climate_change.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
temperatures = np.array([
    15, 17, 22, 28, 33, 38, 40, 39, 34, 27, 20, 16, # Shahar A
    10, 12, 18, 24, 30, 35, 37, 36, 31, 23, 15, 11, # Shahar B
    25, 26, 28, 30, 32, 33, 34, 34, 33, 31, 28, 26  # Shahar C (Tropik)
])
temperatures.size

36

- View each city's data in a separate row

In [5]:
data = temperatures.reshape(3, 12)
data

array([[15, 17, 22, 28, 33, 38, 40, 39, 34, 27, 20, 16],
       [10, 12, 18, 24, 30, 35, 37, 36, 31, 23, 15, 11],
       [25, 26, 28, 30, 32, 33, 34, 34, 33, 31, 28, 26]])

- Temperatures above 35 degrees Celsius are considered "Abnormally hot" due to global warming
- Filter only temperatures above 35 degrees Celsius in City B (City 2)

In [7]:
data[data>35]

array([38, 40, 39, 37, 36])

In [17]:
city2_anomal = data[1][data[1]>35]
city2_anomal

array([37, 36])

- When analyzing the data for City B, it was found that there were a total of 2 cases where the temperature exceeded 35 degrees Celsius. This is the hottest time of the summer for that area

In [18]:
# convert temperature from Celsius to Fahrenheit
temps_f = data*1.8 + 32
temps_f

array([[ 59. ,  62.6,  71.6,  82.4,  91.4, 100.4, 104. , 102.2,  93.2,
         80.6,  68. ,  60.8],
       [ 50. ,  53.6,  64.4,  75.2,  86. ,  95. ,  98.6,  96.8,  87.8,
         73.4,  59. ,  51.8],
       [ 77. ,  78.8,  82.4,  86. ,  89.6,  91.4,  93.2,  93.2,  91.4,
         87.8,  82.4,  78.8]])

In [24]:
# determine the average summer temperature for each city
np.mean(temps_f[:, [5, 6, 7]], axis=1)

array([102.2,  96.8,  92.6])

In [26]:
# transpose each city to compare their temperatures
fahren = temps_f.T
fahren

array([[ 59. ,  50. ,  77. ],
       [ 62.6,  53.6,  78.8],
       [ 71.6,  64.4,  82.4],
       [ 82.4,  75.2,  86. ],
       [ 91.4,  86. ,  89.6],
       [100.4,  95. ,  91.4],
       [104. ,  98.6,  93.2],
       [102.2,  96.8,  93.2],
       [ 93.2,  87.8,  91.4],
       [ 80.6,  73.4,  87.8],
       [ 68. ,  59. ,  82.4],
       [ 60.8,  51.8,  78.8]])

In [30]:
# determining the hottest city in January
np.argmax(fahren[0, :])

np.int64(2)

In [31]:
# Temperatures are predicted to increase by 2% next year, generating data for next year
new_year_temp = temps_f*1.02
new_year_temp

array([[ 60.18 ,  63.852,  73.032,  84.048,  93.228, 102.408, 106.08 ,
        104.244,  95.064,  82.212,  69.36 ,  62.016],
       [ 51.   ,  54.672,  65.688,  76.704,  87.72 ,  96.9  , 100.572,
         98.736,  89.556,  74.868,  60.18 ,  52.836],
       [ 78.54 ,  80.376,  84.048,  87.72 ,  91.392,  93.228,  95.064,
         95.064,  93.228,  89.556,  84.048,  80.376]])