<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/e_commerce_store.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

- `[ID, Miqdor, Summa, Vaqt]`

In [2]:
data = np.array([
    [101, 5, 250, 15],
    [102, 1, 30, 2],
    [103, 12, 1200, 45],
    [104, 0, 0, 1],
    [105, 3, 150, 10],
    [106, 8, 600, 30],
    [107, 2, 40, 5],
    [108, 15, 2000, 60],
    [109, 1, 15, 1],
    [110, 4, 300, 20]
])

In [3]:
print(data)

[[ 101    5  250   15]
 [ 102    1   30    2]
 [ 103   12 1200   45]
 [ 104    0    0    1]
 [ 105    3  150   10]
 [ 106    8  600   30]
 [ 107    2   40    5]
 [ 108   15 2000   60]
 [ 109    1   15    1]
 [ 110    4  300   20]]


In [12]:
data[data < 1]

array([0, 0])