<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/e_commerce_store.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

- `[ID, Miqdor, Summa, Vaqt]`

In [2]:
data = np.array([
    [101, 5, 250, 15],
    [102, 1, 30, 2],
    [103, 12, 1200, 45],
    [104, 0, 0, 1],
    [105, 3, 150, 10],
    [106, 8, 600, 30],
    [107, 2, 40, 5],
    [108, 15, 2000, 60],
    [109, 1, 15, 1],
    [110, 4, 300, 20]
])

In [3]:
print(data)

[[ 101    5  250   15]
 [ 102    1   30    2]
 [ 103   12 1200   45]
 [ 104    0    0    1]
 [ 105    3  150   10]
 [ 106    8  600   30]
 [ 107    2   40    5]
 [ 108   15 2000   60]
 [ 109    1   15    1]
 [ 110    4  300   20]]


- Identify customers who visited the site but did not purchase anything and separate their data into a separate array

In [4]:
# number of products purchased
num_products = data[:, 1]
num_products

array([ 5,  1, 12,  0,  3,  8,  2, 15,  1,  4])

In [5]:
mask = num_products<1

In [6]:
customer_not_buy = data[mask]
customer_not_buy

array([[104,   0,   0,   1]])

In [7]:
# purchases
purchases = data[:, 2]
purchases

array([ 250,   30, 1200,    0,  150,  600,   40, 2000,   15,  300])

In [8]:
purchase_mean = np.mean(purchases)

np.where(purchases>purchase_mean, 'vip', 'classic')

array(['classic', 'classic', 'vip', 'classic', 'classic', 'vip',
       'classic', 'vip', 'classic', 'classic'], dtype='<U7')

In [9]:
purchase_log = np.log1p(purchases)
purchase_log

array([5.52545294, 3.4339872 , 7.09090982, 0.        , 5.01727984,
       6.39859493, 3.71357207, 7.60140233, 2.77258872, 5.70711026])

In [12]:
# add new column to array
new_data5col = np.column_stack((data, purchase_log))
new_data5col

array([[1.01000000e+02, 5.00000000e+00, 2.50000000e+02, 1.50000000e+01,
        5.52545294e+00],
       [1.02000000e+02, 1.00000000e+00, 3.00000000e+01, 2.00000000e+00,
        3.43398720e+00],
       [1.03000000e+02, 1.20000000e+01, 1.20000000e+03, 4.50000000e+01,
        7.09090982e+00],
       [1.04000000e+02, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [1.05000000e+02, 3.00000000e+00, 1.50000000e+02, 1.00000000e+01,
        5.01727984e+00],
       [1.06000000e+02, 8.00000000e+00, 6.00000000e+02, 3.00000000e+01,
        6.39859493e+00],
       [1.07000000e+02, 2.00000000e+00, 4.00000000e+01, 5.00000000e+00,
        3.71357207e+00],
       [1.08000000e+02, 1.50000000e+01, 2.00000000e+03, 6.00000000e+01,
        7.60140233e+00],
       [1.09000000e+02, 1.00000000e+00, 1.50000000e+01, 1.00000000e+00,
        2.77258872e+00],
       [1.10000000e+02, 4.00000000e+00, 3.00000000e+02, 2.00000000e+01,
        5.70711026e+00]])

In [21]:
# customers who spent less than 2 minutes on the site
time_mask = new_data5col[:, 3] < 2
time_mask

array([False, False, False,  True, False, False, False, False,  True,
       False])

In [24]:
clean_data = new_data5col[~time_mask]
clean_data

array([[1.01000000e+02, 5.00000000e+00, 2.50000000e+02, 1.50000000e+01,
        5.52545294e+00],
       [1.02000000e+02, 1.00000000e+00, 3.00000000e+01, 2.00000000e+00,
        3.43398720e+00],
       [1.03000000e+02, 1.20000000e+01, 1.20000000e+03, 4.50000000e+01,
        7.09090982e+00],
       [1.05000000e+02, 3.00000000e+00, 1.50000000e+02, 1.00000000e+01,
        5.01727984e+00],
       [1.06000000e+02, 8.00000000e+00, 6.00000000e+02, 3.00000000e+01,
        6.39859493e+00],
       [1.07000000e+02, 2.00000000e+00, 4.00000000e+01, 5.00000000e+00,
        3.71357207e+00],
       [1.08000000e+02, 1.50000000e+01, 2.00000000e+03, 6.00000000e+01,
        7.60140233e+00],
       [1.10000000e+02, 4.00000000e+00, 3.00000000e+02, 2.00000000e+01,
        5.70711026e+00]])