<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**When working with the numpy library, we can save various necessary arrays and variables to a file and use them later**

In [3]:
# Save an array to a file with save function
arr = np.arange(80, 100, 2)
np.save('even_nums', arr)

In [4]:
# read our saved file
arr_nums = np.load('even_nums.npy')
print(arr_nums)

[80 82 84 86 88 90 92 94 96 98]


In [5]:
# repetition
arr2 = np.random.rand(5)
arr2

array([0.53183609, 0.47746795, 0.66122838, 0.8735272 , 0.47971673])

In [6]:
np.save('random_nums', arr2)

In [7]:
arr2_nums = np.load('random_nums.npy')
print(arr2_nums)

[0.53183609 0.47746795 0.66122838 0.8735272  0.47971673]


**savez**

- stores multiple arrays or variables

In [8]:
# save the arrays arr and arr2 to a file
np.savez('two_arrs', a=arr, b=arr2)

In [9]:
# read from file
two_arrs = np.load('two_arrs.npz')

In [11]:
# arr
two_arrs['a']

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [12]:
# arr2
two_arrs['b']

array([0.53183609, 0.47746795, 0.66122838, 0.8735272 , 0.47971673])

`savez_compressed` - performs the same function as savez . The only difference is that it saves the file compressed, which saves memory space