<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/indexing_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**extracting a value from a simple array**

In [2]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# 5
arr[4]

5

In [4]:
# 7
arr[6]

7

In [6]:
# 9
print(arr[8])

9


In [7]:
# cutting the last element
arr[-1]

10

In [8]:
# 9
arr[-2]

9

**cutting several elements**

In [9]:
arr2 = np.arange(10, 110, 10)
arr2

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [11]:
# 10, 20
arr2[0:2]

array([10, 20])

In [13]:
# 40, 50
arr2[3:5]

array([40, 50])

In [16]:
# 80, 90
arr2[7:-1]

array([80, 90])

In [17]:
# 30, 40, 50
arr2[2:5]

array([30, 40, 50])

**cutting multiple elements in several steps**

In [22]:
arr2[0:-1:2]

array([10, 30, 50, 70, 90])

In [23]:
arr2[1:7:3]

array([20, 50])

In [24]:
arr2[::2]

array([10, 30, 50, 70, 90])

**to extract a value from an array and perform an operation on it**

In [25]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# 4, 5
arr_4_5 = arr[3:5]
arr_4_5

array([4, 5])

- If a change is made to the part cut from the array, it will also affect the main array and change its element

In [30]:
#change all elements of the stored array 4 and 5 to 0.Compare the answer of the original array and the cut arrays
arr_4_5[:] = 0
print(arr)
print(arr_4_5)

[ 1  2  3  0  0  6  7  8  9 10]
[0 0]


- If we need to make changes to the cut portion without affecting the original array, we use the `copy()` method

In [31]:
arr2

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [33]:
arr2_80_90 = arr2[7:-1].copy()
arr2_80_90

array([80, 90])

In [34]:
# change the elements of this array
arr2_80_90[0] = -1
arr2_80_90[1] = -111
print(arr2_80_90)

[  -1 -111]


In [35]:
# compare the answers of the main array and the array arr2_80_90
print(arr2)
print(arr2_80_90)

[ 10  20  30  40  50  60  70  80  90 100]
[  -1 -111]


- did not affect the main array

**Indexing and slicing in a 2D array**

In [37]:
arr2d = np.arange(1, 13).reshape(4, 3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
# determining array size
arr2d.shape

(4, 3)

In [38]:
# 3
arr2d[0, -1]

3

In [39]:
# 5
arr2d[1, 1]

5

In [40]:
# 7
arr2d[2, 0]

7

In [41]:
# 12
arr2d[-1, -1]

12

**Cutting multiple elements from a 2D array**

In [45]:
print(arr2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [47]:
# 1, 2
arr2d[0, 0:-1]

array([1, 2])

In [48]:
# 5, 6
arr2d[1, 1:]

array([5, 6])

In [50]:
# 7, 8, 9
arr2d[2]

array([7, 8, 9])

In [51]:
# 10, 11
arr2d[-1, 0:-1]

array([10, 11])

In [52]:
arr2d[:, 1:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [54]:
arr2d[:, 0:-1]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

**Indexing and slicing in a 3D array**

In [57]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [11, 12, 13]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [58]:
# 3
arr3d[0][0, -1]

3

In [59]:
# 4
arr3d[0][1, 0]

4

In [60]:
# 5, 6
arr3d[0][1, 1:]

array([5, 6])

In [61]:
# 7, 8
arr3d[1][0, :-1]

array([7, 8])

In [62]:
# 12, 13
arr3d[1][-1, 1:]

array([12, 13])