<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/math_and_statistics_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

###N1
**Given `arr = np.array([3, 6, 9, 12, 15])`, compute the mean and standard deviation of the array**

In [2]:
arr = np.array([3, 6, 9, 12, 15])
# average value
print(np.mean(arr))
# standard deviation
print(np.std(arr))

9.0
4.242640687119285


###N2
**How do you find the sum of each row in a 3x3 NumPy array? Provide an example**

In [7]:
arr2 = np.random.randint(10, 100, (3, 3))
print(arr2)
print(np.sum(arr2, axis=1))

[[85 17 66]
 [56 87 53]
 [96 67 65]]
[168 196 228]


###N3
**What is the output of `np.cumsum(np.array([1, 2, 3, 4]))`? Explain how it works**

In [8]:
# 1, 3, 6, 10

###N4
**How can you find the minimum and maximum values in a NumPy array along a specific axis? Provide an example**

In [11]:
arr3 = np.arange(30, 42).reshape(3, 4)
# min
print(arr3.min(axis=0)) # by column

# by row
print(arr3.min(axis=1))

[30 31 32 33]
[30 34 38]


In [12]:
print(arr3.max(axis=0)) # by column

# by row
print(arr3.max(axis=1))

[38 39 40 41]
[33 37 41]
