<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/Netflix_Style_Recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- We have 5 users of a streaming platform and viewing figures for 6 movie genres.
- The data represents the users' interest in each genre (score from 0 to 100) and their subscription status.

- The users interest scores for the 6 genres are represented as 6 rows in the array below.
- Genres: `[Action, Comedy, Drama, Sci-Fi, Horror, Romance]`

In [14]:
import numpy as np

In [25]:
raw_ratings = np.array([
    [85, 40, 20, 90, 10, 5],   # User 0
    [20, 95, 80, 10, 5, 75],   # User 1
    [0, 0, 0, 0, 0, 0],        # User 2 (new profile, no data yet)
    [60, 60, 60, 60, 60, 60],  # User 3
    [45, 55, 100, 30, 20, 85]  # User 4
])
raw_ratings

array([[ 85,  40,  20,  90,  10,   5],
       [ 20,  95,  80,  10,   5,  75],
       [  0,   0,   0,   0,   0,   0],
       [ 60,  60,  60,  60,  60,  60],
       [ 45,  55, 100,  30,  20,  85]])

In [26]:
# User monthly subscription fees (USD)
subscriptions = np.array([15.99, 9.99, 0.0, 12.99, 15.99])
subscriptions

array([15.99,  9.99,  0.  , 12.99, 15.99])

In [27]:
raw_ratings.shape

(5, 6)

In [28]:
# Determine the average of all rows except row 3
average_values = np.mean(raw_ratings[[0, 1, 3, 4], :], axis=0)
average_values

array([52.5 , 62.5 , 65.  , 47.5 , 23.75, 56.25])

In [29]:
# convert the main array to float type
raw_ratings = raw_ratings.astype(float)
raw_ratings

array([[ 85.,  40.,  20.,  90.,  10.,   5.],
       [ 20.,  95.,  80.,  10.,   5.,  75.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [ 60.,  60.,  60.,  60.,  60.,  60.],
       [ 45.,  55., 100.,  30.,  20.,  85.]])

In [30]:
# Complementing the user's scores in row 3 with the average of all users
raw_ratings[2] = average_values
raw_ratings

array([[ 85.  ,  40.  ,  20.  ,  90.  ,  10.  ,   5.  ],
       [ 20.  ,  95.  ,  80.  ,  10.  ,   5.  ,  75.  ],
       [ 52.5 ,  62.5 ,  65.  ,  47.5 ,  23.75,  56.25],
       [ 60.  ,  60.  ,  60.  ,  60.  ,  60.  ,  60.  ],
       [ 45.  ,  55.  , 100.  ,  30.  ,  20.  ,  85.  ]])

In [35]:
# Determine which users have given a score above 70 for the "Drama" genre (column 3) and currently have an active subscription
drama_active = raw_ratings[(raw_ratings[:, 2]>70) & (subscriptions>0)]
drama_active

array([[ 20.,  95.,  80.,  10.,   5.,  75.],
       [ 45.,  55., 100.,  30.,  20.,  85.]])

In [42]:
# The platform wants to promote the "Action" and "Sci-Fi" genres. Increase action (column 1) and sci-fi (column 4)
# by 1.5 times
raw_ratings[:, [0, 3]] = raw_ratings[:, [0, 3]]*1.5
raw_ratings

array([[127.5 ,  40.  ,  20.  , 135.  ,  10.  ,   5.  ],
       [ 30.  ,  95.  ,  80.  ,  15.  ,   5.  ,  75.  ],
       [ 78.75,  62.5 ,  65.  ,  71.25,  23.75,  56.25],
       [ 90.  ,  60.  ,  60.  ,  90.  ,  60.  ,  60.  ],
       [ 67.5 ,  55.  , 100.  ,  45.  ,  20.  ,  85.  ]])

In [ ]:
# to bring the data into the range of 0-1 to feed it into the model