<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/practicec_all.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- **This page practices numpy**

In [1]:
import numpy as np

In [2]:
arr1 = np.array([10, 20, 30, 40, 50])
arr1

array([10, 20, 30, 40, 50])

In [3]:
# dtype
arr1.dtype

dtype('int64')

In [4]:
# shape
arr1.shape

(5,)

In [5]:
# size
arr1.ndim

1

In [6]:
# number of elements
arr1.size

5

In [7]:
arr2 = np.array([1, 2, 3, 4, 5])
arr3 = np.array([[10, 20, 30], [40, 50, 60]])
arr2

array([1, 2, 3, 4, 5])

In [8]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
# dimensions
print("arr2:", arr2.ndim)
print("arr3:", arr3.ndim)

arr2: 1
arr3: 2


In [10]:
# shapes
print("arr2:", arr2.shape)
print("arr3:", arr3.shape)

arr2: (5,)
arr3: (2, 3)


In [11]:
# Create an array of even numbers from 0 to 20
arr4 = np.arange(0, 20, 2)
arr4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# Create a 3x4 array with all elements 0
arr5 = np.zeros(shape=(3, 4))
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# Create an array of size 2x5, all elements of which are 1
arr6 = np.ones((2, 5))
arr6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# Create a 4x4 identity matrix
arr7 = np.eye(4, 4)
arr7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
arr8 = np.arange(10, 110, 10)
arr8

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [16]:
print(arr8[2]) # 30
print(arr8[-1]) # 100

# 30->70
print(arr8[2:6])

30
100
[30 40 50 60]


In [17]:
# get every 2nd element
arr8[::2]

array([10, 30, 50, 70, 90])

In [18]:
arr9 = np.arange(10, 130, 10).reshape(3, 4)
arr9

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [19]:
# Get the element in row 2, column 3
arr9[1, 2]

np.int64(70)

In [20]:
# Extract all elements of the first row
arr9[0, :]

array([10, 20, 30, 40])

In [21]:
# get all elements of the last column
arr9[:, -1]

array([ 40,  80, 120])

In [22]:
# Get the 2x2 sub-section: [[60, 70], [100, 110]]
arr9[1:, 1:3]

array([[ 60,  70],
       [100, 110]])

In [23]:
scores = np.array([45, 67, 89, 34, 56, 78, 90, 23, 67, 88])
scores

array([45, 67, 89, 34, 56, 78, 90, 23, 67, 88])

In [24]:
# Find all scores above 60
scores[scores>60]

array([67, 89, 78, 90, 67, 88])

In [25]:
# Find the scores between 50 and 80 (including 50 and 80)
scores[(scores>=50) & (scores<=80)]

array([67, 56, 78, 67])

In [26]:
prices = np.array([1200, 450, 800, 350, 1500, 600, 2000, 300])
prices

array([1200,  450,  800,  350, 1500,  600, 2000,  300])

In [27]:
# Change prices less than 500 to 0
prices[prices<500] = 0

In [28]:
prices

array([1200,    0,  800,    0, 1500,  600, 2000,    0])

In [29]:
# Mark prices above 1000 as "Expensive" and the rest
# as "Affordable" (create a new array)
new_prices = np.where(prices>1000, "expensive", "affordable")
new_prices

array(['expensive', 'affordable', 'affordable', 'affordable', 'expensive',
       'affordable', 'expensive', 'affordable'], dtype='<U10')

In [30]:
arr10 = np.array([10, 20, 30, 40, 50])
arr11 = np.array([5, 10, 15, 20, 25])

- *Add, subtract, multiply, and divide two arrays*

In [31]:
arr10+arr11

array([15, 30, 45, 60, 75])

In [32]:
arr10*arr11

array([  50,  200,  450,  800, 1250])

In [33]:
arr10-arr11

array([ 5, 10, 15, 20, 25])

In [34]:
arr10/arr11

array([2., 2., 2., 2., 2.])

In [35]:
# Multiply all elements of arr10 by 2
arr10*2

array([ 20,  40,  60,  80, 100])

In [36]:
# Square each element of arr10
arr10**2

array([ 100,  400,  900, 1600, 2500])

In [37]:
arr12 = np.arange(1, 7).reshape(2, 3)
arr13 = np.array([10, 20, 30])
arr12

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr13

array([10, 20, 30])

In [39]:
# Add arr13 to each row of arr12
arr12+arr13

array([[11, 22, 33],
       [14, 25, 36]])

In [40]:
# Multiply each element of arr12 by the corresponding element of arr13
np.multiply(arr12, arr13)

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [41]:
data = np.array([15, 22, 18, 30, 25, 19, 28, 21, 17, 24])
data

array([15, 22, 18, 30, 25, 19, 28, 21, 17, 24])

- *Calculate the mean , median , standard deviation , and variance*

In [42]:
# mean
np.mean(data)

np.float64(21.9)

In [43]:
# median
np.median(data)

np.float64(21.5)

In [44]:
# std
np.std(data)

np.float64(4.6141087980237305)

In [45]:
# var
np.var(data)

np.float64(21.29)

In [46]:
# Find the minimum and maximum values
print("max:", np.max(data))
print("min:", np.min(data))

max: 30
min: 15


In [47]:
# Calculate the sum of all elements
np.sum(data)

np.int64(219)

In [48]:
sales = np.array([[120, 150, 130],
                  [200, 180, 210],
                  [160, 140, 170],
                  [190, 220, 200]])
sales

array([[120, 150, 130],
       [200, 180, 210],
       [160, 140, 170],
       [190, 220, 200]])

In [49]:
sales.ndim

2

In [50]:
# Calculate the average sales in each row
np.mean(sales, axis=1)

array([133.33333333, 196.66666667, 156.66666667, 203.33333333])

In [51]:
# Calculate the total sales in each column
np.sum(sales, axis=0)

array([670, 690, 710])

In [52]:
# Find the average sales across the entire matrix
np.mean(sales)

np.float64(172.5)

In [53]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
vector1

array([1, 2, 3])

In [54]:
vector2

array([4, 5, 6])

In [55]:
# Calculate the dot product between two vectors
np.dot(vector1, vector2)

np.int64(32)

In [56]:
matrix_a = np.arange(1, 7).reshape(2, 3)
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
matrix_b = np.arange(7, 13).reshape(3, 2)
matrix_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [58]:
# Multiply Matrix A and Matrix B
#np.multiply(matrix_a, matrix_b)

In [59]:
# Find the transpose of Matrix A
matrix_a = matrix_a.T
matrix_a

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
np.multiply(matrix_a, matrix_b)

array([[ 7, 32],
       [18, 50],
       [33, 72]])

In [61]:
matrix = np.array([[2, 1],
                   [7, 4]])
matrix

array([[2, 1],
       [7, 4]])

In [62]:
# Find the determinant and inverse of this matrix
det = np.linalg.det(matrix)
inv = np.linalg.inv(matrix)
print('det:', det)
print('inv:', inv)

det: 0.9999999999999996
inv: [[ 4. -1.]
 [-7.  2.]]


In [63]:
matrix*inv

array([[  8.,  -1.],
       [-49.,   8.]])

In [64]:
# Generate 5 random numbers from 0 to 1
arr14 = np.random.rand(5)
arr14

array([0.74300565, 0.23716043, 0.94197572, 0.71139826, 0.5800289 ])

In [65]:
# Generate 10 random integers from 10 to 50
arr15 = np.random.randint(10, 50, 10)
arr15

array([12, 17, 35, 31, 13, 20, 26, 40, 38, 12])

In [66]:
# Create a 3x3 random matrix (0 to 1)
arr16 = np.random.rand(9).reshape(3, 3)
arr16

array([[0.21502737, 0.18228608, 0.28240842],
       [0.54310665, 0.01576974, 0.24519982],
       [0.24673992, 0.64021427, 0.25465677]])

In [67]:
# Set the Seed to 42 and generate 5 random numbers
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [68]:
arr17 = np.arange(1, 7).reshape(2, 3)
arr17

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
# Convert this array to a one-dimensional (1D) array
arr17.flatten()

array([1, 2, 3, 4, 5, 6])

In [70]:
# Make this array 6x1
arr17.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [71]:
arr18 = np.array([10, 20, np.nan, 40, 50, np.nan, 70, 80])
arr18

array([10., 20., nan, 40., 50., nan, 70., 80.])

In [75]:
# Detect if there are NaN values
np.isnan(arr18)

array([False, False,  True, False, False,  True, False, False])

In [88]:
# Count the number of NaN values
np.isnan(arr18).sum()

np.int64(2)

In [92]:
# Extract non-NaN values
arr18[~np.isnan(arr18)]

array([10., 20., 40., 50., 70., 80.])

In [80]:
data2 = np.array([[1.5, 2.3, np.nan, 4.1],
                 [5.2, np.nan, 7.8, 8.9],
                 [np.nan, 10.1, 11.2, 12.3]])
data2

array([[ 1.5,  2.3,  nan,  4.1],
       [ 5.2,  nan,  7.8,  8.9],
       [ nan, 10.1, 11.2, 12.3]])

In [89]:
# Replace NaN values ​​with 0
np.nan_to_num(data2, nan=0)

array([[ 1.5,  2.3,  0. ,  4.1],
       [ 5.2,  0. ,  7.8,  8.9],
       [ 0. , 10.1, 11.2, 12.3]])

In [87]:
data2 = np.array([[1.5, 2.3, np.nan, 4.1],
                 [5.2, np.nan, 7.8, 8.9],
                 [np.nan, 10.1, 11.2, 12.3]])
data2

array([[ 1.5,  2.3,  nan,  4.1],
       [ 5.2,  nan,  7.8,  8.9],
       [ nan, 10.1, 11.2, 12.3]])

In [91]:
# Create an array of only valid values, removing NaN values
data2[~np.isnan(data2)]

array([ 1.5,  2.3,  4.1,  5.2,  7.8,  8.9, 10.1, 11.2, 12.3])

In [93]:
data2

array([[ 1.5,  2.3,  nan,  4.1],
       [ 5.2,  nan,  7.8,  8.9],
       [ nan, 10.1, 11.2, 12.3]])

- *Calculate the average for each column*

In [95]:
means = np.nanmean(data2, axis=0)
means

array([3.35      , 6.2       , 9.5       , 8.43333333])

In [99]:
for col in range(data2.shape[1]):
  data2[:, col] = np.where(np.isnan(data2[:, col]), means[col], data2[:, col])

In [100]:
data2

array([[ 1.5 ,  2.3 ,  9.5 ,  4.1 ],
       [ 5.2 ,  6.2 ,  7.8 ,  8.9 ],
       [ 3.35, 10.1 , 11.2 , 12.3 ]])