<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/practice_all03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100],
                [110, 120, 130, 140, 150],
                [160, 170, 180, 190, 200]])

print("Original array:")
print(arr)

Original array:
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [3]:
arr.shape

(4, 5)

In [6]:
# Extract the part from row 2 to row 4 and from column 1 to column 4
new_arr = arr[1:-1, 0:3]
new_arr

array([[ 60,  70,  80],
       [110, 120, 130]])

In [7]:
new_arr.shape

(2, 3)

In [8]:
arr2 = np.array([[[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print("Original array shape:", arr2.shape)
print(arr2)

Original array shape: (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [10]:
# From the first block , extract all rows, only the 2nd and 3rd columns
arr2[0][:, 1:-1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [12]:
# From the second block , from the 1st row, extract all columns
arr2[1][0, :]

array([13, 14, 15, 16])

In [13]:
arr3 = np.array([15, 22, 8, 35, 42, 18, 50, 11, 29, 7])
print("Original array:", arr3)

Original array: [15 22  8 35 42 18 50 11 29  7]


In [15]:
# Find all values ​​greater than 20
arr3[arr3>20]

array([22, 35, 42, 50, 29])

In [16]:
arr4 = np.array([[12, 35, 8, 42],
                [55, 18, 70, 23],
                [9, 48, 15, 61]])

print("Original array:")
print(arr4)

Original array:
[[12 35  8 42]
 [55 18 70 23]
 [ 9 48 15 61]]


In [19]:
# Find all values ​​less than 30 AND greater than 15
arr4[(arr4<30) & (arr4>15)]

array([18, 23])

In [20]:
np.argwhere(arr4==18)

array([[1, 1]])

In [21]:
np.argwhere(arr4==23)

array([[1, 3]])

In [22]:
arr5 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

indices = [0, 3, 5, 8]

print("Original array:", arr5)
print("Indices:", indices)

Original array: [ 10  20  30  40  50  60  70  80  90 100]
Indices: [0, 3, 5, 8]


In [26]:
# Extract elements at given indices
new_arr5 = arr5[indices]
new_arr5

array([10, 40, 60, 90])