<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/practicec_all.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- **This page practices numpy**

In [1]:
import numpy as np

In [2]:
arr1 = np.array([10, 20, 30, 40, 50])
arr1

array([10, 20, 30, 40, 50])

In [5]:
# dtype
arr1.dtype

dtype('int64')

In [6]:
# shape
arr1.shape

(5,)

In [8]:
# size
arr1.ndim

1

In [9]:
# number of elements
arr1.size

5

In [10]:
arr2 = np.array([1, 2, 3, 4, 5])
arr3 = np.array([[10, 20, 30], [40, 50, 60]])
arr2

array([1, 2, 3, 4, 5])

In [11]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
# dimensions
print("arr2:", arr2.ndim)
print("arr3:", arr3.ndim)

arr2: 1
arr3: 2


In [13]:
# shapes
print("arr2:", arr2.shape)
print("arr3:", arr3.shape)

arr2: (5,)
arr3: (2, 3)


In [14]:
# Create an array of even numbers from 0 to 20
arr4 = np.arange(0, 20, 2)
arr4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# Create a 3x4 array with all elements 0
arr5 = np.zeros(shape=(3, 4))
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# Create an array of size 2x5, all elements of which are 1
arr6 = np.ones((2, 5))
arr6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# Create a 4x4 identity matrix
arr7 = np.eye(4, 4)
arr7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
arr8 = np.arange(10, 110, 10)
arr8

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [24]:
print(arr8[2]) # 30
print(arr8[-1]) # 100

# 30->70
print(arr8[2:6])

30
100
[30 40 50 60]


In [26]:
# get every 2nd element
arr8[::2]

array([10, 30, 50, 70, 90])

In [27]:
arr9 = np.arange(10, 130, 10).reshape(3, 4)
arr9

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [29]:
# Get the element in row 2, column 3
arr9[1, 2]

np.int64(70)

In [30]:
# Extract all elements of the first row
arr9[0, :]

array([10, 20, 30, 40])

In [31]:
# get all elements of the last column
arr9[:, -1]

array([ 40,  80, 120])

In [32]:
# Get the 2x2 sub-section: [[60, 70], [100, 110]]
arr9[1:, 1:3]

array([[ 60,  70],
       [100, 110]])