<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/practicec_all.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- **This page practices numpy**

In [1]:
import numpy as np

In [2]:
arr1 = np.array([10, 20, 30, 40, 50])
arr1

array([10, 20, 30, 40, 50])

In [5]:
# dtype
arr1.dtype

dtype('int64')

In [6]:
# shape
arr1.shape

(5,)

In [8]:
# size
arr1.ndim

1

In [9]:
# number of elements
arr1.size

5

In [10]:
arr2 = np.array([1, 2, 3, 4, 5])
arr3 = np.array([[10, 20, 30], [40, 50, 60]])
arr2

array([1, 2, 3, 4, 5])

In [11]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
# dimensions
print("arr2:", arr2.ndim)
print("arr3:", arr3.ndim)

arr2: 1
arr3: 2


In [13]:
# shapes
print("arr2:", arr2.shape)
print("arr3:", arr3.shape)

arr2: (5,)
arr3: (2, 3)


In [14]:
# Create an array of even numbers from 0 to 20
arr4 = np.arange(0, 20, 2)
arr4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# Create a 3x4 array with all elements 0
arr5 = np.zeros(shape=(3, 4))
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# Create an array of size 2x5, all elements of which are 1
arr6 = np.ones((2, 5))
arr6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# Create a 4x4 identity matrix
arr7 = np.eye(4, 4)
arr7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
arr8 = np.arange(10, 110, 10)
arr8

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [24]:
print(arr8[2]) # 30
print(arr8[-1]) # 100

# 30->70
print(arr8[2:6])

30
100
[30 40 50 60]


In [26]:
# get every 2nd element
arr8[::2]

array([10, 30, 50, 70, 90])

In [27]:
arr9 = np.arange(10, 130, 10).reshape(3, 4)
arr9

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [29]:
# Get the element in row 2, column 3
arr9[1, 2]

np.int64(70)

In [30]:
# Extract all elements of the first row
arr9[0, :]

array([10, 20, 30, 40])

In [31]:
# get all elements of the last column
arr9[:, -1]

array([ 40,  80, 120])

In [32]:
# Get the 2x2 sub-section: [[60, 70], [100, 110]]
arr9[1:, 1:3]

array([[ 60,  70],
       [100, 110]])

In [33]:
scores = np.array([45, 67, 89, 34, 56, 78, 90, 23, 67, 88])
scores

array([45, 67, 89, 34, 56, 78, 90, 23, 67, 88])

In [34]:
# Find all scores above 60
scores[scores>60]

array([67, 89, 78, 90, 67, 88])

In [36]:
# Find the scores between 50 and 80 (including 50 and 80)
scores[(scores>=50) & (scores<=80)]

array([67, 56, 78, 67])

In [37]:
prices = np.array([1200, 450, 800, 350, 1500, 600, 2000, 300])
prices

array([1200,  450,  800,  350, 1500,  600, 2000,  300])

In [39]:
# Change prices less than 500 to 0
prices[prices<500] = 0

In [40]:
prices

array([1200,    0,  800,    0, 1500,  600, 2000,    0])

In [44]:
# Mark prices above 1000 as "Expensive" and the rest
# as "Affordable" (create a new array)
new_prices = np.where(prices>1000, "expensive", "affordable")
new_prices

array(['expensive', 'affordable', 'affordable', 'affordable', 'expensive',
       'affordable', 'expensive', 'affordable'], dtype='<U10')

In [45]:
arr10 = np.array([10, 20, 30, 40, 50])
arr11 = np.array([5, 10, 15, 20, 25])

- *Add, subtract, multiply, and divide two arrays*

In [46]:
arr10+arr11

array([15, 30, 45, 60, 75])

In [47]:
arr10*arr11

array([  50,  200,  450,  800, 1250])

In [48]:
arr10-arr11

array([ 5, 10, 15, 20, 25])

In [49]:
arr10/arr11

array([2., 2., 2., 2., 2.])

In [50]:
# Multiply all elements of arr10 by 2
arr10*2

array([ 20,  40,  60,  80, 100])

In [51]:
# Square each element of arr10
arr10**2

array([ 100,  400,  900, 1600, 2500])

In [53]:
arr12 = np.arange(1, 7).reshape(2, 3)
arr13 = np.array([10, 20, 30])
arr12

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr13

array([10, 20, 30])

In [56]:
# Add arr13 to each row of arr12
arr12+arr13

array([[11, 22, 33],
       [14, 25, 36]])

In [58]:
# Multiply each element of arr12 by the corresponding element of arr13
np.multiply(arr12, arr13)

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [59]:
data = np.array([15, 22, 18, 30, 25, 19, 28, 21, 17, 24])
data

array([15, 22, 18, 30, 25, 19, 28, 21, 17, 24])