<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/practice_all02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create a numpy array from this list and display it on the screen
data = [10, 20, 30, 40, 50]
arr1 = np.array(data)
arr1

array([10, 20, 30, 40, 50])

In [3]:
# create a numpy array
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
arr2 = np.array(matrix)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Extract the data type and shape of an array
print("dtype =", arr2.dtype)
print("shape =", arr2.shape)

dtype = int64
shape = (3, 3)


In [7]:
# Create an array of size 4x5 with all elements 0
arr3 = np.zeros((4, 5))
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# Create a 3x3x3 array (3D), all elements of which are 0
arr4 = np.zeros((3, 3, 3))
arr4

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Output the size, shape, and total number of elements of an array
print("format =", arr4.ndim)
print("shape =", arr4.shape)
print("size =", arr4.size)

format = 3
shape = (3, 3, 3)
size = 27


In [12]:
# Create an array of size 5x4, all elements of which are 1
arr5 = np.ones((5, 4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- *Create an array of size 2x6, all elements of which are 1, and of data type float*

In [14]:
arr6 = np.ones((2, 6), dtype=np.float16)
print(arr6)
print("dtype =", arr6.dtype)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
dtype = float16


In [16]:
# Create a 3x4 array with all elements 7
arr7 = np.full((3, 4), 7)
arr7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [19]:
# Create a 5x5 array with all elements 3.14
arr8 = np.full((5, 5), 3.14)
print(arr8)
print("dtype =", arr8.dtype)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
dtype = float64


In [21]:
# Create a 5x5 identity matrix
arr9 = np.eye(5)
arr9

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# Create a 7x7 unit matrix
arr10 = np.eye(7)
arr10

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [24]:
# Calculate the sum of diagonal elements
arr10_diags = np.diag(arr10)
arr10_diags.sum()

np.float64(7.0)

In [26]:
# Create an array of numbers from 0 to 50
arr11 = np.arange(0, 50)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
# Create an array of numbers from 10 to 100, every 5 digits
arr12 = np.arange(10, 100, 5)
arr12

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [29]:
arr12.size

18