<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/practice_all02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# Create a numpy array from this list and display it on the screen
data = [10, 20, 30, 40, 50]
arr1 = np.array(data)
arr1

array([10, 20, 30, 40, 50])

In [4]:
# create a numpy array
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
arr2 = np.array(matrix)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Extract the data type and shape of an array
print("dtype =", arr2.dtype)
print("shape =", arr2.shape)

dtype = int64
shape = (3, 3)


In [6]:
# Create an array of size 4x5 with all elements 0
arr3 = np.zeros((4, 5))
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
# Create a 3x3x3 array (3D), all elements of which are 0
arr4 = np.zeros((3, 3, 3))
arr4

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
# Output the size, shape, and total number of elements of an array
print("format =", arr4.ndim)
print("shape =", arr4.shape)
print("size =", arr4.size)

format = 3
shape = (3, 3, 3)
size = 27


In [9]:
# Create an array of size 5x4, all elements of which are 1
arr5 = np.ones((5, 4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- *Create an array of size 2x6, all elements of which are 1, and of data type float*

In [10]:
arr6 = np.ones((2, 6), dtype=np.float16)
print(arr6)
print("dtype =", arr6.dtype)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
dtype = float16


In [11]:
# Create a 3x4 array with all elements 7
arr7 = np.full((3, 4), 7)
arr7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [12]:
# Create a 5x5 array with all elements 3.14
arr8 = np.full((5, 5), 3.14)
print(arr8)
print("dtype =", arr8.dtype)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
dtype = float64


In [13]:
# Create a 5x5 identity matrix
arr9 = np.eye(5)
arr9

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
# Create a 7x7 unit matrix
arr10 = np.eye(7)
arr10

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [15]:
# Calculate the sum of diagonal elements
arr10_diags = np.diag(arr10)
arr10_diags.sum()

np.float64(7.0)

In [16]:
# Create an array of numbers from 0 to 50
arr11 = np.arange(0, 50)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [17]:
# Create an array of numbers from 10 to 100, every 5 digits
arr12 = np.arange(10, 100, 5)
arr12

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [18]:
arr12.size

18

In [19]:
# Generate 11 evenly distributed numbers in the range 0 to 1
arr13 = np.linspace(0, 1, 11)
arr13

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
# Generate 21 evenly distributed numbers in the range 0 to 100
arr14 = np.linspace(0, 100, 21)
arr14

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [21]:
arr14.size

21

In [22]:
# Extract the first and last elements
print(arr14[0])
print(arr14[-1])

0.0
100.0


In [23]:
arr15 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr15

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
# Extract the shape of the array
arr15.shape

(3, 4)

In [25]:
arr16 = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]],
                [[9, 10], [11, 12]]])
arr16

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [26]:
# Extract the shape of this array
arr16.shape

(3, 2, 2)

In [27]:
arr17 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])
arr17

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
# How many elements are there in the array?
arr17.size

12

In [29]:
# Determine how many elements are in each array
arr18 = np.array([1, 2, 3, 4, 5])
arr19 = np.array([[1, 2, 3], [4, 5, 6]])
arr20 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("arr1 =", arr18.size)
print("arr2 =", arr19.size)
print("arr3 =", arr20.size)

arr1 = 5
arr2 = 6
arr3 = 8


In [30]:
# determine the size of each array
arr21 = np.array([1, 2, 3])
arr22 = np.array([[1, 2], [3, 4]])
arr23 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("arr1 =", arr21.shape)
print("arr2 =", arr22.shape)
print("arr3 =", arr23.shape)

arr1 = (3,)
arr2 = (2, 2)
arr3 = (2, 2, 2)


In [31]:
arr24 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr24

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# Extract the size, shape, and number of elements of an array
print("size =", arr24.ndim)
print("shape =", arr24.shape)
print("number of elements =", arr24.size)

size = 2
shape = (3, 3)
number of elements = 9


In [33]:
# Determine the data type of each array
arr25 = np.array([1, 2, 3])
arr26 = np.array([1.5, 2.5, 3.5])
arr27 = np.array(['a', 'b', 'c'])

print("arr1 =", arr25.dtype)
print("arr2 =", arr26.dtype)
print("arr3 =", arr27.dtype)

arr1 = int64
arr2 = float64
arr3 = <U1


In [34]:
arr28 = np.array([1, 2, 3, 4, 5])
print("original :", arr28.dtype)

original : int64


In [35]:
# convert array to float64 type
arr28_float64 = arr28.astype(np.float64)
print(arr28_float64)
print(arr28_float64.dtype)

[1. 2. 3. 4. 5.]
float64


In [36]:
# Convert again to int32 type
arr28_int32 = arr28.astype(np.int32)
print(arr28_int32)
print("dtype =", arr28_int32.dtype)

[1 2 3 4 5]
dtype = int32


In [37]:
# Create an array of size 3x3, all elements of 1.5, and data type float16
arr29 = np.full((3, 3), 1.5, dtype=np.float16)
arr29

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]], dtype=float16)

In [38]:
arr29.dtype

dtype('float16')

In [39]:
arr29.nbytes

18

In [40]:
# Output the size of each array in bytes
arr30 = np.array([1.0, 2.0, 3.0], dtype=np.float16)
arr31 = np.array([1.0, 2.0, 3.0], dtype=np.float32)
arr32 = np.array([1.0, 2.0, 3.0], dtype=np.float64)

print("arr1 =", arr30.nbytes)
print("arr2 =", arr31.nbytes)
print("arr3 =", arr32.nbytes)

arr1 = 6
arr2 = 12
arr3 = 24


In [41]:
# Create an array from [1, 2, 3, 4, 5]
arr33 = np.array([1, 2, 3, 4, 5])

# Convert the array to float16 type
arr33_float = arr33.astype(np.float16)

# Extract the data type and size of an array
print("dtype =", arr33_float.dtype)
print("size =", arr33_float.size)

dtype = float16
size = 5


In [42]:
# generator
rang = np.random.default_rng(seed=42)

# Create a 5x4 array of random numbers (from 0 to 100)
arr34 = rang.integers(low=0, high=100, size=(5, 4))
arr34

array([[ 8, 77, 65, 43],
       [43, 85,  8, 69],
       [20,  9, 52, 97],
       [73, 76, 71, 78],
       [51, 12, 83, 45]])

In [43]:
arr34.dtype

dtype('int64')

In [44]:
arr34_int32 = arr34.astype(np.int32)
print(arr34_int32.dtype)

int32


In [45]:
# Extract the size, shape, capacity, and data type of an array
print(arr34_int32.ndim)
print(arr34_int32.shape)
print(arr34_int32.size)

2
(5, 4)
20


In [46]:
# Create an array of odd numbers from 1 to 100
arr35 = np.arange(1, 100, 2)
arr35

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [47]:
# Generate 50 evenly distributed numbers in the range 0 to 1
arr36 = np.linspace(0, 1, 50)
arr36

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [48]:
# Output the first 10 elements of an array
arr36[:10]

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347])

In [49]:
arr37 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("original :", arr37)
print("original shape :", arr37.shape)

original : [ 1  2  3  4  5  6  7  8  9 10 11 12]
original shape : (12,)


In [50]:
# Make this array 3x4
arr37.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
arr38 = np.arange(1, 25)

print("Original array:", arr38)
print("Shape:", arr38.shape)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)


In [52]:
# Make this array 2x3x4
arr38.reshape(2, 3, 4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [53]:
arr39 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Original array:")
print(arr39)
print("Shape:", arr39.shape)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [54]:
# Convert this array to a one-dimensional (1D) array
arr39.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [55]:
arr40 = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

print("Original array:")
print(arr40)
print("Shape:", arr40.shape)
print("size :", arr40.size)

Original array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
size : 8


In [56]:
# Convert this 3D array to a one-dimensional array
arr40 = arr40.flatten()
print(arr40)
print("size :", arr40.size)

[1 2 3 4 5 6 7 8]
size : 8


In [57]:
arr41 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:")
print(arr41)
print("Shape:", arr41.shape)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [58]:
# Convert this array to a one-dimensional array (without making a copy)
arr41_new = arr41.ravel()
arr41_new

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- **Change the first element of the original array and check the new array**

In [59]:
arr41[0, 0] = -555
arr41

array([[-555,    2,    3],
       [   4,    5,    6],
       [   7,    8,    9]])

In [60]:
arr41_new

array([-555,    2,    3,    4,    5,    6,    7,    8,    9])

In [61]:
arr42 = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80]])

print("Original array:")
print(arr42)
print("Shape:", arr42.shape)

Original array:
[[10 20 30 40]
 [50 60 70 80]]
Shape: (2, 4)


In [62]:
# Convert this array to a one-dimensional array (without making a copy)
arr42_new = arr42.ravel()
arr42_new

array([10, 20, 30, 40, 50, 60, 70, 80])

In [63]:
arr42_new[6] = 999
arr42_new

array([ 10,  20,  30,  40,  50,  60, 999,  80])

In [64]:
arr42

array([[ 10,  20,  30,  40],
       [ 50,  60, 999,  80]])

In [65]:
arr43 = np.array([1, 2, 3, 4, 5])

print("Original array:", arr43)
print("Shape:", arr43.shape)

Original array: [1 2 3 4 5]
Shape: (5,)


In [66]:
# Add a new dimension to this array so that it becomes (1, 5)
arr43_ex = np.expand_dims(arr43, axis=0)
arr43_ex.shape

(1, 5)

In [67]:
arr43_shape = arr43.reshape(1, 1, 5)
arr43_shape.shape

(1, 1, 5)

In [68]:
arr44 = np.array([[1, 2, 3]])

print("Original array:")
print(arr44)
print("Shape:", arr44.shape)

Original array:
[[1 2 3]]
Shape: (1, 3)


In [70]:
# Add a new dimension to the end of this array, so that it becomes (1, 3, 1)
arr44_ex = np.expand_dims(arr44, axis=-1)
arr44_ex.shape

(1, 3, 1)

In [75]:
# Add a new dimension to the beginning as well, so that it becomes (1, 1, 3, 1)
np.expand_dims(arr44_ex, axis=0).shape

(1, 1, 3, 1)

In [76]:
arr45 = np.array([[[1, 2, 3]]])

print("Original array:")
print(arr45)
print("Shape:", arr45.shape)

Original array:
[[[1 2 3]]]
Shape: (1, 1, 3)


In [79]:
# Remove all unnecessary dimensions from this array (dimensions with size 1
arr45_new = np.squeeze(arr45)
arr45_new

array([1, 2, 3])

In [80]:
arr45_new.shape

(3,)

In [81]:
arr46 = np.array([[[[10]]]])

print("Original array:")
print(arr46)
print("Shape:", arr46.shape)

Original array:
[[[[10]]]]
Shape: (1, 1, 1, 1)


In [83]:
# Remove all unnecessary dimensions from this array
arr46_sq = np.squeeze(arr46)
arr46_sq

array(10)

In [86]:
arr47 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:")
print(arr47)
print("Shape:", arr47.shape)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [89]:
# Convert the rows of this matrix into columns and the columns into rows
arr47 = arr47.T
arr47

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [90]:
arr47.shape

(3, 3)

In [91]:
arr48 = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

print("Original array:")
print(arr48)
print("Shape:", arr48.shape)

Original array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [93]:
# Swap the first and last dimensions of this 3D array
arr48 = np.swapaxes(arr48, 0, 2)
arr48

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [94]:
arr48.shape

(2, 2, 2)

In [95]:
arr49 = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Original array:")
print(arr49)
print("Shape:", arr49.shape)

Original array:
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)


In [98]:
# Find the transpose of this matrix (convert rows to columns)
arr49 = arr49.transpose()
arr49

array([[10, 40],
       [20, 50],
       [30, 60]])

In [99]:
arr50 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Original array:")
print(arr50)
print("Shape:", arr50.shape)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [100]:
# Find the transpose of this matrix
arr50 = arr50.transpose()
arr50

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [102]:
# Find the element at position (1, 2) in the transpose
arr50[1, 2]

np.int64(10)