<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/practice_all03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100],
                [110, 120, 130, 140, 150],
                [160, 170, 180, 190, 200]])

print("Original array:")
print(arr)

Original array:
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [3]:
arr.shape

(4, 5)

In [4]:
# Extract the part from row 2 to row 4 and from column 1 to column 4
new_arr = arr[1:-1, 0:3]
new_arr

array([[ 60,  70,  80],
       [110, 120, 130]])

In [5]:
new_arr.shape

(2, 3)

In [6]:
arr2 = np.array([[[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print("Original array shape:", arr2.shape)
print(arr2)

Original array shape: (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [7]:
# From the first block , extract all rows, only the 2nd and 3rd columns
arr2[0][:, 1:-1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [8]:
# From the second block , from the 1st row, extract all columns
arr2[1][0, :]

array([13, 14, 15, 16])

In [9]:
arr3 = np.array([15, 22, 8, 35, 42, 18, 50, 11, 29, 7])
print("Original array:", arr3)

Original array: [15 22  8 35 42 18 50 11 29  7]


In [10]:
# Find all values ​​greater than 20
arr3[arr3>20]

array([22, 35, 42, 50, 29])

In [11]:
arr4 = np.array([[12, 35, 8, 42],
                [55, 18, 70, 23],
                [9, 48, 15, 61]])

print("Original array:")
print(arr4)

Original array:
[[12 35  8 42]
 [55 18 70 23]
 [ 9 48 15 61]]


In [12]:
# Find all values ​​less than 30 AND greater than 15
arr4[(arr4<30) & (arr4>15)]

array([18, 23])

In [13]:
np.argwhere(arr4==18)

array([[1, 1]])

In [14]:
np.argwhere(arr4==23)

array([[1, 3]])

In [15]:
arr5 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

indices = [0, 3, 5, 8]

print("Original array:", arr5)
print("Indices:", indices)

Original array: [ 10  20  30  40  50  60  70  80  90 100]
Indices: [0, 3, 5, 8]


In [16]:
# Extract elements at given indices
new_arr5 = arr5[indices]
new_arr5

array([10, 40, 60, 90])

In [17]:
arr6 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

row_indices = [0, 2, 3]
col_indices = [1, 3, 2]

print("Original array:")
print(arr6)
print("Row indices:", row_indices)
print("Column indices:", col_indices)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row indices: [0, 2, 3]
Column indices: [1, 3, 2]


In [18]:
arr6.shape

(4, 4)

In [19]:
# Extract the elements at the following positions (0, 1), (2, 3), (3, 2)
arr6[row_indices, col_indices]

array([ 2, 12, 15])

In [20]:
scores = np.array([45, 67, 89, 34, 78, 92, 56, 23, 88, 71])

print("Scores:", scores)

Scores: [45 67 89 34 78 92 56 23 88 71]


In [21]:
# Mark scores above 60 as 'Pass' and the rest as 'Fail'
new_scores = np.where(scores>60, 'pass', 'fail')
new_scores

array(['fail', 'pass', 'pass', 'fail', 'pass', 'pass', 'fail', 'fail',
       'pass', 'pass'], dtype='<U4')

- Classify each temperature into a category:
  - Above 30: 'Hot'
  - Between 20-30: 'Warm'
  - Between 10-20: 'Cool'
  - Below 10: 'Cold

In [22]:
temperatures = np.array([15, 28, 35, 10, 22, 38, 5, 31, 18, 42])

print("Temperatures:", temperatures)

Temperatures: [15 28 35 10 22 38  5 31 18 42]


In [23]:
conditions = [
    (temperatures>30),
    (temperatures >= 20) & (temperatures <= 30),
    (temperatures >=10) & (temperatures <=20),
    (temperatures < 10)
]
second_conds = ['hot', 'warm', 'cool', 'cold']
np.select(conditions, second_conds, temperatures)

array(['cool', 'warm', 'hot', 'cool', 'warm', 'hot', 'cold', 'hot',
       'cool', 'hot'], dtype='<U21')

- Create a category based on age:
  - Under 18: 'Minor'
  - 18-30: 'Young Adult'
  - 31-50: 'Adult'
  - Over 50: 'Senior'

In [24]:
ages = np.array([15, 22, 35, 8, 45, 17, 60, 12, 28, 50])

print("Ages:", ages)

Ages: [15 22 35  8 45 17 60 12 28 50]


In [25]:
conditions_age = [
    (ages < 18),
    (ages>=18) & (ages<=30),
    (ages>=31) & (ages<=50),
    (ages>50)
]
select_conds = ['minor', 'young adult', 'adult', 'senior']
np.select(conditions_age, select_conds, ages)

array(['minor', 'young adult', 'adult', 'minor', 'adult', 'minor',
       'senior', 'minor', 'young adult', 'adult'], dtype='<U21')

- Set category and discount based on price:
  - Above 1000: 'Premium', 15% discount
  - 500-1000: 'Standard', 10% discount
  - Below 500: 'Budget', 5% discount
  - Output prices after category and discount

In [26]:
prices = np.array([1200, 450, 800, 350, 1500, 600, 2000, 300])

print("Prices:", prices)

Prices: [1200  450  800  350 1500  600 2000  300]


In [27]:
# categorize according to prices
conditions_prices = [
    prices>1000,
    (prices>=500) & (prices<=1000),
    prices<500
]
select_conds_prices = ['premium', 'standard', 'budget']
np.select(conditions_prices, select_conds_prices, default=' ')

array(['premium', 'budget', 'standard', 'budget', 'premium', 'standard',
       'premium', 'budget'], dtype='<U8')

In [28]:
# discounting based on prices
conditions_prices = [
    prices>1000,
    (prices>=500) & (prices<=1000),
    prices<500
]
prices_per = [15, 10, 5]
discount = np.select(conditions_prices, prices_per)
discount

array([15,  5, 10,  5, 15, 10, 15,  5])

In [29]:
# categorize and discount based on prices
final_prices = prices - (prices * discount / 100)
final_prices

array([1020. ,  427.5,  720. ,  332.5, 1275. ,  540. , 1700. ,  285. ])

####**broadcasting tasks**

In [30]:
arr7 = np.array([10, 20, 30, 40, 50])
arr8 = np.array([5, 10, 15, 20, 25])

print("Array 1:", arr7)
print("Array 2:", arr8)

Array 1: [10 20 30 40 50]
Array 2: [ 5 10 15 20 25]


In [31]:
# Add, subtract, multiply, and divide two arrays element by element
print("add :", arr7+arr8)
print("subtract :", arr7-arr8)
print("multiply :", arr7*arr8)
print("divide :", arr7/arr8)

add : [15 30 45 60 75]
subtract : [ 5 10 15 20 25]
multiply : [  50  200  450  800 1250]
divide : [2. 2. 2. 2. 2.]


In [32]:
arr9 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr10 = np.array([[9, 8, 7],
                 [6, 5, 4],
                 [3, 2, 1]])

print("Array 1:")
print(arr9)
print("\nArray 2:")
print(arr10)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [33]:
# Multiply two matrices element by element
np.multiply(arr9, arr10)

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [34]:
# Square each element
print("arr9 square :\n", arr9**2)
print("\narr10 square :\n", arr10**2)

arr9 square :
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]

arr10 square :
 [[81 64 49]
 [36 25 16]
 [ 9  4  1]]


In [35]:
# Find the element-wise maximum of arr9 and arr10
np.maximum(arr9, arr10)

array([[9, 8, 7],
       [6, 5, 6],
       [7, 8, 9]])

In [36]:
arr11 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr12 = np.array([10, 20, 30])

print("Array 1 (2x3):")
print(arr11)
print("\nArray 2 (3,):")
print(arr12)

Array 1 (2x3):
[[1 2 3]
 [4 5 6]]

Array 2 (3,):
[10 20 30]


In [37]:
# Add arr12 to each row of arr11
np.add(arr11, arr12)

array([[11, 22, 33],
       [14, 25, 36]])

In [38]:
# Multiply each element of arr1 by the corresponding element of arr2
np.multiply(arr11, arr12)

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [39]:
arr13 = np.array([[1],
                 [2],
                 [3]])

arr14 = np.array([10, 20, 30, 40])

print("Array 1 (3x1):")
print(arr13)
print("\nArray 2 (4,):")
print(arr14)

Array 1 (3x1):
[[1]
 [2]
 [3]]

Array 2 (4,):
[10 20 30 40]


In [40]:
# Add these two arrays (the result will be 3x4)
np.add(arr13, arr14)

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43]])

In [41]:
arr15 = np.array([10, 20, 30, 40, 50])

print("Original array:", arr15)

Original array: [10 20 30 40 50]


In [42]:
# Multiply all elements by 5
arr15*5

array([ 50, 100, 150, 200, 250])

In [43]:
# Add 100 to all elements
arr15+100

array([110, 120, 130, 140, 150])

In [44]:
# Divide all elements by 3
arr15//3

array([ 3,  6, 10, 13, 16])

In [45]:
arr16 = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])

print("Original array:")
print(arr16)

Original array:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [46]:
# Subtract 10 from all elements
arr16-10

array([[-5,  0,  5],
       [10, 15, 20],
       [25, 30, 35]])

In [47]:
# Divide all elements by 2
# Raise each element in the result to the 3rd power
(arr16//2)**3

array([[    8,   125,   343],
       [ 1000,  1728,  3375],
       [ 4913,  8000, 10648]])

####**tasks related to statistical functions**

In [48]:
scores = np.array([85, 90, 78, 92, 88, 76, 95, 82, 89, 91])

print("Scores:", scores)

Scores: [85 90 78 92 88 76 95 82 89 91]


In [49]:
# Calculate the standard deviation of these scores
np.std(scores)

np.float64(5.902541825349483)

In [51]:
# output the average score
np.mean(scores)

np.float64(86.6)

In [52]:
group_a = np.array([50, 52, 51, 49, 50, 51, 50, 52])
group_b = np.array([30, 70, 40, 60, 35, 65, 45, 55])

print("Group A:", group_a)
print("Group B:", group_b)

Group A: [50 52 51 49 50 51 50 52]
Group B: [30 70 40 60 35 65 45 55]


In [53]:
# Calculate the average of both groups
print("mean_a :", np.mean(group_a))
print("mean_b :", np.mean(group_b))

mean_a : 50.625
mean_b : 50.0


In [54]:
# Calculate the standard deviation of both groups
print("std_a :", np.std(group_a))
print("std_b :", np.std(group_b))

std_a : 0.9921567416492215
std_b : 13.693063937629153


In [55]:
data = np.array([10, 12, 15, 18, 20, 22, 25, 28, 30])

print("Data:", data)

Data: [10 12 15 18 20 22 25 28 30]


In [57]:
# Calculate the variance of this data
print("var :", np.var(data))

# calculate the standard deviation
print("std :", np.std(data))

var : 42.888888888888886
std : 6.548960901462833


In [59]:
prices = np.array([[100, 150, 200],
                   [120, 180, 220],
                   [110, 160, 210]])

print("Prices:")
print(prices)

Prices:
[[100 150 200]
 [120 180 220]
 [110 160 210]]


In [61]:
# Calculate the variance for each row
np.var(prices, axis=1)

array([1666.66666667, 1688.88888889, 1666.66666667])

In [62]:
# Calculate the variance for each column
np.var(prices, axis=0)

array([ 66.66666667, 155.55555556,  66.66666667])

In [64]:
# Calculate the variance over the entire matrix
np.var(prices)

np.float64(1765.4320987654319)

In [65]:
sales = np.array([1500, 2300, 1800, 3200, 2100, 1900, 2800, 2400])

print("Sales:", sales)

Sales: [1500 2300 1800 3200 2100 1900 2800 2400]


In [73]:
# Find the highest sales index
np.argmax(sales)

np.int64(3)

In [72]:
# Extract the value of the highest sale
sales[3]

np.int64(3200)

In [74]:
# Find the lowest sales index
np.argmin(sales)

np.int64(0)

In [75]:
np.min(sales)

np.int64(1500)