<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/practice_all03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100],
                [110, 120, 130, 140, 150],
                [160, 170, 180, 190, 200]])

print("Original array:")
print(arr)

Original array:
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [3]:
arr.shape

(4, 5)

In [6]:
# Extract the part from row 2 to row 4 and from column 1 to column 4
new_arr = arr[1:-1, 0:3]
new_arr

array([[ 60,  70,  80],
       [110, 120, 130]])

In [7]:
new_arr.shape

(2, 3)

In [8]:
arr2 = np.array([[[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print("Original array shape:", arr2.shape)
print(arr2)

Original array shape: (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [10]:
# From the first block , extract all rows, only the 2nd and 3rd columns
arr2[0][:, 1:-1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [12]:
# From the second block , from the 1st row, extract all columns
arr2[1][0, :]

array([13, 14, 15, 16])

In [13]:
arr3 = np.array([15, 22, 8, 35, 42, 18, 50, 11, 29, 7])
print("Original array:", arr3)

Original array: [15 22  8 35 42 18 50 11 29  7]


In [15]:
# Find all values ​​greater than 20
arr3[arr3>20]

array([22, 35, 42, 50, 29])

In [16]:
arr4 = np.array([[12, 35, 8, 42],
                [55, 18, 70, 23],
                [9, 48, 15, 61]])

print("Original array:")
print(arr4)

Original array:
[[12 35  8 42]
 [55 18 70 23]
 [ 9 48 15 61]]


In [19]:
# Find all values ​​less than 30 AND greater than 15
arr4[(arr4<30) & (arr4>15)]

array([18, 23])

In [20]:
np.argwhere(arr4==18)

array([[1, 1]])

In [21]:
np.argwhere(arr4==23)

array([[1, 3]])

In [22]:
arr5 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

indices = [0, 3, 5, 8]

print("Original array:", arr5)
print("Indices:", indices)

Original array: [ 10  20  30  40  50  60  70  80  90 100]
Indices: [0, 3, 5, 8]


In [26]:
# Extract elements at given indices
new_arr5 = arr5[indices]
new_arr5

array([10, 40, 60, 90])

In [27]:
arr6 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

row_indices = [0, 2, 3]
col_indices = [1, 3, 2]

print("Original array:")
print(arr6)
print("Row indices:", row_indices)
print("Column indices:", col_indices)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row indices: [0, 2, 3]
Column indices: [1, 3, 2]


In [28]:
arr6.shape

(4, 4)

In [30]:
# Extract the elements at the following positions (0, 1), (2, 3), (3, 2)
arr6[row_indices, col_indices]

array([ 2, 12, 15])

In [31]:
scores = np.array([45, 67, 89, 34, 78, 92, 56, 23, 88, 71])

print("Scores:", scores)

Scores: [45 67 89 34 78 92 56 23 88 71]


In [33]:
# Mark scores above 60 as 'Pass' and the rest as 'Fail'
new_scores = np.where(scores>60, 'pass', 'fail')
new_scores

array(['fail', 'pass', 'pass', 'fail', 'pass', 'pass', 'fail', 'fail',
       'pass', 'pass'], dtype='<U4')

- Classify each temperature into a category:
  - Above 30: 'Hot'
  - Between 20-30: 'Warm'
  - Between 10-20: 'Cool'
  - Below 10: 'Cold

In [34]:
temperatures = np.array([15, 28, 35, 10, 22, 38, 5, 31, 18, 42])

print("Temperatures:", temperatures)

Temperatures: [15 28 35 10 22 38  5 31 18 42]


In [35]:
conditions = [
    (temperatures>30),
    (temperatures >= 20) & (temperatures <= 30),
    (temperatures >=10) & (temperatures <=20),
    (temperatures < 10)
]
second_conds = ['hot', 'warm', 'cool', 'cold']
np.select(conditions, second_conds, temperatures)

array(['cool', 'warm', 'hot', 'cool', 'warm', 'hot', 'cold', 'hot',
       'cool', 'hot'], dtype='<U21')

- Create a category based on age:
  - Under 18: 'Minor'
  - 18-30: 'Young Adult'
  - 31-50: 'Adult'
  - Over 50: 'Senior'

In [36]:
ages = np.array([15, 22, 35, 8, 45, 17, 60, 12, 28, 50])

print("Ages:", ages)

Ages: [15 22 35  8 45 17 60 12 28 50]


In [37]:
conditions_age = [
    (ages < 18),
    (ages>=18) & (ages<=30),
    (ages>=31) & (ages<=50),
    (ages>50)
]
select_conds = ['minor', 'young adult', 'adult', 'senior']
np.select(conditions_age, select_conds, ages)

array(['minor', 'young adult', 'adult', 'minor', 'adult', 'minor',
       'senior', 'minor', 'young adult', 'adult'], dtype='<U21')

In [38]:
prices = np.array([1200, 450, 800, 350, 1500, 600, 2000, 300])

print("Prices:", prices)

Prices: [1200  450  800  350 1500  600 2000  300]


In [46]:
conditions_prices = [
    prices>1000,
    (prices>=500) & (prices<=1000),
    prices<500
]
select_conds_prices = ['premium', 'standard', 'budget']
np.select(conditions_prices, select_conds_prices, default=' ')

array(['premium', 'budget', 'standard', 'budget', 'premium', 'standard',
       'premium', 'budget'], dtype='<U8')