<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/practice_all02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np

In [37]:
# Create a numpy array from this list and display it on the screen
data = [10, 20, 30, 40, 50]
arr1 = np.array(data)
arr1

array([10, 20, 30, 40, 50])

In [38]:
# create a numpy array
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
arr2 = np.array(matrix)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# Extract the data type and shape of an array
print("dtype =", arr2.dtype)
print("shape =", arr2.shape)

dtype = int64
shape = (3, 3)


In [40]:
# Create an array of size 4x5 with all elements 0
arr3 = np.zeros((4, 5))
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
# Create a 3x3x3 array (3D), all elements of which are 0
arr4 = np.zeros((3, 3, 3))
arr4

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
# Output the size, shape, and total number of elements of an array
print("format =", arr4.ndim)
print("shape =", arr4.shape)
print("size =", arr4.size)

format = 3
shape = (3, 3, 3)
size = 27


In [43]:
# Create an array of size 5x4, all elements of which are 1
arr5 = np.ones((5, 4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- *Create an array of size 2x6, all elements of which are 1, and of data type float*

In [44]:
arr6 = np.ones((2, 6), dtype=np.float16)
print(arr6)
print("dtype =", arr6.dtype)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
dtype = float16


In [45]:
# Create a 3x4 array with all elements 7
arr7 = np.full((3, 4), 7)
arr7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [46]:
# Create a 5x5 array with all elements 3.14
arr8 = np.full((5, 5), 3.14)
print(arr8)
print("dtype =", arr8.dtype)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
dtype = float64


In [47]:
# Create a 5x5 identity matrix
arr9 = np.eye(5)
arr9

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
# Create a 7x7 unit matrix
arr10 = np.eye(7)
arr10

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [49]:
# Calculate the sum of diagonal elements
arr10_diags = np.diag(arr10)
arr10_diags.sum()

np.float64(7.0)

In [50]:
# Create an array of numbers from 0 to 50
arr11 = np.arange(0, 50)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [51]:
# Create an array of numbers from 10 to 100, every 5 digits
arr12 = np.arange(10, 100, 5)
arr12

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [52]:
arr12.size

18

In [53]:
# Generate 11 evenly distributed numbers in the range 0 to 1
arr13 = np.linspace(0, 1, 11)
arr13

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [54]:
# Generate 21 evenly distributed numbers in the range 0 to 100
arr14 = np.linspace(0, 100, 21)
arr14

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [55]:
arr14.size

21

In [56]:
# Extract the first and last elements
print(arr14[0])
print(arr14[-1])

0.0
100.0


In [57]:
arr15 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr15

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
# Extract the shape of the array
arr15.shape

(3, 4)

In [59]:
arr16 = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]],
                [[9, 10], [11, 12]]])
arr16

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [60]:
# Extract the shape of this array
arr16.shape

(3, 2, 2)

In [61]:
arr17 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])
arr17

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
# How many elements are there in the array?
arr17.size

12

In [63]:
# Determine how many elements are in each array
arr18 = np.array([1, 2, 3, 4, 5])
arr19 = np.array([[1, 2, 3], [4, 5, 6]])
arr20 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("arr1 =", arr18.size)
print("arr2 =", arr19.size)
print("arr3 =", arr20.size)

arr1 = 5
arr2 = 6
arr3 = 8


In [64]:
# determine the size of each array
arr21 = np.array([1, 2, 3])
arr22 = np.array([[1, 2], [3, 4]])
arr23 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("arr1 =", arr21.shape)
print("arr2 =", arr22.shape)
print("arr3 =", arr23.shape)

arr1 = (3,)
arr2 = (2, 2)
arr3 = (2, 2, 2)


In [65]:
arr24 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr24

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
# Extract the size, shape, and number of elements of an array
print("size =", arr24.ndim)
print("shape =", arr24.shape)
print("number of elements =", arr24.size)

size = 2
shape = (3, 3)
number of elements = 9


In [67]:
# Determine the data type of each array
arr25 = np.array([1, 2, 3])
arr26 = np.array([1.5, 2.5, 3.5])
arr27 = np.array(['a', 'b', 'c'])

print("arr1 =", arr25.dtype)
print("arr2 =", arr26.dtype)
print("arr3 =", arr27.dtype)

arr1 = int64
arr2 = float64
arr3 = <U1


In [68]:
arr28 = np.array([1, 2, 3, 4, 5])
print("original :", arr28.dtype)

original : int64


In [70]:
# convert array to float64 type
arr28_float64 = arr28.astype(np.float64)
print(arr28_float64)
print(arr28_float64.dtype)

[1. 2. 3. 4. 5.]
float64


In [71]:
# Convert again to int32 type
arr28_int32 = arr28.astype(np.int32)
print(arr28_int32)
print("dtype =", arr28_int32.dtype)

[1 2 3 4 5]
dtype = int32


In [72]:
# Create an array of size 3x3, all elements of 1.5, and data type float16
arr29 = np.full((3, 3), 1.5, dtype=np.float16)
arr29

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]], dtype=float16)

In [73]:
arr29.dtype

dtype('float16')

In [76]:
arr29.nbytes

18

In [77]:
# Output the size of each array in bytes
arr30 = np.array([1.0, 2.0, 3.0], dtype=np.float16)
arr31 = np.array([1.0, 2.0, 3.0], dtype=np.float32)
arr32 = np.array([1.0, 2.0, 3.0], dtype=np.float64)

print("arr1 =", arr30.nbytes)
print("arr2 =", arr31.nbytes)
print("arr3 =", arr32.nbytes)

arr1 = 6
arr2 = 12
arr3 = 24


In [78]:
# Create an array from [1, 2, 3, 4, 5]
arr33 = np.array([1, 2, 3, 4, 5])

# Convert the array to float16 type
arr33_float = arr33.astype(np.float16)

# Extract the data type and size of an array
print("dtype =", arr33_float.dtype)
print("size =", arr33_float.size)

dtype = float16
size = 5


In [79]:
# generator
rang = np.random.default_rng(seed=42)

# Create a 5x4 array of random numbers (from 0 to 100)
arr34 = rang.integers(low=0, high=100, size=(5, 4))
arr34

array([[ 8, 77, 65, 43],
       [43, 85,  8, 69],
       [20,  9, 52, 97],
       [73, 76, 71, 78],
       [51, 12, 83, 45]])

In [80]:
arr34.dtype

dtype('int64')

In [82]:
arr34_int32 = arr34.astype(np.int32)
print(arr34_int32.dtype)

int32


In [84]:
# Extract the size, shape, capacity, and data type of an array
print(arr34_int32.ndim)
print(arr34_int32.shape)
print(arr34_int32.size)

2
(5, 4)
20


In [86]:
# Create an array of odd numbers from 1 to 100
arr35 = np.arange(1, 100, 2)
arr35

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [89]:
# Generate 50 evenly distributed numbers in the range 0 to 1
arr36 = np.linspace(0, 1, 50)
arr36

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [92]:
# Output the first 10 elements of an array
arr36[:10]

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347])