<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/rep_22_dec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(0, 10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr2 = np.ones((3, 4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.arange(5, 25)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [5]:
# 5 dan 25 gacha juft sonlar massivini yaratish
n = 5
start = n if n%2==0 else n+1
np.arange(start, 26, 2)

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [6]:
arr3 = np.arange(1, 10).reshape(3, 3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

####**slicing**

In [8]:
arr4 = np.array([5, 12, 7, 20, 3, 15, 8, 25])
arr4

array([ 5, 12,  7, 20,  3, 15,  8, 25])

In [9]:
# 10 dan katta qiymatlarni olish
arr4[arr4>10]

array([12, 20, 15, 25])

In [10]:
# birinchi 5 ta elementni olish
arr4[:5]

array([ 5, 12,  7, 20,  3])

In [11]:
# ohirgi 4 ta elementni olish
arr4[-3:]

array([15,  8, 25])

In [12]:
# 5 va 20 oralig'idagi qiymatlarni olish
arr4[(arr4>5) & (arr4<20)]

array([12,  7, 15,  8])

In [13]:
juftlar = []
for n in arr4:
  if n%2 == 0:
    juftlar.append(n)
juftlar

[np.int64(12), np.int64(20), np.int64(8)]

In [14]:
# 10 dan kichik qiymatlarni 0 ga almashtirish
arr4[arr4 < 10] = 0
arr4

array([ 0, 12,  0, 20,  0, 15,  0, 25])

In [15]:
arr5 = np.array([2, 4, 6, 8, 10])
arr5

array([ 2,  4,  6,  8, 10])

In [16]:
# har bir elementni 3 ga ko'paytirish
arr5 * 3

array([ 6, 12, 18, 24, 30])

In [17]:
# har bir elementga 5 qo'shish
arr5 + 5

array([ 7,  9, 11, 13, 15])

In [18]:
# har bir elementni kvadratini hisoblash
arr5**2

array([  4,  16,  36,  64, 100])

In [19]:
# har bir qiymatdan o'rtacha qiymatni ayirish
arr5 - np.mean(arr5)

array([-4., -2.,  0.,  2.,  4.])

In [20]:
# har bir elemetni o'z indeksiga ko'paytirish
arr5 * list(range(len(arr5)))

array([ 0,  4, 12, 24, 40])

In [21]:
arr6 = np.array([[10, 20, 30],
                [5, 15, 25],
                [2, 4, 6]])
arr6

array([[10, 20, 30],
       [ 5, 15, 25],
       [ 2,  4,  6]])

In [22]:
# barcha elementlar yigindisini aniqlash
np.sum(arr6)

np.int64(117)

In [23]:
# har bir ustunni o'rtacha qiymatini aniqlash
np.mean(arr6, axis=0)

array([ 5.66666667, 13.        , 20.33333333])

In [24]:
# har bir qatorni maksimal qiymatini aniqlash
np.max(arr6, axis=1)

array([30, 25,  6])

In [25]:
arr6

array([[10, 20, 30],
       [ 5, 15, 25],
       [ 2,  4,  6]])

In [26]:
# arr6 ning eng kichik qiymatini aniqlash
np.min(arr6)

np.int64(2)

In [27]:
np.sum(arr6, axis=1)

array([60, 45, 12])

In [28]:
np.argmax(arr6)

np.int64(2)

In [29]:
arr7 = np.array([10, np.nan, 20, np.nan, 30, 40])
arr7

array([10., nan, 20., nan, 30., 40.])

In [30]:
np.sum(np.isnan(arr7))

np.int64(2)

In [31]:
# nan bo'lmagan qiymatlarni o'rtachasini aniqlash
np.nanmean(arr7)

np.float64(25.0)

In [32]:
nans = np.isnan(arr7)
arr7[nans] = 0
arr7

array([10.,  0., 20.,  0., 30., 40.])

In [35]:
arr7 = np.array([10, np.nan, 20, np.nan, 30, 40])
arr7

array([10., nan, 20., nan, 30., 40.])

In [36]:
np.sum(np.isnan(arr7))

np.int64(2)

In [38]:
# na bo'lmagan qiymatlarni olish
arr7[~np.isnan(arr7)]

array([10., 20., 30., 40.])

In [41]:
arr7_mean = np.nanmean(arr7)
np.isnan(arr7)

array([False,  True, False,  True, False, False])

In [43]:
arr7[np.isnan(arr7)] = arr7_mean
arr7

array([10., 25., 20., 25., 30., 40.])

In [44]:
arr8 = np.array([1, 2, 3, 4, 5, 6])
arr8

array([1, 2, 3, 4, 5, 6])

In [46]:
# massivni 3 ustun 2 qatorli qilish
arr8.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# 2 ustun va 3 qatorli qilish
arr8_2d = arr8.reshape(3, 2)
arr8_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
arr8_2d.T

array([[1, 3, 5],
       [2, 4, 6]])

In [51]:
arr8_2d.ravel()

array([1, 2, 3, 4, 5, 6])

In [53]:
arr8.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [55]:
arr9 = np.random.rand(5)
arr9

array([0.27678623, 0.26212168, 0.37526881, 0.03581615, 0.40665884])

In [57]:
arr10 = np.random.randint(1, 100, 10)
arr10

array([43, 18, 45, 27, 99, 27, 57, 15, 35, 56])

In [58]:
arr11 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr11

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.random.shuffle(arr11)

In [62]:
arr11

array([4, 9, 8, 7, 2, 6, 3, 1, 5])

In [63]:
# massivdan tasodifiy 3 ta qiymatni olish
np.random.choice(arr11, size=3, replace=False)

array([6, 8, 3])

In [68]:
np.random.seed(42)
arr = np.random.rand(5)

In [69]:
arr

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])