<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/rep_22_dec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(0, 10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr2 = np.ones((3, 4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.arange(5, 25)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [5]:
# 5 dan 25 gacha juft sonlar massivini yaratish
n = 5
start = n if n%2==0 else n+1
np.arange(start, 26, 2)

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [6]:
arr3 = np.arange(1, 10).reshape(3, 3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

####**slicing**

In [8]:
arr4 = np.array([5, 12, 7, 20, 3, 15, 8, 25])
arr4

array([ 5, 12,  7, 20,  3, 15,  8, 25])

In [9]:
# 10 dan katta qiymatlarni olish
arr4[arr4>10]

array([12, 20, 15, 25])

In [10]:
# birinchi 5 ta elementni olish
arr4[:5]

array([ 5, 12,  7, 20,  3])

In [11]:
# ohirgi 4 ta elementni olish
arr4[-3:]

array([15,  8, 25])

In [12]:
# 5 va 20 oralig'idagi qiymatlarni olish
arr4[(arr4>5) & (arr4<20)]

array([12,  7, 15,  8])

In [13]:
juftlar = []
for n in arr4:
  if n%2 == 0:
    juftlar.append(n)
juftlar

[np.int64(12), np.int64(20), np.int64(8)]

In [16]:
# 10 dan kichik qiymatlarni 0 ga almashtirish
arr4[arr4 < 10] = 0
arr4

array([ 0, 12,  0, 20,  0, 15,  0, 25])

In [17]:
arr5 = np.array([2, 4, 6, 8, 10])
arr5

array([ 2,  4,  6,  8, 10])

In [18]:
# har bir elementni 3 ga ko'paytirish
arr5 * 3

array([ 6, 12, 18, 24, 30])

In [19]:
# har bir elementga 5 qo'shish
arr5 + 5

array([ 7,  9, 11, 13, 15])

In [21]:
# har bir elementni kvadratini hisoblash
arr5**2

array([  4,  16,  36,  64, 100])

In [26]:
# har bir qiymatdan o'rtacha qiymatni ayirish
arr5 - np.mean(arr5)

array([-4., -2.,  0.,  2.,  4.])

In [32]:
# har bir elemetni o'z indeksiga ko'paytirish
arr5 * list(range(len(arr5)))

array([ 0,  4, 12, 24, 40])

In [33]:
arr6 = np.array([[10, 20, 30],
                [5, 15, 25],
                [2, 4, 6]])
arr6

array([[10, 20, 30],
       [ 5, 15, 25],
       [ 2,  4,  6]])

In [34]:
# barcha elementlar yigindisini aniqlash
np.sum(arr6)

np.int64(117)

In [36]:
# har bir ustunni o'rtacha qiymatini aniqlash
np.mean(arr6, axis=0)

array([ 5.66666667, 13.        , 20.33333333])

In [39]:
# har bir qatorni maksimal qiymatini aniqlash
np.max(arr6, axis=1)

array([30, 25,  6])