<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/rep_22_dec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(0, 10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr2 = np.ones((3, 4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.arange(5, 25)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [8]:
# 5 dan 25 gacha juft sonlar massivini yaratish
n = 5
start = n if n%2==0 else n+1
np.arange(start, 26, 2)

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [9]:
arr3 = np.arange(1, 10).reshape(3, 3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

####**slicing**

In [13]:
arr4 = np.array([5, 12, 7, 20, 3, 15, 8, 25])
arr4

array([ 5, 12,  7, 20,  3, 15,  8, 25])

In [14]:
# 10 dan katta qiymatlarni olish
arr4[arr4>10]

array([12, 20, 15, 25])

In [16]:
# birinchi 5 ta elementni olish
arr4[:5]

array([ 5, 12,  7, 20,  3])

In [22]:
# ohirgi 4 ta elementni olish
arr4[-3:]

array([15,  8, 25])

In [24]:
# 5 va 20 oralig'idagi qiymatlarni olish
arr4[(arr4>5) & (arr4<20)]

array([12,  7, 15,  8])

In [25]:
juftlar = []
for n in arr4:
  if n%2 == 0:
    juftlar.append(n)
juftlar

[np.int64(12), np.int64(20), np.int64(8)]