<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/set_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**In this topic we will learn the following functions:**

`unique , intersect1d , union1d , setdiff1d , setxor1d`

**unique**

In [2]:
# unique - returns non-repeating elements of an array
arr = np.array([1, 1, 2, 3, 3, 4, 5, 5, 6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [3]:
# determine the number of times each element of an array is repeated
arr_c = np.unique(arr, return_counts=True)
print(arr_c)

(array([1, 2, 3, 4, 5, 6]), array([2, 1, 2, 1, 2, 1]))


In [4]:
# writing the above two actions in one line of code
values, counts = np.unique(arr, return_counts=True)
print(values)
print(counts)

[1 2 3 4 5 6]
[2 1 2 1 2 1]


In [6]:
# determining the indices of non-repeating elements in an array
arr_idx = np.unique(arr, return_index=True)
print(arr_idx)

(array([1, 2, 3, 4, 5, 6]), array([0, 2, 3, 5, 6, 8]))


**intersect1d**

- returns the same elements that exist in both arrays. There will be no duplicate elements and it will always be sorted

In [9]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

common = np.intersect1d(arr1, arr2)
print(common)

[3 4 5]


**union1d**

- combines the elements of both arrays. Makes the elements unique and always sorted

In [10]:
arr3 = np.array([1, 2, 3])
arr4 = np.array([3, 4, 5])

union = np.union1d(arr3, arr4)
print(union)

[1 2 3 4 5]


**setdiff1d**

- extracts elements from one array that are not present in another
- i.e. it removes the elements in arr2 from the elements in arr1

In [11]:
arr5 = np.array([1, 2, 3, 4, 5])
arr6 = np.array([3, 4, 5, 6, 7])

setd = np.setdiff1d(arr5, arr6)
print(setd)

[1 2]


**setxor1d**

- returns elements that are present in either array but not in both

In [12]:
arr7 = np.array([1, 2, 3, 4, 5])
arr8 = np.array([3, 4, 5, 6, 7])

xor1 = np.setxor1d(arr7, arr8)
print(xor1)

[1 2 6 7]
