<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**We will learn to sort array elements using the sort function**

In [2]:
arr = np.array([10, 1, 9, 2, 8, 3, 7, 4])
sort_arr = np.sort(arr)
print(sort_arr)

[ 1  2  3  4  7  8  9 10]


In [3]:
arr2 = np.array([11, -1, 3, 2, -3, 5, 7, 9])
arr2_sort = np.sort(arr2)
print(arr2_sort)

[-3 -1  2  3  5  7  9 11]


**reverse order**

In [4]:
arr3 = np.arange(10, 20)
arr3_rev = -np.sort(-arr3)
print(arr3_rev)

[19 18 17 16 15 14 13 12 11 10]


In [6]:
arr4 = np.arange(1, 10)
arr4_rev = -np.sort(-arr4)
print(arr4_rev)

[9 8 7 6 5 4 3 2 1]


**Sorting in a two-dimensional array is done by: axis=0, axis=1**

In [12]:
arr2d = np.array([[4, 3, 2, 1], [8, 7, 6, 5], [9, 11, 10, 12]])
arr2d_sort = np.sort(arr2d, axis=1)
print(arr2d)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [ 9 11 10 12]]


In [13]:
print(arr2d_sort)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
# reverse order
arr2d_rev = -np.sort(-arr2d)
print(arr2d_rev)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
