<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/sorting_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

###N1
**Given `arr = np.array([5, 1, 8, 3, 2])`, what will be the output of `np.sort(arr)`?**

In [18]:
# 1, 2, 3, 5, 8

###N2
**How can you sort a 2D NumPy array along columns ?**

In [19]:
arr = np.random.randint(10, 100, (3, 4))
arr_sort = np.sort(arr, axis=0)
print(arr)

[[94 52 17 13]
 [77 51 88 54]
 [39 80 22 12]]


In [20]:
print(arr_sort)

[[39 51 17 12]
 [77 52 22 13]
 [94 80 88 54]]


###N3
**What is the difference between `np.sort(arr)` and `arr.sort()` ?**

In [21]:
# There is no difference, they both perform the same function

###N4
**Suppose you have an array with NaN values. How can you sort it while ensuring that NaN values appear at the end of the array ?**

In [22]:
arr4 = np.array([1, np.nan, 3, np.nan, 5, 6, np.nan])
arr4_sort = np.sort(arr4)
print(arr4_sort)

[ 1.  3.  5.  6. nan nan nan]
