<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/ufuncs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

- **universal functions are mathematical functions that allow vectorized calculations**

- *Universal functions are divided into two:*
  1. unary functions. They take one argument
  2. binary functions. They take two arguments

We will learn unary functions: `sqrt, square, exp, log, modf, sign, isnan`

and binary functions: `add, multiply, maximum`

In [12]:
# sqrt - returns the square root of each element
arr = np.arange(1, 11)
print(arr)
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [5]:
arr2 = np.arange(11, 21)
print(arr2)

[11 12 13 14 15 16 17 18 19 20]


In [6]:
# Let's give the sqrt function two arguments
np.sqrt(arr, arr2)

UFuncTypeError: Cannot cast ufunc 'sqrt' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

- The sqrt function is unary, meaning it takes one argument

In [7]:
# square - square each element of an array
square_arr = np.square(arr)
print(square_arr)

[  1   4   9  16  25  36  49  64  81 100]


In [9]:
square_arr2 = np.square(arr2)
print(square_arr2)

[121 144 169 196 225 256 289 324 361 400]


In [13]:
# exp - returns the exponent of each element
exp_arr = np.exp(arr)
print(exp_arr)

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [14]:
exp_arr2 = np.exp(arr2)
print(exp_arr2)

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15 1.90734657e+21 6.23514908e+27
 1.50609731e+35 2.68811714e+43]


In [15]:
# log - returns the logarithm of each element according to loge
log_arr = np.log(arr)
print(log_arr)

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [16]:
log_arr2 = np.log(arr2)
print(log_arr2)

[0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894
 3.8918203  4.15888308 4.39444915 4.60517019]


In [19]:
# create float numbers - array
float_arr = np.random.rand(10)
float_arr

array([0.27287349, 0.67660517, 0.89591732, 0.87839501, 0.34362305,
       0.73611805, 0.61878957, 0.94744651, 0.99314909, 0.21960314])

In [26]:
# modf - separates float numbers into integer and remainder parts
residue, whole = np.modf(float_arr)

In [28]:
# residue
print(residue)

[0.27287349 0.67660517 0.89591732 0.87839501 0.34362305 0.73611805
 0.61878957 0.94744651 0.99314909 0.21960314]


In [29]:
# whole
print(whole)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
# create an array of positive and negative numbers
min_plus_arr = np.array([1, -2, 3, -4, 5, -6, 7, -8, 9, 10])
min_plus_arr

array([ 1, -2,  3, -4,  5, -6,  7, -8,  9, 10])

In [31]:
# sign - returns -1 if the array load is negative, 1 if it is positive
sgn_arr = np.sign(min_plus_arr)
print(sgn_arr)

[ 1 -1  1 -1  1 -1  1 -1  1  1]


In [33]:
# Creating an array with mixed NaN elements
nan_arr = np.array([1, np.nan, 2, 3, np.nan, 4, np.nan])
nan_arr

array([ 1., nan,  2.,  3., nan,  4., nan])

In [34]:
# isnan - returns True if the elements contain NaN, otherwise returns False
isnan_arr = np.isnan(nan_arr)
print(isnan_arr)

[False  True False False  True False  True]


###**Bynary functions**

- `add, substract, multiply, divide, power`
- `logical_and, logical_or, equal, greater`

In [35]:
# creates arr1 and arr2
arr1 = np.arange(10, 110, 10)
arr2 = np.arange(110, 210, 10)
print(arr1)
print(arr2)

[ 10  20  30  40  50  60  70  80  90 100]
[110 120 130 140 150 160 170 180 190 200]


In [38]:
# add - adds two arrays element by element
add_arrs = np.add(arr1, arr2)
print(add_arrs)

[120 140 160 180 200 220 240 260 280 300]


In [40]:
# subtract - element by element subtraction
subs_arrs = np.subtract(arr2, arr1) # subtract arr1 from arr2
print(subs_arrs)

[100 100 100 100 100 100 100 100 100 100]


In [41]:
# multiply - element by element multiplication
multp_arrs = np.multiply(arr1, arr2)
print(multp_arrs)

[ 1100  2400  3900  5600  7500  9600 11900 14400 17100 20000]
