<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/where.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Using where as a conditional operator**

- in the following example: elements greater than 4 are retrieved

In [5]:
arr = np.arange(1, 11)
cond1 = np.where(arr > 4)
print(arr)
print(cond1)

[ 1  2  3  4  5  6  7  8  9 10]
(array([4, 5, 6, 7, 8, 9]),)


- if the array element is positive, it will set it to 1, if it is negative, it will set it to 0

In [6]:
arr2 = np.array([1, -2, 3, -4, -5, 6, -7, 8])
cond2 = np.where(arr2 > 0, 1, 0)
print(cond2)

[1 0 1 0 0 1 0 1]


In [7]:
print(arr2)

[ 1 -2  3 -4 -5  6 -7  8]


- if the condition is True, it takes the element of x_arr, otherwise it takes the element of y_arr

In [8]:
x_arr = np.array([1.1, 1.2, 1.3, 1.4])
y_arr = np.array([2.1, 2.2, 2.3, 2.4])

t_f = np.array([True, False, False, True])
cond3 = np.where(t_f, x_arr, y_arr)

In [9]:
print(cond3)

[1.1 2.2 2.3 1.4]
