<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/numpy/where_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

###N1
**What will be the output of the following code ?**
```
import numpy as np  
arr = np.array([10, 20, 30, 40, 50])  
result = np.where(arr > 25, "Big", "Small")  
print(result)
```

In [2]:
# Small, Small, Big, Big, Big

###N2
**Use where to replace even numbers with themselves and odd numbers with 0 in a given array**

In [3]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
res1 = np.where(arr1%2==0, arr1, 0)
print(res1)

[0 2 0 4 0 6 0]


###N3
**Given an array, use np.where to keep positive numbers unchanged and convert negative numbers to their absolute values**

In [4]:
arr2 = np.array([1, -2, 3, -4, 5, -6])
res2 = np.where(arr2>0, arr2, np.abs(arr2))
print(res2)

[1 2 3 4 5 6]


###N4
**Use where to compare two arrays arr1 and arr2, selecting the larger value from each pair**
```
arr1 = np.array([3, 10, 7, 5])  
arr2 = np.array([4, 9, 8, 6])
```

In [7]:
arr3 = np.array([3, 10, 7, 5])
arr4 = np.array([4, 9, 8, 6])
res3 = np.where(arr3>arr4, arr3, arr4)
print(res3)

[ 4 10  8  6]


###N5
**Use where to replace all 0s with 1 and keep other elements unchanged in a given array**

In [9]:
arr5 = np.array([0, 2, 0, 4, 0, 5, 0, 6])
res4 = np.where(arr5==0, 1, arr5)
print(res4)

[1 2 1 4 1 5 1 6]


###N6
**Given the array below, use where to replace negative numbers with their squares and keep positive numbers unchanged**

`arr = np.array([-2, 3, -5, 7, -1, 6])`

In [10]:
arr6 = np.array([-2, 3, -5, 7, -1, 6])
res5 = np.where(arr6<0, arr6**2, arr6)
print(res5)

[ 4  3 25  7  1  6]


###N7
**You have two arrays, arr1 and arr2. Use where to select elements from arr1 if they are divisible by 3, otherwise select elements from arr2**
```
arr1 = np.array([9, 15, 22, 30, 41, 60])  
arr2 = np.array([1, 2, 3, 4, 5, 6])
```

In [11]:
arr7 = np.array([9, 15, 22, 30, 41, 60])
arr8 = np.array([1, 2, 3, 4, 5, 6])
res6 = np.where(arr7%3==0, arr7, arr8)
print(res6)

[ 9 15  3 30  5 60]


###N8
**Create a 3x3 random matrix with values between 1 and 100. Use where to replace elements greater than 50 with "High" and others with "Low"**

In [13]:
arr9 = np.random.randint(1, 100, (3, 3))
res7 = np.where(arr9>50, "High", "Low")
print(res7)

[['Low' 'Low' 'High']
 ['Low' 'High' 'Low']
 ['Low' 'Low' 'High']]
